import { PoolThinker } from "./types";

export const aiGovernancePool: PoolThinker[] = [
  {
    name: "Sam Altman",
    slug: "sam-altman",
    domain: "AI development / OpenAI",
    corePosition: '"Responsible development" while racing toward AGI — the central paradox of the current moment embodied in one person',
    recognitionTier: "anchor",
  },
  {
    name: "Dario Amodei",
    slug: "dario-amodei",
    domain: "AI development / Anthropic",
    corePosition: "Safety and capability can advance together; built the institutional structure (Anthropic) to try to prove it; \"careful race\" as distinct from reckless acceleration",
    recognitionTier: "anchor",
  },
  {
    name: "Shoshana Zuboff",
    slug: "shoshana-zuboff",
    domain: "Surveillance capitalism",
    corePosition: "AI and data systems are a new form of behavioral modification for profit — the real question is who owns human experience",
    recognitionTier: "anchor",
  },
  {
    name: "Marc Andreessen",
    slug: "marc-andreessen",
    domain: "Venture capital",
    corePosition: "Technological acceleration is morally obligatory; governance and regulation are the primary threats to human flourishing",
    recognitionTier: "anchor",
  },
  {
    name: "Eliezer Yudkowsky",
    slug: "eliezer-yudkowsky",
    domain: "AI safety / MIRI",
    corePosition: "Unaligned superintelligence will kill everyone; international coordination is naive; only controlled development with solved alignment works",
    recognitionTier: "anchor",
  },
  {
    name: "Nick Bostrom",
    slug: "nick-bostrom",
    domain: "Existential risk / philosophy",
    corePosition: "Superintelligence is the most important governance problem in history — current regulatory debates are rearranging deck chairs",
    recognitionTier: "anchor",
  },
  {
    name: "Timnit Gebru",
    slug: "timnit-gebru",
    domain: "AI ethics / computer science",
    corePosition: "Structural racism is encoded in AI systems; the problem is not bias to be corrected but power to be redistributed",
    recognitionTier: "anchor",
  },
  {
    name: "Geoffrey Hinton",
    slug: "geoffrey-hinton",
    domain: "Deep learning",
    corePosition: "The godfather who left Google to warn — AI risk is real, current development is reckless, the field built this problem",
    recognitionTier: "anchor",
  },
  {
    name: "Audrey Tang",
    slug: "audrey-tang",
    domain: "Civic technology",
    corePosition: "Democracy and technology are not in tension — Taiwan built governance infrastructure that IS the technology",
    recognitionTier: "anchor",
  },
  {
    name: "Tim Wu",
    slug: "tim-wu",
    domain: 'Law / "The Master Switch"',
    corePosition: "History of communication technologies shows the same capture pattern every time — structural antitrust is the only durable answer",
    recognitionTier: "anchor",
  },
  {
    name: "Cory Doctorow",
    slug: "cory-doctorow",
    domain: "Tech policy / fiction",
    corePosition: '"Enshittification" — platforms extract value from users once locked in; interoperability is the structural fix',
    recognitionTier: "anchor",
  },
  {
    name: "Evgeny Morozov",
    slug: "evgeny-morozov",
    domain: "Tech criticism",
    corePosition: '"Solutionism" — framing social problems as technology problems is itself political capture that forecloses real solutions',
    recognitionTier: "anchor",
  },
  {
    name: "Yuval Noah Harari",
    slug: "yuval-noah-harari",
    domain: "History / philosophy",
    corePosition: "AI will give authoritarian governments unprecedented surveillance and control; the existential threat is political, not technical",
    recognitionTier: "anchor",
  },
  {
    name: "Mustafa Suleyman",
    slug: "mustafa-suleyman",
    domain: "AI development / Microsoft AI",
    corePosition: "AI is ungovernable by current institutions; the only answer is technology that contains itself",
    recognitionTier: "anchor",
  },
  {
    name: "Alan Turing",
    slug: "alan-turing",
    domain: "Mathematics / CS",
    corePosition: "Posed the question of machine intelligence and its limits — everything in AI descends from here, including the governance questions",
    recognitionTier: "anchor",
  },
  {
    name: "Kai-Fu Lee",
    slug: "kai-fu-lee",
    domain: 'AI / "AI Superpowers"',
    corePosition: "AI governance is fundamentally a US-China story; Western regulation frameworks miss the geopolitical reality of a technology race between two systems",
    recognitionTier: "anchor",
  },
  {
    name: "Norbert Wiener",
    slug: "norbert-wiener",
    domain: "Cybernetics",
    corePosition: "Asked in 1950 who controls feedback loops in automated systems — every current AI governance debate descends from his questions",
    recognitionTier: "depth",
  },
  {
    name: "Joseph Weizenbaum",
    slug: "joseph-weizenbaum",
    domain: "Computer science",
    corePosition: "Some decisions must not be delegated to machines regardless of capability — human judgment has irreducible moral dimensions",
    recognitionTier: "depth",
  },
  {
    name: "Herbert Simon",
    slug: "herbert-simon",
    domain: "Political science / AI",
    corePosition: "Bounded rationality — institutions are cognitive artifacts; humans and machines share the same cognitive limits",
    recognitionTier: "depth",
  },
  {
    name: "Langdon Winner",
    slug: "langdon-winner",
    domain: "Philosophy of technology",
    corePosition: '"Do artifacts have politics?" — technology embeds values and power relations before it ever reaches governance',
    recognitionTier: "depth",
  },
  {
    name: "Virginia Eubanks",
    slug: "virginia-eubanks",
    domain: "Poverty / automation",
    corePosition: "Automated systems punish the already-punished — technology makes existing power invisible and unappealable",
    recognitionTier: "depth",
  },
  {
    name: "Joy Buolamwini",
    slug: "joy-buolamwini",
    domain: "Algorithmic justice",
    corePosition: "Founder of Algorithmic Justice League; maps distance between technical neutrality claims and discriminatory outcomes in real systems",
    recognitionTier: "depth",
  },
  {
    name: "Frank Pasquale",
    slug: "frank-pasquale",
    domain: 'Law / "Black Box Society"',
    corePosition: "Algorithms affecting lives must be auditable — the accountability architecture for automated power",
    recognitionTier: "depth",
  },
  {
    name: "Helen Nissenbaum",
    slug: "helen-nissenbaum",
    domain: "Information ethics",
    corePosition: "Contextual integrity — information flows should match social norms; privacy is relational, not absolute",
    recognitionTier: "depth",
  },
  {
    name: "danah boyd",
    slug: "danah-boyd",
    domain: "Media studies / tech",
    corePosition: "Bridges structural critique and platform accountability — power, identity, and youth in networked systems",
    recognitionTier: "depth",
  },
  {
    name: "Bruce Schneier",
    slug: "bruce-schneier",
    domain: "Security / policy",
    corePosition: "Holds security and liberty simultaneously; moved from technical security to systemic critique of surveillance infrastructure",
    recognitionTier: "depth",
  },
  {
    name: "Nick Srnicek",
    slug: "nick-srnicek",
    domain: "Platform capitalism",
    corePosition: "Platforms are a new economic form requiring new governance — ownership, not just regulation, is the real question",
    recognitionTier: "depth",
  },
  {
    name: "Ruha Benjamin",
    slug: "ruha-benjamin",
    domain: "Sociology / race and tech",
    corePosition: "Race is a technology — algorithmic discrimination is designed, not incidental; the next step past bias mitigation",
    recognitionTier: "depth",
  },
  {
    name: "Stuart Russell",
    slug: "stuart-russell",
    domain: 'AI / "Human Compatible"',
    corePosition: "AI systems must be uncertain about human preferences, not optimizing fixed objectives — technical alignment is the missing governance layer",
    recognitionTier: "depth",
  },
  {
    name: "Meredith Whittaker",
    slug: "meredith-whittaker",
    domain: "AI labor / Signal",
    corePosition: "AI infrastructure is concentrated in a few hands; what gets built is shaped by labor dynamics inside companies, not just regulation",
    recognitionTier: "depth",
  },
  {
    name: "Tyler Cowen",
    slug: "tyler-cowen",
    domain: "Economics / Marginal Revolution",
    corePosition: "AI governance slows benefits to the poorest; decentralized experimentation serves humanity better than coordinated design",
    recognitionTier: "depth",
  },
  {
    name: "Balaji Srinivasan",
    slug: "balaji-srinivasan",
    domain: "Tech / Network State",
    corePosition: "Nation-state governance is structurally obsolete for digital systems; network states and exit mechanisms are the real solution",
    recognitionTier: "depth",
  },
  {
    name: "Yochai Benkler",
    slug: "yochai-benkler",
    domain: "Internet law",
    corePosition: "Commons-based peer production — decentralized open systems consistently outperform hierarchical governance as productive forces",
    recognitionTier: "depth",
  },
  {
    name: "Lawrence Lessig",
    slug: "lawrence-lessig",
    domain: "Law / Creative Commons",
    corePosition: "Code is law — and the institutional response is to build better infrastructure, not just critique",
    recognitionTier: "depth",
  },
  {
    name: "Kate Crawford",
    slug: "kate-crawford",
    domain: 'AI studies / "Atlas of AI"',
    corePosition: "AI systems are material — mines, data centers, labor chains; governance ignoring physical infrastructure misses real stakes",
    recognitionTier: "depth",
  },
  {
    name: "Safiya Umoja Noble",
    slug: "safiya-umoja-noble",
    domain: "Information science",
    corePosition: "Search and recommendation systems extend existing oppression through a veneer of neutrality",
    recognitionTier: "depth",
  },
  {
    name: "Gary Marcus",
    slug: "gary-marcus",
    domain: "Cognitive science / AI skeptic",
    corePosition: "Current deep learning systems are fundamentally brittle; AI governance built on inflated capability claims is building on sand",
    recognitionTier: "depth",
  },
  {
    name: "Peter Thiel",
    slug: "peter-thiel",
    domain: "Venture capital / philosophy",
    corePosition: "Competition is destructive; monopoly is the natural state of technology — complicates anti-concentration without dismissing the concern",
    recognitionTier: "depth",
  },
  {
    name: "Danielle Citron",
    slug: "danielle-citron",
    domain: "Law / automated harm",
    corePosition: "Who is legally responsible when an automated system destroys a life — the liability architecture for algorithmic harm",
    recognitionTier: "depth",
  },
  {
    name: "Ryan Calo",
    slug: "ryan-calo",
    domain: "Law / robotics",
    corePosition: "Bridges AI capabilities and legal doctrine — what existing law can and cannot accommodate about autonomous systems",
    recognitionTier: "surprise",
  },
  {
    name: "Robin Hanson",
    slug: "robin-hanson",
    domain: "Economics / prediction markets",
    corePosition: "Governance should be settled by skin-in-the-game prediction, not expert committees — including AI governance",
    recognitionTier: "surprise",
  },
  {
    name: "J.C.R. Licklider",
    slug: "jcr-licklider",
    domain: "Human-computer interaction",
    corePosition: '"Man-Computer Symbiosis" — the original vision of AI as human amplifier; the road not taken that still haunts current design',
    recognitionTier: "surprise",
  },
  {
    name: "Ben Green",
    slug: "ben-green",
    domain: "Tech and democracy",
    corePosition: '"Smart" governance is a trojan horse for technocratic capture of democratic deliberation — the anti-solutionism argument from inside government',
    recognitionTier: "surprise",
  },
];
