import { PoolThinker } from "./types";

export const animalRightsPool: PoolThinker[] = [
  {
    name: "Peter Singer",
    slug: "peter-singer",
    domain: 'Philosophy / "Animal Liberation"',
    corePosition: "Sentience is the only morally relevant criterion — species membership is arbitrary; speciesism is analogous to racism; the utilitarian case for animal equality",
    recognitionTier: "anchor",
  },
  {
    name: "Temple Grandin",
    slug: "temple-grandin",
    domain: "Animal science / autism advocacy",
    corePosition: "Animals can be used ethically if their welfare is genuinely prioritized — designed humane slaughter systems; reform from inside the industry",
    recognitionTier: "anchor",
  },
  {
    name: "Jonathan Safran Foer",
    slug: "jonathan-safran-foer",
    domain: 'Literature / "Eating Animals"',
    corePosition: "Factory farming is the moral catastrophe of our time — the writer's confrontation with what we do to animals for food",
    recognitionTier: "anchor",
  },
  {
    name: "Jane Goodall",
    slug: "jane-goodall",
    domain: "Primatology / conservation",
    corePosition: "Demonstrated that animals have personalities, emotions, and cultures — bridged scientific observation and moral advocacy for chimpanzees and beyond",
    recognitionTier: "anchor",
  },
  {
    name: "Michael Pollan",
    slug: "michael-pollan",
    domain: 'Journalism / "The Omnivore\'s Dilemma"',
    corePosition: "The industrial food system is the problem, not meat-eating per se — ethical omnivory requires knowing where your food comes from",
    recognitionTier: "anchor",
  },
  {
    name: "Frans de Waal",
    slug: "frans-de-waal",
    domain: 'Primatology / "Are We Smart Enough?"',
    corePosition: "Animal cognition is far more sophisticated than science assumed — empathy, justice, and culture exist throughout the animal kingdom",
    recognitionTier: "anchor",
  },
  {
    name: "Tom Regan",
    slug: "tom-regan",
    domain: 'Philosophy / "The Case for Animal Rights"',
    corePosition: 'Animals are "subjects-of-a-life" with inherent value — rights-based rather than utilitarian; you cannot trade animal suffering against human benefit',
    recognitionTier: "depth",
  },
  {
    name: "Martha Nussbaum",
    slug: "martha-nussbaum",
    domain: 'Philosophy / "Justice for Animals"',
    corePosition: "The capabilities approach applied to animals — each species has characteristic forms of flourishing that justice requires us to protect",
    recognitionTier: "depth",
  },
  {
    name: "Gary Francione",
    slug: "gary-francione",
    domain: "Law / abolitionist animal rights",
    corePosition: "Welfarism is collaboration with exploitation — the only coherent position is complete abolition of animal use; reform legitimizes the system",
    recognitionTier: "depth",
  },
  {
    name: "Christine Korsgaard",
    slug: "christine-korsgaard",
    domain: 'Philosophy / "Fellow Creatures"',
    corePosition: "Kantian argument for animal rights — animals are ends in themselves because they have goods of their own; deontological, not just utilitarian",
    recognitionTier: "depth",
  },
  {
    name: "Lori Gruen",
    slug: "lori-gruen",
    domain: 'Philosophy / "Entangled Empathy"',
    corePosition: "Feminist ethics of care applied to animals — relationship, context, and attention matter more than abstract principles",
    recognitionTier: "depth",
  },
  {
    name: "Jonathan Balcombe",
    slug: "jonathan-balcombe",
    domain: 'Ethology / "What a Fish Knows"',
    corePosition: "Fish are sentient, feel pain, and have complex social lives — the frontier of moral consideration extends further than most people assume",
    recognitionTier: "depth",
  },
  {
    name: "Bruce Friedrich",
    slug: "bruce-friedrich",
    domain: "Good Food Institute / cellular agriculture",
    corePosition: "Lab-grown meat is the realistic path — moral arguments have failed for 50 years; technology will succeed where ethics couldn't",
    recognitionTier: "depth",
  },
  {
    name: "Jeff Sebo",
    slug: "jeff-sebo",
    domain: "Philosophy / NYU",
    corePosition: "Animal rights in the age of AI — if we grant moral status based on sentience, the same arguments apply to potentially sentient machines",
    recognitionTier: "depth",
  },
  {
    name: "Cass Sunstein",
    slug: "cass-sunstein",
    domain: "Law / animal welfare regulation",
    corePosition: "Animal welfare through existing legal frameworks — nudges, cost-benefit analysis, and incremental regulation; the pragmatic path",
    recognitionTier: "depth",
  },
  {
    name: "Will Kymlicka & Sue Donaldson",
    slug: "will-kymlicka-sue-donaldson",
    domain: 'Philosophy / "Zoopolis"',
    corePosition: "Political theory for animals — domesticated animals as citizens, wild animals as sovereign communities, liminal animals as residents; beyond rights to political membership",
    recognitionTier: "depth",
  },
  {
    name: "Carol Adams",
    slug: "carol-adams",
    domain: 'Feminist theory / "The Sexual Politics of Meat"',
    corePosition: "The domination of animals and the domination of women share the same logic — patriarchy and carnism are structurally linked",
    recognitionTier: "depth",
  },
  {
    name: "Steven Wise",
    slug: "steven-wise",
    domain: "Law / Nonhuman Rights Project",
    corePosition: "Litigation for legal personhood — habeas corpus for chimpanzees and elephants; using courts to move the boundary of who counts as a legal person",
    recognitionTier: "depth",
  },
  {
    name: "Melanie Joy",
    slug: "melanie-joy",
    domain: 'Psychology / "Why We Love Dogs, Eat Pigs, and Wear Cows"',
    corePosition: '"Carnism" as invisible ideology — the belief system that conditions people to eat certain animals is a social construction, not a natural given',
    recognitionTier: "depth",
  },
  {
    name: "David Favre",
    slug: "david-favre",
    domain: 'Law / "living property"',
    corePosition: "Animals as a new legal category — neither pure property nor full persons; graduated legal status based on cognitive capacity",
    recognitionTier: "depth",
  },
  {
    name: "Roger Scruton",
    slug: "roger-scruton",
    domain: 'Philosophy / "Animal Rights and Wrongs"',
    corePosition: "The conservative case for animal welfare without animal rights — piety, stewardship, and moral sentiment rather than abstract moral status",
    recognitionTier: "depth",
  },
  {
    name: "Kristin Andrews",
    slug: "kristin-andrews",
    domain: "Philosophy / animal minds",
    corePosition: "How to study and assess animal cognition without anthropomorphism — the epistemological challenge of knowing other minds",
    recognitionTier: "surprise",
  },
  {
    name: "Clare Palmer",
    slug: "clare-palmer",
    domain: 'Philosophy / "Animal Ethics in Context"',
    corePosition: "Relational approach — our obligations to animals depend on our relationship to them; we owe more to domesticated animals than wild ones",
    recognitionTier: "surprise",
  },
  {
    name: "Maneesha Deckha",
    slug: "maneesha-deckha",
    domain: "Law / post-colonial animal ethics",
    corePosition: "Western animal rights frameworks erase indigenous and non-Western relationships with animals — decolonizing the ethics conversation",
    recognitionTier: "surprise",
  },
  {
    name: "Oscar Horta",
    slug: "oscar-horta",
    domain: "Philosophy / wild animal suffering",
    corePosition: "Wild animal suffering is the largest moral problem — nature is not a harmony but a slaughterhouse; if suffering matters, wild animals can't be excluded",
    recognitionTier: "surprise",
  },
  {
    name: "Alasdair Cochrane",
    slug: "alasdair-cochrane",
    domain: 'Political philosophy / "Animal Rights Without Liberation"',
    corePosition: 'Animals need political representation, not "liberation" — the framework of political rights applied to animal interests without requiring abolition',
    recognitionTier: "surprise",
  },
  {
    name: "Jacy Reese Anthis",
    slug: "jacy-reese-anthis",
    domain: 'Research / "The End of Animal Farming"',
    corePosition: "The social movement trajectory — animal agriculture will end the way slavery and other institutions ended: through a combination of moral argument, technology, and political pressure",
    recognitionTier: "surprise",
  },
];
