import { PoolThinker } from "./types";

export const bioethicsPool: PoolThinker[] = [
  {
    name: "He Jiankui",
    slug: "he-jiankui",
    domain: "Genetics / CRISPR babies",
    corePosition: "Created the first gene-edited humans in 2018 — the line was crossed, and the question is no longer whether but what comes next",
    recognitionTier: "anchor",
  },
  {
    name: "Jennifer Doudna",
    slug: "jennifer-doudna",
    domain: "Biochemistry / CRISPR co-inventor",
    corePosition: "Developed the tool and then immediately raised alarms about its use — the scientist's responsibility doesn't end at discovery",
    recognitionTier: "anchor",
  },
  {
    name: "Peter Singer",
    slug: "peter-singer",
    domain: 'Philosophy / "Practical Ethics"',
    corePosition: "Preference utilitarianism applied to life, disability, and enhancement — the most controversial bioethicist alive; forces confrontation with moral intuitions",
    recognitionTier: "anchor",
  },
  {
    name: "Francis Fukuyama",
    slug: "francis-fukuyama",
    domain: 'Political philosophy / "Our Posthuman Future"',
    corePosition: "Genetic enhancement threatens human dignity and the equality assumption that grounds liberal democracy — the conservative bioethics case",
    recognitionTier: "anchor",
  },
  {
    name: "Nick Bostrom",
    slug: "nick-bostrom",
    domain: "Philosophy / transhumanism",
    corePosition: 'Enhancement is a moral imperative; humans have a duty to improve their biology — the "why not?" that forces opponents to articulate their actual objection',
    recognitionTier: "anchor",
  },
  {
    name: "Aldous Huxley",
    slug: "aldous-huxley",
    domain: 'Fiction / "Brave New World"',
    corePosition: "The foundational dystopian warning — biological engineering in service of social control produces comfort without freedom",
    recognitionTier: "anchor",
  },
  {
    name: "George Church",
    slug: "george-church",
    domain: "Genetics / Harvard",
    corePosition: "De-extinction, synthetic biology, radical genetic engineering — the maximalist scientific vision of what's technically possible",
    recognitionTier: "anchor",
  },
  {
    name: "Michael Sandel",
    slug: "michael-sandel",
    domain: 'Philosophy / "The Case Against Perfection"',
    corePosition: 'Enhancement destroys the "giftedness" of life — when everything is chosen, gratitude and humility become impossible',
    recognitionTier: "anchor",
  },
  {
    name: "Françoise Baylis",
    slug: "francoise-baylis",
    domain: 'Bioethics / "Altered Inheritance"',
    corePosition: "Heritable genome editing requires global governance and relational ethics — individual consent is meaningless for changes that affect all future descendants",
    recognitionTier: "depth",
  },
  {
    name: "Francis Collins",
    slug: "francis-collins",
    domain: "Genetics / NIH",
    corePosition: "Led the Human Genome Project and consistently argued for guardrails on genetic technology from within the scientific establishment",
    recognitionTier: "depth",
  },
  {
    name: "Siddhartha Mukherjee",
    slug: "siddhartha-mukherjee",
    domain: 'Medicine / "The Gene"',
    corePosition: "The gene as cultural and medical object — history shows that every time we think we understand heredity, we weaponize it",
    recognitionTier: "depth",
  },
  {
    name: "Kazuo Ishiguro",
    slug: "kazuo-ishiguro",
    domain: 'Fiction / "Never Let Me Go"',
    corePosition: "What do we owe created beings? The moral status of engineered life — personhood doesn't depend on origin",
    recognitionTier: "depth",
  },
  {
    name: "Julian Savulescu",
    slug: "julian-savulescu",
    domain: 'Bioethics / "Procreative Beneficence"',
    corePosition: "Parents have a moral obligation to select the best possible children — not doing so when technology permits is a form of harm",
    recognitionTier: "depth",
  },
  {
    name: "Rosemarie Garland-Thomson",
    slug: "rosemarie-garland-thomson",
    domain: "Disability studies",
    corePosition: 'Genetic selection against disability is eugenics rebranded — the "problem" of disability is social, not biological',
    recognitionTier: "depth",
  },
  {
    name: "Leon Kass",
    slug: "leon-kass",
    domain: 'Bioethics / "The Wisdom of Repugnance"',
    corePosition: 'Moral intuition (the "yuck factor") contains genuine wisdom that rational argument cannot capture — some things should not be done regardless of consequences',
    recognitionTier: "depth",
  },
  {
    name: "Ruth Faden",
    slug: "ruth-faden",
    domain: "Bioethics / informed consent",
    corePosition: "The ethics of research on humans requires structural protections, not just individual consent — power asymmetries make voluntary participation fiction without safeguards",
    recognitionTier: "depth",
  },
  {
    name: "Henry Greely",
    slug: "henry-greely",
    domain: 'Law / "The End of Sex"',
    corePosition: "Reproduction will move to the lab within a generation through easy PGT — the legal and social infrastructure isn't remotely ready",
    recognitionTier: "depth",
  },
  {
    name: "Allen Buchanan",
    slug: "allen-buchanan",
    domain: 'Philosophy / "Better than Human"',
    corePosition: "Enhancement is the next stage of the same moral progress that drove civil rights — genetic equality of opportunity is justice, not hubris",
    recognitionTier: "depth",
  },
  {
    name: "Marcy Darnovsky",
    slug: "marcy-darnovsky",
    domain: "Genetics and society / CGS",
    corePosition: "The public, not scientists, should decide the boundaries of genetic technology — democratic governance of biotech against technocratic capture",
    recognitionTier: "depth",
  },
  {
    name: "Paul Knoepfler",
    slug: "paul-knoepfler",
    domain: 'Stem cell biology / "GMO Sapiens"',
    corePosition: "A working scientist's assessment of designer babies — what's actually possible vs. what's hype, and why the gap matters for policy",
    recognitionTier: "depth",
  },
  {
    name: "Adrienne Asch",
    slug: "adrienne-asch",
    domain: "Bioethics / disability rights",
    corePosition: "Prenatal testing communicates that disabled lives are not worth living — the expressivist objection to selective abortion",
    recognitionTier: "depth",
  },
  {
    name: "John Harris",
    slug: "john-harris",
    domain: 'Bioethics / "Enhancing Evolution"',
    corePosition: "There is no coherent distinction between treatment and enhancement — once you accept medicine, you've accepted the principle of improvement",
    recognitionTier: "depth",
  },
  {
    name: "Jürgen Habermas",
    slug: "jurgen-habermas",
    domain: 'Philosophy / "The Future of Human Nature"',
    corePosition: "Genetic engineering of children violates their future autonomy — you cannot consent to being designed; this makes the designer's values permanent",
    recognitionTier: "depth",
  },
  {
    name: "Insoo Hyun",
    slug: "insoo-hyun",
    domain: "Bioethics / stem cells",
    corePosition: "The ethics of chimeras, organoids, and embryo models — new biological entities that don't fit existing moral categories require new frameworks",
    recognitionTier: "depth",
  },
  {
    name: "Donna Haraway",
    slug: "donna-haraway",
    domain: 'Science studies / "Cyborg Manifesto"',
    corePosition: 'The boundary between natural and engineered is always political — "nature" is not a moral category but a rhetorical weapon',
    recognitionTier: "depth",
  },
  {
    name: "Arthur Caplan",
    slug: "arthur-caplan",
    domain: "Bioethics / NYU",
    corePosition: "The pragmatic center of bioethics — technology will advance regardless; the job is to build workable governance, not to stop progress",
    recognitionTier: "depth",
  },
  {
    name: "Dena Davis",
    slug: "dena-davis",
    domain: 'Bioethics / "Genetic Dilemmas"',
    corePosition: 'Children have a "right to an open future" — parental genetic choices that narrow a child\'s possibilities violate their autonomy before they exist',
    recognitionTier: "depth",
  },
  {
    name: "Abdulaziz Sachedina",
    slug: "abdulaziz-sachedina",
    domain: 'Islamic bioethics / "Islamic Biomedical Ethics"',
    corePosition: "Islamic jurisprudence offers a distinct framework for genetic intervention — stewardship of God's creation, the principle of maslaha (public interest), and limits on human sovereignty over life",
    recognitionTier: "depth",
  },
  {
    name: "Kathryn Paige Harden",
    slug: "kathryn-paige-harden",
    domain: 'Behavioral genetics / "The Genetic Lottery"',
    corePosition: "Genetic differences in outcomes are real, not racist to acknowledge, and demand a left-wing policy response — the progressive case for taking genetics seriously",
    recognitionTier: "surprise",
  },
  {
    name: "Tsutomu Sawai",
    slug: "tsutomu-sawai",
    domain: "Bioethics / Japan",
    corePosition: "Japanese bioethics brings different cultural assumptions about nature, harmony, and collective obligation — Western autonomy frameworks are not universal",
    recognitionTier: "surprise",
  },
  {
    name: "Josephine Johnston",
    slug: "josephine-johnston",
    domain: "Bioethics / Hastings Center",
    corePosition: 'The "naturalness" objection to enhancement isn\'t irrational — it tracks real concerns about meaning, effort, and what we value in human achievement',
    recognitionTier: "surprise",
  },
  {
    name: "Nicholas Agar",
    slug: "nicholas-agar",
    domain: 'Philosophy / "Humanity\'s End"',
    corePosition: "Liberal eugenics (parental choice) is acceptable but radical enhancement (posthuman transformation) crosses a line — the moderate enhancement position",
    recognitionTier: "surprise",
  },
  {
    name: "Sheila Jasanoff",
    slug: "sheila-jasanoff",
    domain: "Science and technology studies / Harvard",
    corePosition: "Bioethics without political economy is incomplete — who funds, who regulates, and who profits shapes what \"ethical\" biotechnology looks like",
    recognitionTier: "surprise",
  },
  {
    name: "Ruha Benjamin",
    slug: "ruha-benjamin",
    domain: 'Sociology / "Race After Technology"',
    corePosition: "Genetic technology will reproduce racial hierarchy unless explicitly designed not to — the history of eugenics isn't past, it's being updated",
    recognitionTier: "surprise",
  },
];
