import { PoolThinker } from "./types";

export const capitalismPool: PoolThinker[] = [
  {
    name: "Karl Marx",
    slug: "karl-marx",
    domain: 'Political economy (foundational)',
    corePosition: "Capitalism contains its own contradictions — exploitation of labor, tendency toward crisis, and concentration of wealth are features, not bugs",
    recognitionTier: "anchor",
  },
  {
    name: "Adam Smith",
    slug: "adam-smith",
    domain: 'Economics (foundational) / "The Wealth of Nations"',
    corePosition: "Markets coordinate activity through self-interest better than planning — but also wrote about moral sentiments, regulation, and the dangers of monopoly",
    recognitionTier: "anchor",
  },
  {
    name: "Thomas Piketty",
    slug: "thomas-piketty",
    domain: 'Economics / "Capital in the Twenty-First Century"',
    corePosition: "When r > g (returns on capital exceed growth), inequality automatically increases — capitalism tends toward oligarchy without active redistribution",
    recognitionTier: "anchor",
  },
  {
    name: "Milton Friedman",
    slug: "milton-friedman",
    domain: "Economics / monetarism",
    corePosition: "The free market is both the most efficient and the most moral system — government intervention produces worse outcomes than the problems it addresses",
    recognitionTier: "anchor",
  },
  {
    name: "Naomi Klein",
    slug: "naomi-klein",
    domain: 'Journalism / "The Shock Doctrine"',
    corePosition: 'Capitalism expands through crisis — disaster is not a failure of the system but an opportunity for further extraction; "disaster capitalism"',
    recognitionTier: "anchor",
  },
  {
    name: "Friedrich Hayek",
    slug: "friedrich-hayek",
    domain: 'Economics / "The Road to Serfdom"',
    corePosition: "Central planning is inherently totalitarian — prices contain distributed knowledge no planner can replicate; freedom requires markets",
    recognitionTier: "anchor",
  },
  {
    name: "Mariana Mazzucato",
    slug: "mariana-mazzucato",
    domain: 'Economics / "The Entrepreneurial State"',
    corePosition: "The state creates value, not just corrects market failures — innovation is collectively produced but privately captured; public investment deserves public returns",
    recognitionTier: "anchor",
  },
  {
    name: "Joseph Stiglitz",
    slug: "joseph-stiglitz",
    domain: "Economics / Nobel laureate",
    corePosition: 'Markets are systematically imperfect — information asymmetries, externalities, and power imbalances make "free markets" a fiction; regulation is essential',
    recognitionTier: "anchor",
  },
  {
    name: "Ha-Joon Chang",
    slug: "ha-joon-chang",
    domain: 'Economics / "23 Things"',
    corePosition: "Free-market capitalism is an ideology, not a description — every successful economy used industrial policy, protectionism, and state intervention",
    recognitionTier: "depth",
  },
  {
    name: "David Graeber",
    slug: "david-graeber",
    domain: 'Anthropology / "Debt: The First 5,000 Years"',
    corePosition: "Markets didn't emerge from barter — they were created by states and violence; the origin story of capitalism is a myth that naturalizes what was imposed",
    recognitionTier: "depth",
  },
  {
    name: "Ayn Rand",
    slug: "ayn-rand",
    domain: 'Philosophy / "Atlas Shrugged"',
    corePosition: "Rational self-interest is the highest moral principle — capitalism is the only system consistent with individual rights; altruism is slavery",
    recognitionTier: "depth",
  },
  {
    name: "Richard Wolff",
    slug: "richard-wolff",
    domain: "Economics / Marxian analysis",
    corePosition: "Worker cooperatives are the alternative — not state socialism but democratic workplaces; the exploitation is in the employment relation itself",
    recognitionTier: "depth",
  },
  {
    name: "Kate Raworth",
    slug: "kate-raworth",
    domain: 'Economics / "Doughnut Economics"',
    corePosition: "Growth-dependent economics is obsolete — a thriving economy meets human needs within planetary boundaries; the doughnut, not the GDP line",
    recognitionTier: "depth",
  },
  {
    name: "Branko Milanovic",
    slug: "branko-milanovic",
    domain: 'Economics / "Global Inequality"',
    corePosition: "Global capitalism has lifted billions from poverty while increasing within-country inequality — both stories are true simultaneously",
    recognitionTier: "depth",
  },
  {
    name: "Yanis Varoufakis",
    slug: "yanis-varoufakis",
    domain: 'Economics / "Technofeudalism"',
    corePosition: "Capitalism is already dead — replaced by something worse: platform lords who extract rent from everything; we've moved backward, not forward",
    recognitionTier: "depth",
  },
  {
    name: "Deirdre McCloskey",
    slug: "deirdre-mccloskey",
    domain: "Economics / Bourgeois trilogy",
    corePosition: "The Great Enrichment — capitalism lifted humanity from universal poverty; ideas of liberty and dignity, not exploitation, explain the modern world",
    recognitionTier: "depth",
  },
  {
    name: "Wendy Brown",
    slug: "wendy-brown",
    domain: 'Political theory / "Undoing the Demos"',
    corePosition: "Neoliberalism is not just economic policy — it remakes every domain of life in market terms; democracy, education, and selfhood are all colonized by economic logic",
    recognitionTier: "depth",
  },
  {
    name: "Erik Olin Wright",
    slug: "erik-olin-wright",
    domain: 'Sociology / "Real Utopias"',
    corePosition: '"Real utopias" — worker cooperatives, participatory budgeting, basic income; concrete institutional alternatives that exist now, not revolutionary fantasy',
    recognitionTier: "depth",
  },
  {
    name: "Daron Acemoglu & James Robinson",
    slug: "daron-acemoglu-james-robinson",
    domain: 'Economics / "Why Nations Fail"',
    corePosition: "Inclusive institutions produce prosperity; extractive institutions produce poverty — the political foundations of economic success",
    recognitionTier: "depth",
  },
  {
    name: "Nancy Fraser",
    slug: "nancy-fraser",
    domain: 'Philosophy / "Cannibal Capitalism"',
    corePosition: "Capitalism cannibalizes its own conditions of possibility — nature, care work, and public goods are all consumed without reproduction",
    recognitionTier: "depth",
  },
  {
    name: "Hernando de Soto",
    slug: "hernando-de-soto",
    domain: 'Economics / "The Mystery of Capital"',
    corePosition: "The poor are locked out of capitalism, not victimized by it — property rights formalization is the path out of poverty",
    recognitionTier: "depth",
  },
  {
    name: "Jason Hickel",
    slug: "jason-hickel",
    domain: 'Anthropology / "Less is More"',
    corePosition: 'Degrowth — rich countries must shrink their economies; "green growth" is a contradiction; sufficiency, not efficiency, is the answer',
    recognitionTier: "depth",
  },
  {
    name: "Albert Hirschman",
    slug: "albert-hirschman",
    domain: 'Economics / "Exit, Voice, and Loyalty"',
    corePosition: "Systems improve through the combination of exit (markets) and voice (politics) — neither alone is sufficient; the framework for when to stay and when to leave",
    recognitionTier: "depth",
  },
  {
    name: "Michael Sandel",
    slug: "michael-sandel",
    domain: 'Philosophy / "What Money Can\'t Buy"',
    corePosition: "Markets are appropriate for goods but corrode when applied to civic life — some things should not be for sale; the moral limits of markets",
    recognitionTier: "depth",
  },
  {
    name: "Stephanie Kelton",
    slug: "stephanie-kelton",
    domain: "Economics / MMT",
    corePosition: 'Monetary sovereignty means fiscal constraints are self-imposed — the "we can\'t afford it" argument against social programs is factually wrong',
    recognitionTier: "depth",
  },
  {
    name: "Amartya Sen",
    slug: "amartya-sen",
    domain: "Economics / capabilities approach",
    corePosition: "Development is freedom — GDP is not welfare; what matters is what people can actually do and be, not how much is produced",
    recognitionTier: "depth",
  },
  {
    name: "Kohei Saito",
    slug: "kohei-saito",
    domain: 'Philosophy / "Marx in the Anthropocene"',
    corePosition: "Late Marx was a degrowth communist — the solution to climate change is already in Marx's unpublished notebooks; the Japanese philosopher who made Marx relevant again",
    recognitionTier: "surprise",
  },
  {
    name: "Katharina Pistor",
    slug: "katharina-pistor",
    domain: 'Law / "The Code of Capital"',
    corePosition: "Law creates capital — property, corporations, and financial assets are legal constructions; whoever controls the legal code controls the economy",
    recognitionTier: "surprise",
  },
  {
    name: "Quinn Slobodian",
    slug: "quinn-slobodian",
    domain: 'History / "Crack-Up Capitalism"',
    corePosition: "Neoliberalism was never about free markets — it was about insulating markets from democracy; the history of market radicalism as political project",
    recognitionTier: "surprise",
  },
  {
    name: "Isabella Weber",
    slug: "isabella-weber",
    domain: 'Economics / "How China Escaped Shock Therapy"',
    corePosition: "Managed price controls work — China's heterodox transition succeeded where shock therapy failed; the empirical refutation of market fundamentalism",
    recognitionTier: "surprise",
  },
  {
    name: "Cédric Durand",
    slug: "cedric-durand",
    domain: 'Economics / "Techno-Feudalism"',
    corePosition: "Digital platforms represent a new mode of extraction — not capitalism but something more regressive; rent-seeking at civilizational scale",
    recognitionTier: "surprise",
  },
  {
    name: "Juliet Schor",
    slug: "juliet-schor",
    domain: 'Sociology / "After the Gig"',
    corePosition: 'The platform economy is not liberation but precarity rebranded — "flexibility" serves capital, not workers; the sharing economy was never about sharing',
    recognitionTier: "surprise",
  },
];
