import { PoolThinker } from "./types";

export const climatePool: PoolThinker[] = [
  {
    name: "Greta Thunberg",
    slug: "greta-thunberg",
    domain: "Climate activism",
    corePosition: "The moral clarity position — the science is settled, the failure is political will, and incrementalism is complicity",
    recognitionTier: "anchor",
  },
  {
    name: "Bill Gates",
    slug: "bill-gates",
    domain: 'Energy / "How to Avoid a Climate Disaster"',
    corePosition: "Climate is an engineering problem solvable through innovation, nuclear power, and massive R&D investment — not degrowth or austerity",
    recognitionTier: "anchor",
  },
  {
    name: "Naomi Klein",
    slug: "naomi-klein",
    domain: 'Political economy / "This Changes Everything"',
    corePosition: "Climate change is inseparable from capitalism — you cannot solve the crisis within the system that created it",
    recognitionTier: "anchor",
  },
  {
    name: "Michael Mann",
    slug: "michael-mann",
    domain: 'Climate science / "The New Climate War"',
    corePosition: "The fossil fuel industry's greatest success is shifting blame from systemic actors to individual consumers",
    recognitionTier: "anchor",
  },
  {
    name: "Bjørn Lomborg",
    slug: "bjorn-lomborg",
    domain: 'Economics / "The Skeptical Environmentalist"',
    corePosition: "Climate is real but overhyped relative to other problems — adaptation and innovation beat emissions reduction on cost-effectiveness",
    recognitionTier: "anchor",
  },
  {
    name: "Bill McKibben",
    slug: "bill-mckibben",
    domain: "Environmentalism / 350.org",
    corePosition: "The first popular writer to frame climate as civilizational emergency; divestment and systemic pressure over individual action",
    recognitionTier: "anchor",
  },
  {
    name: "Andreas Malm",
    slug: "andreas-malm",
    domain: 'Human ecology / "How to Blow Up a Pipeline"',
    corePosition: "Nonviolent protest has failed; sabotage of fossil fuel infrastructure is morally justified when legal channels are captured",
    recognitionTier: "anchor",
  },
  {
    name: "Vaclav Smil",
    slug: "vaclav-smil",
    domain: 'Energy systems / "How the World Really Works"',
    corePosition: "Energy transitions take decades, not years; the gap between climate rhetoric and physical reality is enormous and dangerous",
    recognitionTier: "anchor",
  },
  {
    name: "Vandana Shiva",
    slug: "vandana-shiva",
    domain: "Environmental justice / agriculture",
    corePosition: "Climate solutions imposed by the Global North replicate colonialism; indigenous knowledge and seed sovereignty are the real alternatives",
    recognitionTier: "anchor",
  },
  {
    name: "James Hansen",
    slug: "james-hansen",
    domain: "Climate science / NASA",
    corePosition: "The scientist who told Congress in 1988 the crisis was here; nuclear power is essential and environmentalists blocking it are part of the problem",
    recognitionTier: "anchor",
  },
  {
    name: "Kim Stanley Robinson",
    slug: "kim-stanley-robinson",
    domain: 'Science fiction / "The Ministry for the Future"',
    corePosition: "Imagined the governance architecture for a climate-stable world — geoengineering, central bank intervention, eco-terrorism as political forcing function",
    recognitionTier: "anchor",
  },
  {
    name: "Ted Nordhaus",
    slug: "ted-nordhaus",
    domain: "Ecomodernism / Breakthrough Institute",
    corePosition: "Decoupling growth from emissions is possible and desirable — environmentalism's anti-growth impulse is its greatest strategic mistake",
    recognitionTier: "depth",
  },
  {
    name: "Kate Marvel",
    slug: "kate-marvel",
    domain: "Climate science / Columbia",
    corePosition: "Communicates climate science with emotional honesty — grief, uncertainty, and determination coexist; rejects both doom and denial",
    recognitionTier: "depth",
  },
  {
    name: "Ayana Elizabeth Johnson",
    slug: "ayana-elizabeth-johnson",
    domain: "Marine biology / climate policy",
    corePosition: 'Climate solutions must center justice and joy, not just sacrifice — "what can I do?" starts with what you love, not what you fear',
    recognitionTier: "depth",
  },
  {
    name: "Jason Hickel",
    slug: "jason-hickel",
    domain: 'Ecological economics / "Less is More"',
    corePosition: "Degrowth — rich nations must shrink their economies; green growth is a fantasy that lets the Global North avoid accountability",
    recognitionTier: "depth",
  },
  {
    name: "Jesse Jenkins",
    slug: "jesse-jenkins",
    domain: "Energy systems engineering / Princeton",
    corePosition: "Models actual decarbonization pathways — the engineering reality of what a clean grid requires, without ideology",
    recognitionTier: "depth",
  },
  {
    name: "Katharine Hayhoe",
    slug: "katharine-hayhoe",
    domain: "Climate science / evangelical engagement",
    corePosition: "Climate communication across political divides works through shared values, not data — the bridge-building position",
    recognitionTier: "depth",
  },
  {
    name: "Leah Stokes",
    slug: "leah-stokes",
    domain: 'Political science / "Short Circuited"',
    corePosition: "Clean energy policy fails because of organized obstruction, not public opinion — the political economy of who blocks progress and how",
    recognitionTier: "depth",
  },
  {
    name: "Amory Lovins",
    slug: "amory-lovins",
    domain: "Energy / Rocky Mountain Institute",
    corePosition: '"Soft energy paths" — efficiency and renewables make fossil fuels obsolete through market logic, not regulation',
    recognitionTier: "depth",
  },
  {
    name: "Saul Griffith",
    slug: "saul-griffith",
    domain: 'Engineering / "Electrify"',
    corePosition: "Climate is a household-level electrification problem — heat pumps, EVs, induction stoves; the personal IS political when aggregated",
    recognitionTier: "depth",
  },
  {
    name: "Mark Jacobson",
    slug: "mark-jacobson",
    domain: "Civil engineering / Stanford",
    corePosition: "100% renewables is technically feasible now — nuclear and carbon capture are distractions pushed by incumbents",
    recognitionTier: "depth",
  },
  {
    name: "Dipesh Chakrabarty",
    slug: "dipesh-chakrabarty",
    domain: 'History / "The Climate of History"',
    corePosition: "Climate change collapses the distinction between human history and geological time — existing political categories cannot contain it",
    recognitionTier: "depth",
  },
  {
    name: "Fatih Birol",
    slug: "fatih-birol",
    domain: "Energy economics / IEA",
    corePosition: "The institutional voice of global energy data — neither activist nor denialist; models what's actually happening vs. what's pledged",
    recognitionTier: "depth",
  },
  {
    name: "Herman Daly",
    slug: "herman-daly",
    domain: "Ecological economics",
    corePosition: "Steady-state economics — growth is not sustainable on a finite planet; the economy is a subsystem of the biosphere, not the other way around",
    recognitionTier: "depth",
  },
  {
    name: "Sunita Narain",
    slug: "sunita-narain",
    domain: "Environmental policy / India",
    corePosition: "Climate justice means the Global South's right to develop; per-capita emissions are the only fair metric",
    recognitionTier: "depth",
  },
  {
    name: "Stewart Brand",
    slug: "stewart-brand",
    domain: "Whole Earth / ecopragmatism",
    corePosition: '"We are as gods and have to get good at it" — nuclear, GMOs, geoengineering; environmentalists must embrace technology or become irrelevant',
    recognitionTier: "depth",
  },
  {
    name: "Donella Meadows",
    slug: "donella-meadows",
    domain: 'Systems thinking / "Limits to Growth"',
    corePosition: "Modeled planetary boundaries in 1972; the leverage points framework — where to intervene in complex systems",
    recognitionTier: "depth",
  },
  {
    name: "Elizabeth Kolbert",
    slug: "elizabeth-kolbert",
    domain: 'Science journalism / "The Sixth Extinction"',
    corePosition: "Documents the empirical reality of what's being lost — not argument but witness",
    recognitionTier: "depth",
  },
  {
    name: "Olúfẹ́mi Táíwò",
    slug: "olufemi-taiwo",
    domain: "Philosophy / climate reparations",
    corePosition: "Climate justice requires repairing colonial extraction patterns, not just distributing green technology — the reparative frame",
    recognitionTier: "depth",
  },
  {
    name: "David Keith",
    slug: "david-keith",
    domain: "Geoengineering / Harvard",
    corePosition: "Solar geoengineering deserves serious research — the risks of not having this option may exceed the risks of developing it",
    recognitionTier: "depth",
  },
  {
    name: "Robert Howarth",
    slug: "robert-howarth",
    domain: "Ecology / methane research",
    corePosition: 'Demonstrated that natural gas is not a "bridge fuel" — methane leakage makes it as bad as coal; the empirical demolition of a key fossil fuel argument',
    recognitionTier: "depth",
  },
  {
    name: "Kevin Anderson",
    slug: "kevin-anderson",
    domain: "Climate science / Tyndall Centre",
    corePosition: "Carbon budgets are incompatible with economic growth in wealthy nations — the honest math that policymakers refuse to say publicly",
    recognitionTier: "depth",
  },
  {
    name: "Zion Lights",
    slug: "zion-lights",
    domain: "Nuclear advocacy / former Extinction Rebellion",
    corePosition: "The journey from radical activism to pro-nuclear pragmatism — represents a real intellectual transition happening across the environmental movement",
    recognitionTier: "depth",
  },
  {
    name: "Myles Allen",
    slug: "myles-allen",
    domain: "Climate physics / Oxford",
    corePosition: 'Invented the concept of "carbon budgets" and argues that fossil fuel producers, not consumers, should bear capture costs',
    recognitionTier: "depth",
  },
  {
    name: "He Jiankun",
    slug: "he-jiankun",
    domain: "Energy / Tsinghua University",
    corePosition: "The intellectual architecture of China's climate strategy — developing-nation rights, coal phase-down timelines, and carbon market design from inside the world's largest emitter",
    recognitionTier: "surprise",
  },
  {
    name: "Vanessa Nakate",
    slug: "vanessa-nakate",
    domain: "Climate activism / Uganda",
    corePosition: "Climate justice from Africa — the Global South framing that centers those who emit least and suffer most; youth voice from a continent largely absent from climate discourse",
    recognitionTier: "surprise",
  },
  {
    name: "Adrienne Buller",
    slug: "adrienne-buller",
    domain: 'Political economy / "The Value of a Whale"',
    corePosition: "Green finance is a mechanism for capital to profit from the crisis it caused — market-based climate solutions entrench the problem",
    recognitionTier: "surprise",
  },
  {
    name: "Holly Jean Buck",
    slug: "holly-jean-buck",
    domain: 'Geography / "After Geoengineering"',
    corePosition: "Carbon removal is necessary but who controls it determines whether it serves justice or entrenches extraction — the governance of drawdown",
    recognitionTier: "surprise",
  },
  {
    name: "Wim Carton",
    slug: "wim-carton",
    domain: "Human ecology / negative emissions",
    corePosition: "Carbon removal promises allow continued fossil fuel use — the political function of techno-optimism in delaying real change",
    recognitionTier: "surprise",
  },
  {
    name: "Selina Neirok Leem",
    slug: "selina-neirok-leem",
    domain: "Climate diplomacy / Marshall Islands",
    corePosition: "Small island nations face erasure — climate governance from the perspective of those who will lose their country first",
    recognitionTier: "surprise",
  },
  {
    name: "Alice Larkin",
    slug: "alice-larkin",
    domain: "Engineering / Tyndall Centre",
    corePosition: "Shipping and aviation — the sectors everyone's net-zero pledges ignore; the gap between climate targets and the physical infrastructure that makes them impossible",
    recognitionTier: "surprise",
  },
];
