import { PoolThinker } from "./types";

export const consciousnessPool: PoolThinker[] = [
  {
    name: "David Chalmers",
    slug: "david-chalmers",
    domain: 'Philosophy / "The Conscious Mind"',
    corePosition: 'The "hard problem" — explaining why there is something it is like to have experience; functionalism can\'t bridge the explanatory gap',
    recognitionTier: "anchor",
  },
  {
    name: "Daniel Dennett",
    slug: "daniel-dennett",
    domain: 'Philosophy / "Consciousness Explained"',
    corePosition: "The hard problem is an illusion — consciousness IS the functional processing; there's no extra ingredient; eliminative materialism with a smile",
    recognitionTier: "anchor",
  },
  {
    name: "Sam Harris",
    slug: "sam-harris",
    domain: 'Neuroscience / "Waking Up"',
    corePosition: 'Meditation reveals that the self is an illusion — consciousness exists but the "I" observing it does not; neuroscience meets contemplative practice',
    recognitionTier: "anchor",
  },
  {
    name: "Roger Penrose",
    slug: "roger-penrose",
    domain: 'Physics / "The Emperor\'s New Mind"',
    corePosition: "Consciousness involves quantum processes in microtubules — computation alone cannot generate awareness; physics must be revised to accommodate mind",
    recognitionTier: "anchor",
  },
  {
    name: "Antonio Damasio",
    slug: "antonio-damasio",
    domain: 'Neuroscience / "Descartes\' Error"',
    corePosition: "Consciousness is rooted in the body — emotions and feelings are not opposed to reason but constitutive of it; the somatic marker hypothesis",
    recognitionTier: "anchor",
  },
  {
    name: "Anil Seth",
    slug: "anil-seth",
    domain: 'Neuroscience / "Being You"',
    corePosition: 'Consciousness is a "controlled hallucination" — the brain predicts experience rather than receiving it; prediction as the mechanism of awareness',
    recognitionTier: "anchor",
  },
  {
    name: "Iain McGilchrist",
    slug: "iain-mcgilchrist",
    domain: 'Psychiatry / "The Master and His Emissary"',
    corePosition: "Left and right hemisphere process consciousness differently — the left hemisphere's dominance in modern culture distorts our relationship to experience",
    recognitionTier: "anchor",
  },
  {
    name: "Thomas Nagel",
    slug: "thomas-nagel",
    domain: 'Philosophy / "What Is It Like to Be a Bat?"',
    corePosition: "Subjective experience cannot be reduced to objective description — consciousness has an irreducibly first-person character that science can't capture",
    recognitionTier: "depth",
  },
  {
    name: "Philip Goff",
    slug: "philip-goff",
    domain: 'Philosophy / "Galileo\'s Error"',
    corePosition: "Panpsychism — consciousness is fundamental to matter; not an emergent property but a basic feature of the universe; the middle path",
    recognitionTier: "depth",
  },
  {
    name: "Giulio Tononi",
    slug: "giulio-tononi",
    domain: "Neuroscience / Integrated Information Theory",
    corePosition: "Consciousness IS integrated information (Φ) — a mathematical theory that makes consciousness measurable and ubiquitous in any system with sufficient integration",
    recognitionTier: "depth",
  },
  {
    name: "Christof Koch",
    slug: "christof-koch",
    domain: "Neuroscience / Allen Institute",
    corePosition: "The search for neural correlates of consciousness — what specific brain activity patterns correspond to awareness; the empirical program",
    recognitionTier: "depth",
  },
  {
    name: "Patricia Churchland",
    slug: "patricia-churchland",
    domain: 'Neurophilosophy / "Neurophilosophy"',
    corePosition: "Consciousness will be explained by neuroscience — philosophy of mind must be naturalized; folk psychology will be replaced by brain science",
    recognitionTier: "depth",
  },
  {
    name: "Susan Blackmore",
    slug: "susan-blackmore",
    domain: 'Psychology / "Consciousness: An Introduction"',
    corePosition: "Consciousness may be an illusion all the way down — zen meets memes; there is no hard problem because there is no experiencer",
    recognitionTier: "depth",
  },
  {
    name: "Evan Thompson",
    slug: "evan-thompson",
    domain: 'Philosophy / "Waking, Dreaming, Being"',
    corePosition: "Enactivism — consciousness is not in the brain but in the dynamic relationship between organism and environment; draws on Buddhist philosophy",
    recognitionTier: "depth",
  },
  {
    name: "Bernardo Kastrup",
    slug: "bernardo-kastrup",
    domain: "Philosophy / analytic idealism",
    corePosition: "Mind is fundamental, not matter — physical reality is what universal consciousness looks like from the outside; the idealist position with analytic rigor",
    recognitionTier: "depth",
  },
  {
    name: "Keith Frankish",
    slug: "keith-frankish",
    domain: "Philosophy / illusionism",
    corePosition: 'Phenomenal consciousness doesn\'t exist — what we call "qualia" are representational properties, not intrinsic ones; the hard problem dissolves',
    recognitionTier: "depth",
  },
  {
    name: "John Searle",
    slug: "john-searle",
    domain: 'Philosophy / "The Chinese Room"',
    corePosition: "Computation is not sufficient for consciousness — syntax is not semantics; understanding requires biological causation, not just information processing",
    recognitionTier: "depth",
  },
  {
    name: "Francisco Varela",
    slug: "francisco-varela",
    domain: "Neuroscience / neurophenomenology",
    corePosition: "First-person contemplative methods and third-person neuroscience must be integrated — neither alone can explain consciousness",
    recognitionTier: "depth",
  },
  {
    name: "Stanislas Dehaene",
    slug: "stanislas-dehaene",
    domain: 'Neuroscience / "Consciousness and the Brain"',
    corePosition: "Global Workspace Theory — consciousness is what happens when information is broadcast widely across the brain; measurable, specific, and mechanistic",
    recognitionTier: "depth",
  },
  {
    name: "Murray Shanahan",
    slug: "murray-shanahan",
    domain: 'AI / "Embodiment and the Inner Life"',
    corePosition: "If consciousness requires embodiment and interaction with the world, then disembodied AI may never be conscious regardless of computational power",
    recognitionTier: "depth",
  },
  {
    name: "Michael Graziano",
    slug: "michael-graziano",
    domain: 'Neuroscience / "Rethinking Consciousness"',
    corePosition: "Attention Schema Theory — the brain models its own attention, and that self-model IS what consciousness feels like; a specific mechanistic proposal",
    recognitionTier: "depth",
  },
  {
    name: "B. Alan Wallace",
    slug: "b-alan-wallace",
    domain: "Buddhist contemplative science",
    corePosition: "Tibetan Buddhist practices offer rigorous first-person methods for investigating consciousness — Western science without contemplative data is incomplete",
    recognitionTier: "depth",
  },
  {
    name: "Eric Schwitzgebel",
    slug: "eric-schwitzgebel",
    domain: 'Philosophy / "The Weirdness of the World"',
    corePosition: 'Every theory of consciousness has absurd implications — if you\'re not deeply uncomfortable with your view, you haven\'t thought it through; also central to "are LLMs conscious?" debate',
    recognitionTier: "depth",
  },
  {
    name: "Robin Carhart-Harris",
    slug: "robin-carhart-harris",
    domain: "Neuroscience / psychedelics / UCSF",
    corePosition: "The entropic brain theory — psychedelics reveal consciousness as a spectrum from rigid to anarchic; pharmacological evidence for what awareness IS",
    recognitionTier: "depth",
  },
  {
    name: "Peter Godfrey-Smith",
    slug: "peter-godfrey-smith",
    domain: 'Philosophy / "Other Minds"',
    corePosition: "Consciousness likely evolved multiple times independently — octopus minds show radically different architectures for awareness; biology over physics",
    recognitionTier: "depth",
  },
  {
    name: "Joscha Bach",
    slug: "joscha-bach",
    domain: "AI / computational consciousness",
    corePosition: "Consciousness is a specific type of self-model — and it IS computationally reproducible; the strong functionalist position from inside AI research",
    recognitionTier: "depth",
  },
  {
    name: "Hedda Hassel Mørch",
    slug: "hedda-hassel-morch",
    domain: "Philosophy / panpsychism",
    corePosition: "The combination problem — if consciousness is everywhere, how do micro-experiences combine into unified macro-experience? The hardest problem for panpsychism",
    recognitionTier: "surprise",
  },
  {
    name: "Johannes Kleiner",
    slug: "johannes-kleiner",
    domain: "Mathematics / consciousness",
    corePosition: "Mathematical formalization of IIT and other theories — the attempt to make consciousness theories precise enough to actually test and potentially falsify",
    recognitionTier: "surprise",
  },
  {
    name: "Jonathan Birch",
    slug: "jonathan-birch",
    domain: "Philosophy / animal sentience",
    corePosition: "Developed frameworks for assessing sentience in non-human animals — when evidence is uncertain, what's the right threshold for moral consideration?",
    recognitionTier: "surprise",
  },
  {
    name: "Anantanand Rambachan",
    slug: "anantanand-rambachan",
    domain: "Philosophy / Advaita Vedanta",
    corePosition: "Consciousness (Brahman) is the sole fundamental reality; the world is its appearance — 2,000 years of systematic investigation from the Hindu tradition",
    recognitionTier: "surprise",
  },
  {
    name: "Riccardo Manzotti",
    slug: "riccardo-manzotti",
    domain: 'Philosophy / "The Spread Mind"',
    corePosition: "Consciousness is identical with the object perceived — not a representation in the brain but the actual thing in the world; radical externalism",
    recognitionTier: "surprise",
  },
  {
    name: "Miri Albahari",
    slug: "miri-albahari",
    domain: "Philosophy / Buddhist-analytic",
    corePosition: '"Analytical Buddhism" — Buddhist no-self doctrine is philosophically rigorous and compatible with Western consciousness science; the self IS the problem',
    recognitionTier: "surprise",
  },
];
