import { PoolThinker } from "./types";

export const democracyPool: PoolThinker[] = [
  {
    name: "Alexis de Tocqueville",
    slug: "alexis-de-tocqueville",
    domain: "Political philosophy (foundational)",
    corePosition: "Democracy's genius AND its danger — majority tyranny, individualism's corrosion of community, and the habits of heart that sustain self-governance",
    recognitionTier: "anchor",
  },
  {
    name: "Timothy Snyder",
    slug: "timothy-snyder",
    domain: 'History / "On Tyranny"',
    corePosition: "Democracies die through known, repeatable patterns — the warning signs are clear; historical literacy is the first line of defense",
    recognitionTier: "anchor",
  },
  {
    name: "Hannah Arendt",
    slug: "hannah-arendt",
    domain: 'Political philosophy / "The Origins of Totalitarianism"',
    corePosition: "Totalitarianism emerges when atomized, lonely masses lose the capacity for political judgment — democratic collapse is psychological before it's institutional",
    recognitionTier: "anchor",
  },
  {
    name: "Jason Brennan",
    slug: "jason-brennan",
    domain: 'Philosophy / "Against Democracy"',
    corePosition: "Epistocracy — most voters are ignorant or irrational; giving equal political power to the informed and uninformed is not justice but superstition",
    recognitionTier: "anchor",
  },
  {
    name: "Yascha Mounk",
    slug: "yascha-mounk",
    domain: 'Political science / "The People vs. Democracy"',
    corePosition: "Liberal democracy is decomposing into illiberal democracy (populism) or undemocratic liberalism (technocracy) — the twin threats",
    recognitionTier: "anchor",
  },
  {
    name: "Lee Kuan Yew",
    slug: "lee-kuan-yew",
    domain: "Governance / Singapore",
    corePosition: "Good governance matters more than democratic process — a competent state that delivers results has more legitimacy than a dysfunctional democracy",
    recognitionTier: "anchor",
  },
  {
    name: "John Rawls",
    slug: "john-rawls",
    domain: 'Philosophy / "A Theory of Justice"',
    corePosition: 'Justice as fairness — democratic legitimacy requires institutions that everyone could rationally consent to from behind a "veil of ignorance"',
    recognitionTier: "anchor",
  },
  {
    name: "Audrey Tang",
    slug: "audrey-tang",
    domain: "Civic technology / Taiwan",
    corePosition: "Digital democracy works — Taiwan's g0v movement and digital minister role prove that technology can deepen rather than degrade democratic participation",
    recognitionTier: "anchor",
  },
  {
    name: "Steven Levitsky & Daniel Ziblatt",
    slug: "steven-levitsky-daniel-ziblatt",
    domain: 'Political science / "How Democracies Die"',
    corePosition: "Democracies fail through institutional erosion, not coups — norm-breaking by elected leaders is the mechanism; guardrails matter more than elections",
    recognitionTier: "depth",
  },
  {
    name: "Robert Dahl",
    slug: "robert-dahl",
    domain: 'Political science / "Polyarchy"',
    corePosition: 'Democracy is best understood as "polyarchy" — multiple competing centers of power; the conditions that make it possible are specific and fragile',
    recognitionTier: "depth",
  },
  {
    name: "Wendy Brown",
    slug: "wendy-brown",
    domain: 'Political theory / "Undoing the Demos"',
    corePosition: "Neoliberalism is destroying democracy from within — when every value is reduced to market logic, democratic citizenship becomes meaningless",
    recognitionTier: "depth",
  },
  {
    name: "Danielle Allen",
    slug: "danielle-allen",
    domain: 'Political science / "Our Declaration"',
    corePosition: "Democracy requires positive liberty — not just freedom from interference but the capacity to participate; equality and liberty are not in tension",
    recognitionTier: "depth",
  },
  {
    name: "Larry Diamond",
    slug: "larry-diamond",
    domain: 'Political science / "Ill Winds"',
    corePosition: "Democratic recession is global — the empirical documentation of backsliding across dozens of countries since 2006",
    recognitionTier: "depth",
  },
  {
    name: "Hélène Landemore",
    slug: "helene-landemore",
    domain: 'Political science / "Open Democracy"',
    corePosition: "Deliberative democracy and citizens' assemblies — randomly selected citizens make better decisions than elected representatives on complex issues",
    recognitionTier: "depth",
  },
  {
    name: "Adam Przeworski",
    slug: "adam-przeworski",
    domain: 'Political science / "Crises of Democracy"',
    corePosition: "Democracies survive when all parties expect they'll eventually win — the moment a group decides it can never win through elections, democracy is threatened",
    recognitionTier: "depth",
  },
  {
    name: "Pippa Norris",
    slug: "pippa-norris",
    domain: 'Political science / "Cultural Backlash"',
    corePosition: "Authoritarian populism is a cultural backlash against post-material values — generational change triggers reactionary politics as older cohorts feel displaced",
    recognitionTier: "depth",
  },
  {
    name: "Sheldon Wolin",
    slug: "sheldon-wolin",
    domain: 'Political theory / "inverted totalitarianism"',
    corePosition: 'America practices "inverted totalitarianism" — corporate power achieves what fascism achieved through different means; the system looks democratic while functioning otherwise',
    recognitionTier: "depth",
  },
  {
    name: "Anne Applebaum",
    slug: "anne-applebaum",
    domain: 'History / "Twilight of Democracy"',
    corePosition: "Authoritarianism attracts through simplicity — the lure of one-party rule is that it resolves the exhausting complexity of pluralism; why intellectuals betray democracy",
    recognitionTier: "depth",
  },
  {
    name: "Achille Mbembe",
    slug: "achille-mbembe",
    domain: 'Political philosophy / "Necropolitics"',
    corePosition: 'Western democracy was always built on exclusion — colonial subjects, slaves, and the racialized were never included; "democratic" states manage who lives and who dies',
    recognitionTier: "depth",
  },
  {
    name: "Jan-Werner Müller",
    slug: "jan-werner-muller",
    domain: 'Political science / "What Is Populism?"',
    corePosition: 'Populism claims to represent "the real people" against a corrupt elite — anti-pluralist by definition; the key diagnostic for when politics becomes dangerous',
    recognitionTier: "depth",
  },
  {
    name: "David Runciman",
    slug: "david-runciman",
    domain: 'Political science / "How Democracy Ends"',
    corePosition: "Democracies won't die the way they did in the 1930s — they'll die of exhaustion, distraction, and institutional decay; the new failure modes",
    recognitionTier: "depth",
  },
  {
    name: "Martin Gilens & Benjamin Page",
    slug: "martin-gilens-benjamin-page",
    domain: "Political science / oligarchy study",
    corePosition: "Empirical test of U.S. democracy — found that policy outcomes correlate with elite preferences and interest groups, not average citizen preferences; oligarchy by the data",
    recognitionTier: "depth",
  },
  {
    name: "Cornel West",
    slug: "cornel-west",
    domain: "Philosophy / democratic tradition",
    corePosition: "Democracy is not a system but a practice — prophetic witness, solidarity with the dispossessed, and the willingness to be in tension with power",
    recognitionTier: "depth",
  },
  {
    name: "Claudia Chwalisz",
    slug: "claudia-chwalisz",
    domain: "OECD / citizens' assemblies",
    corePosition: "The practical implementation of deliberative democracy — how sortition-based bodies actually work in Dublin, Paris, and beyond",
    recognitionTier: "surprise",
  },
  {
    name: "Yuen Yuen Ang",
    slug: "yuen-yuen-ang",
    domain: 'Political science / "China\'s Gilded Age"',
    corePosition: 'China\'s system is not simply "authoritarian" — it\'s an adaptive governance model with specific accountability mechanisms; the binary of democracy vs. autocracy is too simple',
    recognitionTier: "surprise",
  },
  {
    name: "Arlie Russell Hochschild",
    slug: "arlie-russell-hochschild",
    domain: 'Sociology / "Strangers in Their Own Land"',
    corePosition: 'The emotional logic of why people vote against their interests — the "deep story" of cultural displacement that rational analysis misses',
    recognitionTier: "surprise",
  },
  {
    name: "Astra Taylor",
    slug: "astra-taylor",
    domain: 'Activism / "Democracy May Not Exist"',
    corePosition: 'Democracy has never been achieved — it\'s an aspiration, not a system; the history of who was excluded reveals that "defending democracy" often means defending exclusion',
    recognitionTier: "surprise",
  },
  {
    name: "Daron Acemoglu & James Robinson",
    slug: "daron-acemoglu-james-robinson",
    domain: 'Economics / "The Narrow Corridor"',
    corePosition: 'Democracy survives only in a "narrow corridor" between state capacity and social mobilization — too much of either produces tyranny or anarchy',
    recognitionTier: "surprise",
  },
  {
    name: "Pratap Bhanu Mehta",
    slug: "pratap-bhanu-mehta",
    domain: "Political theory / India",
    corePosition: "Indian democracy as both the world's largest experiment and its most contradictory — caste, Hindu nationalism, and constitutional ideals in permanent tension",
    recognitionTier: "surprise",
  },
  {
    name: "Pierre Rosanvallon",
    slug: "pierre-rosanvallon",
    domain: 'Political theory / "Counter-Democracy"',
    corePosition: "Democracies always generate their own forms of distrust — oversight, veto, and judgment are democratic acts too, not just voting; the French democratic theory tradition",
    recognitionTier: "surprise",
  },
];
