import { PoolThinker } from "./types";

export const drugPolicyPool: PoolThinker[] = [
  {
    name: "Michelle Alexander",
    slug: "michelle-alexander",
    domain: 'Law / "The New Jim Crow"',
    corePosition: "The War on Drugs is the mechanism of a new racial caste system — mass incarceration for drug offenses replaced Jim Crow; the system is designed",
    recognitionTier: "anchor",
  },
  {
    name: "Johann Hari",
    slug: "johann-hari",
    domain: 'Journalism / "Chasing the Scream"',
    corePosition: "Addiction is about disconnection, not chemicals — Portugal's decriminalization works; the punitive model fails by every metric",
    recognitionTier: "anchor",
  },
  {
    name: "Gabor Maté",
    slug: "gabor-mate",
    domain: 'Addiction medicine / "In the Realm of Hungry Ghosts"',
    corePosition: "Addiction is a response to childhood trauma — punishment for addiction is punishment for pain; compassion is the only evidence-based response",
    recognitionTier: "anchor",
  },
  {
    name: "Carl Hart",
    slug: "carl-hart",
    domain: 'Neuroscience / "Drug Use for Grown-Ups"',
    corePosition: "Most drug users are not addicts — responsible adult drug use exists and criminalization is the real harm; the Columbia professor who admitted using heroin responsibly",
    recognitionTier: "anchor",
  },
  {
    name: "Michael Pollan",
    slug: "michael-pollan",
    domain: 'Journalism / "How to Change Your Mind"',
    corePosition: "Psychedelics are legitimate tools for mental health and consciousness exploration — the mainstream rehabilitation of substances demonized for 50 years",
    recognitionTier: "anchor",
  },
  {
    name: "Keith Humphreys",
    slug: "keith-humphreys",
    domain: "Psychiatry / Stanford",
    corePosition: "12-step recovery works, legalization has costs, and drug policy requires balancing liberty with public health — the empirical moderate",
    recognitionTier: "anchor",
  },
  {
    name: "Ethan Nadelmann",
    slug: "ethan-nadelmann",
    domain: "Drug Policy Alliance / reform",
    corePosition: "The intellectual architect of drug policy reform in America — legalization, decriminalization, and harm reduction as the alternative to prohibition",
    recognitionTier: "anchor",
  },
  {
    name: "Mark Kleiman",
    slug: "mark-kleiman",
    domain: 'Public policy / "When Brute Force Fails"',
    corePosition: '"Smart enforcement" — neither legalization nor the war on drugs; targeted, proportional interventions that reduce harm without mass incarceration',
    recognitionTier: "depth",
  },
  {
    name: "Nora Volkow",
    slug: "nora-volkow",
    domain: "Neuroscience / NIDA director",
    corePosition: "Addiction is a brain disease — the neurological model that both reduced stigma and (critics argue) over-medicalized a social problem",
    recognitionTier: "depth",
  },
  {
    name: "João Goulão",
    slug: "joao-goulao",
    domain: "Medicine / Portugal drug policy",
    corePosition: "Architect of Portuguese decriminalization — treated drug use as public health since 2001; the living proof that the alternative works",
    recognitionTier: "depth",
  },
  {
    name: "Sam Quinones",
    slug: "sam-quinones",
    domain: 'Journalism / "Dreamland"',
    corePosition: "Documented how the opioid crisis was manufactured — Purdue Pharma's marketing, pill mills, and the destruction of American communities",
    recognitionTier: "depth",
  },
  {
    name: "Robin Room",
    slug: "robin-room",
    domain: "Sociology / alcohol policy",
    corePosition: "Alcohol is the most harmful drug by societal impact — the double standard between alcohol and illegal drugs reveals that scheduling is cultural, not scientific",
    recognitionTier: "depth",
  },
  {
    name: "David Nutt",
    slug: "david-nutt",
    domain: "Neuropsychopharmacology / UK",
    corePosition: "Published evidence that alcohol and tobacco are more harmful than many illegal drugs — fired from UK advisory panel for stating what the evidence showed",
    recognitionTier: "depth",
  },
  {
    name: "Daniel Ciccarone",
    slug: "daniel-ciccarone",
    domain: "Medicine / UCSF",
    corePosition: "The fentanyl crisis — street drug supply has fundamentally changed; harm reduction must adapt to a reality where every dose could be fatal",
    recognitionTier: "depth",
  },
  {
    name: "Alex Berenson",
    slug: "alex-berenson",
    domain: 'Journalism / "Tell Your Children"',
    corePosition: "Cannabis legalization was premature — the link between marijuana and psychosis is real; the drug is more dangerous than advocates admit",
    recognitionTier: "depth",
  },
  {
    name: "Bruce Alexander",
    slug: "bruce-alexander",
    domain: "Psychology / Rat Park",
    corePosition: "The famous Rat Park experiment — addiction isn't caused by drugs but by environment; isolated rats use compulsively, connected rats don't",
    recognitionTier: "depth",
  },
  {
    name: "Maia Szalavitz",
    slug: "maia-szalavitz",
    domain: 'Journalism / "Unbroken Brain"',
    corePosition: "Addiction as a learning disorder, not a moral failing or a brain disease — the framework that integrates neuroscience with developmental psychology",
    recognitionTier: "depth",
  },
  {
    name: "Rick Doblin",
    slug: "rick-doblin",
    domain: "MAPS founder / psychedelic research",
    corePosition: "Built the research infrastructure for MDMA and psilocybin therapy — decades of work making psychedelic-assisted therapy medically legitimate",
    recognitionTier: "depth",
  },
  {
    name: "Beth Macy",
    slug: "beth-macy",
    domain: 'Journalism / "Dopesick"',
    corePosition: "The human story of the opioid epidemic — communities destroyed by pharmaceutical greed and government indifference",
    recognitionTier: "depth",
  },
  {
    name: "Stanton Peele",
    slug: "stanton-peele",
    domain: 'Psychology / "The Meaning of Addiction"',
    corePosition: "Addiction is not a disease — it's a pattern of behavior that people can and do change without treatment; the anti-disease-model",
    recognitionTier: "depth",
  },
  {
    name: "Kevin Sabet",
    slug: "kevin-sabet",
    domain: "Drug policy / Smart Approaches to Marijuana",
    corePosition: "The case against cannabis commercialization — legalization creates Big Marijuana; the public health moderate who opposes both the War on Drugs AND full legalization",
    recognitionTier: "depth",
  },
  {
    name: "Helena Hansen",
    slug: "helena-hansen",
    domain: "Psychiatry / anthropology",
    corePosition: "White opioid users get treated as patients while Black crack users were treated as criminals — the racial political economy of which drugs get compassion",
    recognitionTier: "depth",
  },
  {
    name: "Leo Beletsky",
    slug: "leo-beletsky",
    domain: "Law and public health / Northeastern",
    corePosition: '"Health in justice" — integrating public health into criminal justice systems; the legal architecture of harm reduction',
    recognitionTier: "surprise",
  },
  {
    name: "Beau Kilmer",
    slug: "beau-kilmer",
    domain: "RAND / drug policy research",
    corePosition: "The wonk's drug policy — what does the evidence actually say about different regulatory models for different substances",
    recognitionTier: "surprise",
  },
  {
    name: "Isaac Campos",
    slug: "isaac-campos",
    domain: 'History / "Home Grown"',
    corePosition: "Mexican marijuana prohibition in the early 1900s — the origins of drug criminalization in racial panic and cultural anxiety, not science",
    recognitionTier: "surprise",
  },
  {
    name: "Don Des Jarlais",
    slug: "don-des-jarlais",
    domain: "Epidemiology / needle exchange",
    corePosition: "Pioneered needle exchange research — proved that providing clean syringes reduces HIV without increasing drug use; the evidence that ended a debate",
    recognitionTier: "surprise",
  },
  {
    name: "Robert DuPont",
    slug: "robert-dupont",
    domain: "Psychiatry / former NIDA director",
    corePosition: "The intellectual case for prohibition — drug availability increases use; permissive policies normalize harm; a recovering society requires firm boundaries",
    recognitionTier: "surprise",
  },
  {
    name: "Bertha Madras",
    slug: "bertha-madras",
    domain: "Psychobiology / Harvard",
    corePosition: "The neuroscience of why cannabis, opioids, and stimulants cause harm — the pharmacological case for caution that reform advocates dismiss too quickly",
    recognitionTier: "surprise",
  },
];
