import { PoolThinker } from "./types";

export const economicDisruptionPool: PoolThinker[] = [
  {
    name: "Daron Acemoglu",
    slug: "daron-acemoglu",
    domain: "Economics / Nobel laureate / MIT",
    corePosition: "The choice between automation and augmentation is a policy choice, not technological destiny — directed innovation can serve workers or replace them",
    recognitionTier: "anchor",
  },
  {
    name: "Andrew Yang",
    slug: "andrew-yang",
    domain: 'Politics / "The War on Normal People"',
    corePosition: "Automation will eliminate millions of jobs; UBI is the necessary response — brought technological unemployment into mainstream political discourse",
    recognitionTier: "anchor",
  },
  {
    name: "Karl Marx",
    slug: "karl-marx",
    domain: "Political economy (foundational)",
    corePosition: "Capitalism's tendency to replace labor with machinery is structural, not accidental — the reserve army of labor; immiseration as systemic feature",
    recognitionTier: "anchor",
  },
  {
    name: "Joseph Schumpeter",
    slug: "joseph-schumpeter",
    domain: 'Economics / "creative destruction"',
    corePosition: "Capitalism progresses through waves of disruption that destroy old industries and create new ones — displacement is the price of innovation",
    recognitionTier: "anchor",
  },
  {
    name: "Thomas Piketty",
    slug: "thomas-piketty",
    domain: 'Economics / "Capital in the Twenty-First Century"',
    corePosition: "When returns on capital exceed growth, inequality increases automatically — AI accelerates this by making capital (machines) substitute for labor",
    recognitionTier: "anchor",
  },
  {
    name: "Tyler Cowen",
    slug: "tyler-cowen",
    domain: 'Economics / "Average Is Over"',
    corePosition: "The economy is bifurcating — those who work effectively with machines will thrive; others face stagnation; the middle is disappearing",
    recognitionTier: "anchor",
  },
  {
    name: "Erik Brynjolfsson",
    slug: "erik-brynjolfsson",
    domain: 'Economics / "The Second Machine Age"',
    corePosition: 'We\'re in a "great restructuring" — technology is racing ahead while institutions lag; the bounty is real but so is the spread',
    recognitionTier: "anchor",
  },
  {
    name: "David Graeber",
    slug: "david-graeber",
    domain: 'Anthropology / "Bullshit Jobs"',
    corePosition: "Half of all jobs are already meaningless — the economy produces work for social control, not productivity; automation could liberate if we let it",
    recognitionTier: "depth",
  },
  {
    name: "David Autor",
    slug: "david-autor",
    domain: "Economics / MIT",
    corePosition: 'The "China shock" papers and automation research — documented that labor markets do NOT self-correct after disruption; transitions can be permanent',
    recognitionTier: "depth",
  },
  {
    name: "Kate Raworth",
    slug: "kate-raworth",
    domain: 'Economics / "Doughnut Economics"',
    corePosition: "Growth-dependent economics is structurally unable to handle automation well — we need an economy designed to thrive without growing",
    recognitionTier: "depth",
  },
  {
    name: "Guy Standing",
    slug: "guy-standing",
    domain: 'Economics / "The Precariat"',
    corePosition: "A new class of insecure workers has emerged — neither proletariat nor middle class; precarity is the defining labor condition of the 21st century",
    recognitionTier: "depth",
  },
  {
    name: "Carlota Perez",
    slug: "carlota-perez",
    domain: 'Economics / "Technological Revolutions"',
    corePosition: "Every technology revolution follows the same pattern — installation phase (inequality spikes) followed by deployment phase (broadly shared gains) — IF policy forces the turn",
    recognitionTier: "depth",
  },
  {
    name: "Mariana Mazzucato",
    slug: "mariana-mazzucato",
    domain: 'Economics / "The Entrepreneurial State"',
    corePosition: "The state funded the research behind AI — the public should own a share of the returns; innovation is collective, profits shouldn't be private",
    recognitionTier: "depth",
  },
  {
    name: "Nick Srnicek",
    slug: "nick-srnicek",
    domain: 'Political economy / "Platform Capitalism"',
    corePosition: "Platform companies extract rent from coordination — owning the infrastructure of work gives more power than owning the means of production",
    recognitionTier: "depth",
  },
  {
    name: "Juliana Bidadanure",
    slug: "juliana-bidadanure",
    domain: "Philosophy / Stanford",
    corePosition: "The philosophical case for UBI as justice — not just a response to automation but a recognition of social contribution that markets can't price",
    recognitionTier: "depth",
  },
  {
    name: "Aaron Benanav",
    slug: "aaron-benanav",
    domain: 'Sociology / "Automation and the Future of Work"',
    corePosition: "Automation is NOT actually accelerating — stagnation and deindustrialization explain unemployment better than robots; the hype is wrong",
    recognitionTier: "depth",
  },
  {
    name: "Pavlina Tcherneva",
    slug: "pavlina-tcherneva",
    domain: 'Economics / "The Case for a Job Guarantee"',
    corePosition: "UBI is the wrong answer — a federal job guarantee provides income, purpose, and community simultaneously; paying people not to work fails on all three",
    recognitionTier: "depth",
  },
  {
    name: "Martin Ford",
    slug: "martin-ford",
    domain: 'Technology / "Rise of the Robots"',
    corePosition: 'White-collar automation is different in kind — when machines can think, the "new jobs will appear" historical argument loses its basis',
    recognitionTier: "depth",
  },
  {
    name: "Stephanie Kelton",
    slug: "stephanie-kelton",
    domain: 'Economics / MMT / "The Deficit Myth"',
    corePosition: 'Fiscal constraints on responding to automation are self-imposed fictions — governments that issue their own currency can fund any transition they choose',
    recognitionTier: "depth",
  },
  {
    name: "Oren Cass",
    slug: "oren-cass",
    domain: 'Conservative economics / "The Once and Future Worker"',
    corePosition: "Work is not just income but identity and community — conservative case for industrial policy and against pure market solutions to disruption",
    recognitionTier: "depth",
  },
  {
    name: "Shoshana Zuboff",
    slug: "shoshana-zuboff",
    domain: 'Business / "Surveillance Capitalism"',
    corePosition: "The new economy doesn't just automate labor — it automates behavior prediction and modification; the real product is human futures",
    recognitionTier: "depth",
  },
  {
    name: "Rutger Bregman",
    slug: "rutger-bregman",
    domain: 'History / "Utopia for Realists"',
    corePosition: "UBI has been proposed by left and right for centuries — the evidence from every pilot is positive; the barrier is political imagination, not economics",
    recognitionTier: "depth",
  },
  {
    name: "Daniel Susskind",
    slug: "daniel-susskind",
    domain: 'Economics / "A World Without Work"',
    corePosition: 'The "complementarity" between humans and machines is temporary — as AI improves, fewer human tasks remain; planning for a post-work world is not premature',
    recognitionTier: "depth",
  },
  {
    name: "Virginia Eubanks",
    slug: "virginia-eubanks",
    domain: 'Political science / "Automating Inequality"',
    corePosition: "Automated systems in welfare, hiring, and housing already punish the poor — the dystopia isn't coming, it's deployed in communities without political power",
    recognitionTier: "surprise",
  },
  {
    name: "Mary Gray",
    slug: "mary-gray",
    domain: 'Anthropology / "Ghost Work"',
    corePosition: "AI requires massive hidden human labor — content moderation, data labeling, training feedback; automation creates new exploited labor, it doesn't eliminate work",
    recognitionTier: "surprise",
  },
  {
    name: "Jason Hickel",
    slug: "jason-hickel",
    domain: 'Anthropology / "Less is More"',
    corePosition: "Economic growth is ecologically impossible and socially unnecessary — automation in a degrowth economy could mean liberation; in a growth economy it means immiseration",
    recognitionTier: "surprise",
  },
  {
    name: "James Bessen",
    slug: "james-bessen",
    domain: 'Economics / "Learning by Doing"',
    corePosition: "Historical evidence shows automation increases demand for labor in automated sectors — but only when workers can access training; the transition mechanism matters",
    recognitionTier: "surprise",
  },
  {
    name: "Kathi Weeks",
    slug: "kathi-weeks",
    domain: 'Political theory / "The Problem with Work"',
    corePosition: 'The demand for full employment is itself ideological — "post-work" politics means refusing the moral framework that equates human value with productivity',
    recognitionTier: "surprise",
  },
  {
    name: "Yuen Yuen Ang",
    slug: "yuen-yuen-ang",
    domain: 'Political science / "China\'s Gilded Age"',
    corePosition: "China's approach to managing economic disruption — state-directed capitalism with different assumptions about government's role; the alternative governance model",
    recognitionTier: "surprise",
  },
];
