import { PoolThinker } from "./types";

export const educationPool: PoolThinker[] = [
  {
    name: "John Dewey",
    slug: "john-dewey",
    domain: 'Philosophy / "Democracy and Education" (foundational)',
    corePosition: "Education is not preparation for life but life itself — learning through doing; democracy requires educated citizens capable of reflective inquiry",
    recognitionTier: "anchor",
  },
  {
    name: "Paulo Freire",
    slug: "paulo-freire",
    domain: 'Education / "Pedagogy of the Oppressed"',
    corePosition: 'Education is either liberation or domestication — "banking education" treats students as passive vessels; critical consciousness as the goal',
    recognitionTier: "anchor",
  },
  {
    name: "Sal Khan",
    slug: "sal-khan",
    domain: 'Khan Academy / "The One World Schoolhouse"',
    corePosition: "Technology can personalize learning at scale — mastery-based progression, AI tutoring, and free access democratize education more than any reform",
    recognitionTier: "anchor",
  },
  {
    name: "Diane Ravitch",
    slug: "diane-ravitch",
    domain: 'Education history / "Reign of Error"',
    corePosition: "Former school choice advocate turned fierce critic — standardized testing and privatization are destroying public education, not improving it",
    recognitionTier: "anchor",
  },
  {
    name: "bell hooks",
    slug: "bell-hooks",
    domain: 'Education / "Teaching to Transgress"',
    corePosition: "The classroom is a site of liberation — engaged pedagogy; education must be holistic, embodied, and connected to students' lived reality",
    recognitionTier: "anchor",
  },
  {
    name: "E.D. Hirsch Jr.",
    slug: "ed-hirsch-jr",
    domain: 'Education / "Cultural Literacy"',
    corePosition: "Shared knowledge matters — progressive education's disdain for content created inequality; disadvantaged children need explicit instruction in the cultural canon",
    recognitionTier: "anchor",
  },
  {
    name: "Ivan Illich",
    slug: "ivan-illich",
    domain: 'Social criticism / "Deschooling Society"',
    corePosition: "Schools are institutions of social control — compulsory education produces conformity, not learning; abolish school and let people learn freely",
    recognitionTier: "anchor",
  },
  {
    name: "Ken Robinson",
    slug: "ken-robinson",
    domain: 'Education / "Creative Schools"',
    corePosition: "Schools kill creativity — the industrial model of education is obsolete; personalization, passion, and creativity should replace standardization and testing",
    recognitionTier: "depth",
  },
  {
    name: "Pasi Sahlberg",
    slug: "pasi-sahlberg",
    domain: 'Education policy / "Finnish Lessons"',
    corePosition: "Finland's success proves that trust, teacher autonomy, and no standardized testing produce better outcomes than accountability regimes",
    recognitionTier: "depth",
  },
  {
    name: "Lisa Delpit",
    slug: "lisa-delpit",
    domain: 'Education / "Other People\'s Children"',
    corePosition: "Progressive pedagogy was designed by and for white middle-class families — Black children need explicit instruction in power codes; good intentions aren't enough",
    recognitionTier: "depth",
  },
  {
    name: "Gloria Ladson-Billings",
    slug: "gloria-ladson-billings",
    domain: "Education / culturally relevant pedagogy",
    corePosition: "Academic success, cultural competence, and critical consciousness can coexist — education doesn't require cultural erasure",
    recognitionTier: "depth",
  },
  {
    name: "Carol Dweck",
    slug: "carol-dweck",
    domain: 'Psychology / "Mindset"',
    corePosition: "Growth mindset — intelligence is not fixed; praising effort over talent changes outcomes; the psychological intervention most adopted by schools",
    recognitionTier: "depth",
  },
  {
    name: "Howard Gardner",
    slug: "howard-gardner",
    domain: "Education / multiple intelligences",
    corePosition: "Intelligence is plural, not singular — linguistic, mathematical, musical, spatial, kinesthetic, interpersonal; schools that measure only two kinds fail most students",
    recognitionTier: "depth",
  },
  {
    name: "Raj Chetty",
    slug: "raj-chetty",
    domain: "Economics / teacher effects",
    corePosition: "A single great teacher in a single year measurably increases lifetime earnings — teacher quality is the highest-leverage in-school factor; the empirical case",
    recognitionTier: "depth",
  },
  {
    name: "Pedro Noguera",
    slug: "pedro-noguera",
    domain: "Education / urban schools",
    corePosition: "Structural racism in schools — discipline disparities, tracking, and resource gaps are deliberate; equity requires confronting the system, not fixing students",
    recognitionTier: "depth",
  },
  {
    name: "Sugata Mitra",
    slug: "sugata-mitra",
    domain: 'Education technology / "Hole in the Wall"',
    corePosition: 'Children can teach themselves with minimal guidance — the Hole in the Wall experiments; "minimally invasive education" and self-organized learning',
    recognitionTier: "depth",
  },
  {
    name: "Jonathan Haidt",
    slug: "jonathan-haidt",
    domain: 'Social psychology / "The Anxious Generation"',
    corePosition: "Smartphones and social media are destroying adolescent mental health — the case for phone-free schools and delayed social media access",
    recognitionTier: "depth",
  },
  {
    name: "Deborah Meier",
    slug: "deborah-meier",
    domain: "Education / small schools movement",
    corePosition: "Small, democratic schools work — Central Park East proved that progressive education succeeds with disadvantaged students when done with rigor and community",
    recognitionTier: "depth",
  },
  {
    name: "Angela Duckworth",
    slug: "angela-duckworth",
    domain: 'Psychology / "Grit"',
    corePosition: "Perseverance and passion predict success better than talent — the character trait most correlated with achievement; controversial for its implied individualism",
    recognitionTier: "depth",
  },
  {
    name: "Yong Zhao",
    slug: "yong-zhao",
    domain: 'Education / "World Class Learners"',
    corePosition: "Standardization kills the qualities most needed for the future — creativity, entrepreneurship, and divergent thinking; the paradox of measuring what doesn't conform",
    recognitionTier: "depth",
  },
  {
    name: "Eva Moskowitz",
    slug: "eva-moskowitz",
    domain: "Success Academy / charter schools",
    corePosition: "High-expectations charter schools prove that poverty is not destiny — if the model works for some children, the system should adopt it for all",
    recognitionTier: "depth",
  },
  {
    name: "Milton Friedman",
    slug: "milton-friedman",
    domain: "Economics / school vouchers",
    corePosition: "Competition improves schools — public monopoly produces mediocrity; vouchers let parents choose and force all schools to improve or close",
    recognitionTier: "depth",
  },
  {
    name: "Gert Biesta",
    slug: "gert-biesta",
    domain: 'Philosophy of education / "The Beautiful Risk of Education"',
    corePosition: "Education is not a technical problem with measurable outcomes — it's a human encounter that necessarily involves risk, unpredictability, and emergence",
    recognitionTier: "surprise",
  },
  {
    name: "Keri Facer",
    slug: "keri-facer",
    domain: 'Education futures / "Learning Futures"',
    corePosition: "Education must prepare students for radical uncertainty — not specific skills but the capacity to imagine and build futures we can't yet describe",
    recognitionTier: "surprise",
  },
  {
    name: "Daisaku Ikeda",
    slug: "daisaku-ikeda",
    domain: "Education philosophy / Soka",
    corePosition: "Value-creating education — learning's purpose is to develop individuals who contribute to others' happiness; Japanese humanistic education philosophy",
    recognitionTier: "surprise",
  },
  {
    name: "Eve Tuck",
    slug: "eve-tuck",
    domain: 'Indigenous education / "Suspending Damage"',
    corePosition: "Deficit research on marginalized communities replicates harm — education research must center desire, sovereignty, and complexity rather than documenting brokenness",
    recognitionTier: "surprise",
  },
  {
    name: "Ethan Hutt",
    slug: "ethan-hutt",
    domain: "Education history / Johns Hopkins",
    corePosition: "The history of grading and assessment — how A-F grades, GPA, and standardized testing became dominant despite thin evidence that they serve learning",
    recognitionTier: "surprise",
  },
  {
    name: "Lant Pritchett",
    slug: "lant-pritchett",
    domain: 'Economics / "The Rebirth of Education"',
    corePosition: 'Most developing-world schools produce "schooling" not learning — enrollment without learning is a global crisis; measuring outcomes not inputs',
    recognitionTier: "surprise",
  },
];
