import { PoolThinker } from "./types";

export const endOfLifePool: PoolThinker[] = [
  {
    name: "Atul Gawande",
    slug: "atul-gawande",
    domain: 'Surgery / "Being Mortal"',
    corePosition: "Medicine's failure is not that people die but that they die badly — the system defaults to aggressive treatment when people want comfort, dignity, and presence",
    recognitionTier: "anchor",
  },
  {
    name: "Elisabeth Kübler-Ross",
    slug: "elisabeth-kubler-ross",
    domain: 'Psychiatry / "On Death and Dying"',
    corePosition: "The five stages of grief — foundational framing of how we process dying; brought death out of medical silence into cultural conversation",
    recognitionTier: "anchor",
  },
  {
    name: "Derek Humphry",
    slug: "derek-humphry",
    domain: 'Right-to-die movement / "Final Exit"',
    corePosition: "Assisted suicide is a fundamental liberty — published the practical guide; the most controversial figure in the American right-to-die movement",
    recognitionTier: "anchor",
  },
  {
    name: "Cicely Saunders",
    slug: "cicely-saunders",
    domain: "Medicine / founded modern hospice",
    corePosition: '"You matter because you are you, and you matter to the last moment of your life" — created the modern hospice movement; total pain, total care',
    recognitionTier: "anchor",
  },
  {
    name: "Paul Kalanithi",
    slug: "paul-kalanithi",
    domain: 'Neurosurgery / "When Breath Becomes Air"',
    corePosition: "The physician facing his own death — what meaning looks like when time is finite and known; memoir as philosophical investigation",
    recognitionTier: "anchor",
  },
  {
    name: "Martin Heidegger",
    slug: "martin-heidegger",
    domain: 'Philosophy / "Being and Time"',
    corePosition: '"Being-toward-death" — authentic existence requires confronting finitude; most of life is fleeing from this confrontation; death gives life meaning',
    recognitionTier: "anchor",
  },
  {
    name: "Ezekiel Emanuel",
    slug: "ezekiel-emanuel",
    domain: 'Bioethics / "Why I Hope to Die at 75"',
    corePosition: "After 75, pursuing longevity diminishes life — creativity, contribution, and vitality decline; accepting mortality at a reasonable age is wisdom, not defeat",
    recognitionTier: "anchor",
  },
  {
    name: "BJ Miller",
    slug: "bj-miller",
    domain: "Palliative medicine / Zen Hospice",
    corePosition: "The art of dying well — design, beauty, and sensory experience matter at the end; dying is not just a medical event but an aesthetic and spiritual one",
    recognitionTier: "depth",
  },
  {
    name: "Ira Byock",
    slug: "ira-byock",
    domain: 'Palliative medicine / "The Four Things That Matter Most"',
    corePosition: '"please forgive me, I forgive you, thank you, I love you" — dying as completion rather than failure; the relational work at the end of life',
    recognitionTier: "depth",
  },
  {
    name: "Jessica Nutik Zitter",
    slug: "jessica-nutik-zitter",
    domain: 'Critical care / "Extreme Measures"',
    corePosition: "The ICU as site of medicalized dying — critical care medicine often extends the dying process rather than treating illness; the courage to stop",
    recognitionTier: "depth",
  },
  {
    name: "Philippe Ariès",
    slug: "philippe-aries",
    domain: 'History / "The Hour of Our Death"',
    corePosition: 'The history of Western death attitudes — from "tamed death" (medieval acceptance) to "invisible death" (modern denial); death is culturally constructed',
    recognitionTier: "depth",
  },
  {
    name: "Caitlin Doughty",
    slug: "caitlin-doughty",
    domain: 'Mortician / "Smoke Gets in Your Eyes"',
    corePosition: "The death-positive movement — reclaiming death from the funeral industry; cultural reform around how we handle bodies and grief",
    recognitionTier: "depth",
  },
  {
    name: "Timothy Quill",
    slug: "timothy-quill",
    domain: "Medicine / physician-assisted dying",
    corePosition: "Published the first account of helping a patient die in a major medical journal (1991) — the physician's case for aid in dying within the doctor-patient relationship",
    recognitionTier: "depth",
  },
  {
    name: "Diane Meier",
    slug: "diane-meier",
    domain: "Geriatrics / Center to Advance Palliative Care",
    corePosition: "Built the institutional infrastructure for palliative care in American hospitals — system change, not just individual practice",
    recognitionTier: "depth",
  },
  {
    name: "Ernest Becker",
    slug: "ernest-becker",
    domain: 'Anthropology / "The Denial of Death"',
    corePosition: "Most human culture is elaborate defense against death anxiety — heroism, religion, and ideology are immortality projects; Terror Management Theory's ancestor",
    recognitionTier: "depth",
  },
  {
    name: "Stephen Jenkinson",
    slug: "stephen-jenkinson",
    domain: 'Palliative care / "Die Wise"',
    corePosition: "Western culture has lost the ability to die — grief-illiteracy and death-phobia produce suffering; dying is a skill that must be relearned",
    recognitionTier: "depth",
  },
  {
    name: "Katy Butler",
    slug: "katy-butler",
    domain: 'Journalism / "Knocking on Heaven\'s Door"',
    corePosition: "The technology of slow dying — pacemakers, feeding tubes, and ICU interventions that extend the dying process; the family's impossible decisions",
    recognitionTier: "depth",
  },
  {
    name: "Sherwin Nuland",
    slug: "sherwin-nuland",
    domain: 'Surgery / "How We Die"',
    corePosition: "The biological reality of dying — stripped of euphemism and denial; death is rarely peaceful and honesty about this changes how we prepare",
    recognitionTier: "depth",
  },
  {
    name: "Thich Nhat Hanh",
    slug: "thich-nhat-hanh",
    domain: 'Buddhism / "No Death, No Fear"',
    corePosition: "Death is a concept, not a reality — cloud becomes rain; continuation rather than cessation; the contemplative tradition's dissolution of the death problem",
    recognitionTier: "depth",
  },
  {
    name: "Sheldon Solomon",
    slug: "sheldon-solomon",
    domain: "Psychology / Terror Management Theory",
    corePosition: "Unconscious death anxiety drives most human behavior — self-esteem, worldview defense, and cultural identification are all anxiety-management strategies",
    recognitionTier: "depth",
  },
  {
    name: "Shelly Kagan",
    slug: "shelly-kagan",
    domain: "Philosophy / Death (Yale course)",
    corePosition: "Deprivation account — death is bad because it deprives us of future good; rigorous analytic engagement with whether and why death is harmful",
    recognitionTier: "depth",
  },
  {
    name: "Kathryn Mannix",
    slug: "kathryn-mannix",
    domain: 'Palliative medicine / "With the End in Mind"',
    corePosition: "What dying actually looks like — demystifying the physical process; most deaths are peaceful when well-managed; the knowledge gap as source of fear",
    recognitionTier: "depth",
  },
  {
    name: "Daniel Sulmasy",
    slug: "daniel-sulmasy",
    domain: "Bioethics / Franciscan",
    corePosition: "The Catholic case against assisted suicide — human dignity is intrinsic, not dependent on quality of life; palliative care, not death, is the answer to suffering",
    recognitionTier: "depth",
  },
  {
    name: "Lois Shepherd",
    slug: "lois-shepherd",
    domain: 'Law / "If That Ever Happens to Me"',
    corePosition: "The legal architecture of advance directives — how living wills work, fail, and get ignored; the gap between documented wishes and clinical reality",
    recognitionTier: "surprise",
  },
  {
    name: "Roshi Joan Halifax",
    slug: "roshi-joan-halifax",
    domain: 'Zen Buddhism / "Being with Dying"',
    corePosition: "Contemplative care for the dying — training presence at the bedside; dying as practice for both the dying person and those attending",
    recognitionTier: "surprise",
  },
  {
    name: "Allan Kellehear",
    slug: "allan-kellehear",
    domain: 'Sociology / "A Social History of Dying"',
    corePosition: "Death is social, not individual — community participation in dying has been destroyed by medicalization and privatization; the public health approach to death",
    recognitionTier: "surprise",
  },
  {
    name: "Lydia Dugdale",
    slug: "lydia-dugdale",
    domain: 'Medicine / "The Lost Art of Dying"',
    corePosition: 'Medieval ars moriendi — the "art of dying" tradition offered community, ritual, and meaning; modern medicine has no equivalent framework',
    recognitionTier: "surprise",
  },
  {
    name: "Samuel Scheffler",
    slug: "samuel-scheffler",
    domain: 'Philosophy / "Death and the Afterlife"',
    corePosition: "What matters for meaning is not personal survival but that humanity continues — the \"afterlife\" that actually matters is collective, not individual",
    recognitionTier: "surprise",
  },
  {
    name: "Haider Warraich",
    slug: "haider-warraich",
    domain: 'Cardiology / "Modern Death"',
    corePosition: "How technology has changed the definition and experience of death — brain death, organ donation, and the increasingly blurry line between alive and dead",
    recognitionTier: "surprise",
  },
];
