import { PoolThinker } from "./types";

export const gazaIsraelPool: PoolThinker[] = [
  {
    name: "Edward Said",
    slug: "edward-said",
    domain: 'Literary criticism / "Orientalism"',
    corePosition: 'Palestine is the paradigmatic case of Western imperialism\'s production of the "Other" — the intellectual foundation of post-colonial critique applied to the conflict',
    recognitionTier: "anchor",
  },
  {
    name: "Benny Morris",
    slug: "benny-morris",
    domain: 'History / "1948"',
    corePosition: 'Israeli "New Historian" who documented the Nakba using Israeli archives — established the factual record of Palestinian displacement, then defended it as necessary',
    recognitionTier: "anchor",
  },
  {
    name: "Norman Finkelstein",
    slug: "norman-finkelstein",
    domain: 'Political science / "The Holocaust Industry"',
    corePosition: "Israel instrumentalizes the Holocaust to shield itself from accountability — the most confrontational critic from within Jewish intellectual tradition",
    recognitionTier: "anchor",
  },
  {
    name: "Rashid Khalidi",
    slug: "rashid-khalidi",
    domain: 'History / "The Hundred Years\' War on Palestine"',
    corePosition: "The conflict is colonial, not bilateral — 100 years of Palestinian dispossession with shifting imperial sponsors; the long historical frame",
    recognitionTier: "anchor",
  },
  {
    name: "Alan Dershowitz",
    slug: "alan-dershowitz",
    domain: 'Law / "The Case for Israel"',
    corePosition: "Israel is the most unfairly criticized nation on earth — applies higher legal and moral standards to its own conduct than any country is held to",
    recognitionTier: "anchor",
  },
  {
    name: "Hannah Arendt",
    slug: "hannah-arendt",
    domain: 'Philosophy / "Eichmann in Jerusalem"',
    corePosition: "Warned against ethnic nationalism in Palestine in the 1940s — the banality of evil and the danger of normalizing occupation; prophetic criticism from a Jewish thinker",
    recognitionTier: "anchor",
  },
  {
    name: "Noam Chomsky",
    slug: "noam-chomsky",
    domain: 'Political criticism / "The Fateful Triangle"',
    corePosition: "U.S. support for Israel is the keystone — without American arms, money, and diplomatic cover, the occupation is unsustainable; the enabling structure",
    recognitionTier: "anchor",
  },
  {
    name: "Peter Beinart",
    slug: "peter-beinart",
    domain: 'Journalism / "The Crisis of Zionism"',
    corePosition: "A liberal Zionist who concluded the two-state solution is dead — argues for equal rights in one state; the evolution that represents a generational shift",
    recognitionTier: "depth",
  },
  {
    name: "Ilan Pappé",
    slug: "ilan-pappe",
    domain: 'History / "The Ethnic Cleansing of Palestine"',
    corePosition: "1948 was deliberate ethnic cleansing, not a war — the maximalist historical critique; challenges the foundational Israeli narrative entirely",
    recognitionTier: "depth",
  },
  {
    name: "Sari Nusseibeh",
    slug: "sari-nusseibeh",
    domain: 'Philosophy / "Once Upon a Country"',
    corePosition: "Palestinian nonviolent intellectual — the case for coexistence and against armed resistance; the position that keeps getting overrun by events",
    recognitionTier: "depth",
  },
  {
    name: "Amira Hass",
    slug: "amira-hass",
    domain: "Journalism / Ha'aretz",
    corePosition: "Israeli journalist who has lived in Gaza and the West Bank — documenting the occupation from inside it; moral witness as journalism",
    recognitionTier: "depth",
  },
  {
    name: "Michael Walzer",
    slug: "michael-walzer",
    domain: 'Philosophy / "Just and Unjust Wars"',
    corePosition: "Just war framework applied to Israel-Palestine — proportionality, discrimination, and when military force is legitimate vs. criminal",
    recognitionTier: "depth",
  },
  {
    name: "Raja Shehadeh",
    slug: "raja-shehadeh",
    domain: 'Law / "Palestinian Walks"',
    corePosition: "International law and lived Palestinian experience — the legal framework for occupation alongside the personal experience of dispossession",
    recognitionTier: "depth",
  },
  {
    name: "Gershom Gorenberg",
    slug: "gershom-gorenberg",
    domain: 'History / "The Accidental Empire"',
    corePosition: "The settlements were never accidental — strategic colonization from day one; the deliberate architecture of permanent occupation",
    recognitionTier: "depth",
  },
  {
    name: "Sara Roy",
    slug: "sara-roy",
    domain: "Political economy / Harvard",
    corePosition: 'Documented "de-development" in Gaza — Israel\'s economic policy deliberately underdevelops Palestinian territory to maintain dependency',
    recognitionTier: "depth",
  },
  {
    name: "David Grossman",
    slug: "david-grossman",
    domain: 'Literature / "To the End of the Land"',
    corePosition: "Israeli novelist who lost a son in the 2006 Lebanon War — the literary voice of Israeli peace movement; writing against despair from inside loss",
    recognitionTier: "depth",
  },
  {
    name: "Nathan Thrall",
    slug: "nathan-thrall",
    domain: 'Journalism / "A Day in the Life of Abed Salama"',
    corePosition: "Documents the everyday reality of occupation through narrative — the system made visible through individual experience",
    recognitionTier: "depth",
  },
  {
    name: "Ian Lustick",
    slug: "ian-lustick",
    domain: 'Political science / "Paradigm Lost"',
    corePosition: "The two-state solution is dead as policy — clinging to it prevents engaging with the one-state reality that already exists",
    recognitionTier: "depth",
  },
  {
    name: "Tareq Baconi",
    slug: "tareq-baconi",
    domain: 'Political analyst / "Hamas Contained"',
    corePosition: "Hamas as political actor, not just terrorist organization — understanding its strategic logic is essential for any resolution",
    recognitionTier: "depth",
  },
  {
    name: "Dahlia Scheindlin",
    slug: "dahlia-scheindlin",
    domain: "Political science / polling",
    corePosition: "Israeli public opinion data — what Israelis actually think, as opposed to what leaders claim; the demographics of the conflict",
    recognitionTier: "depth",
  },
  {
    name: "Judith Butler",
    slug: "judith-butler",
    domain: 'Philosophy / "Parting Ways"',
    corePosition: "Jewish ethics requires opposition to Zionism — the Jewishness of critique; cohabitation as ethical obligation drawn from Jewish thought",
    recognitionTier: "depth",
  },
  {
    name: "Yousef Munayyer",
    slug: "yousef-munayyer",
    domain: "Political analyst / Palestine",
    corePosition: "One democratic state with equal rights is the only just solution — the two-state framework was always a mechanism for managing, not ending, colonization",
    recognitionTier: "depth",
  },
  {
    name: "Michael Oren",
    slug: "michael-oren",
    domain: "History / former ambassador",
    corePosition: "Israel's story is one of miraculous survival against existential threat — strategic depth and military strength are non-negotiable for a surrounded state",
    recognitionTier: "depth",
  },
  {
    name: "Yossi Klein Halevi",
    slug: "yossi-klein-halevi",
    domain: 'Journalism / "Letters to My Palestinian Neighbor"',
    corePosition: "The centrist Israeli narrative — existential fear and desire for coexistence are not contradictory; both peoples have legitimate claims and deep trauma",
    recognitionTier: "depth",
  },
  {
    name: "Ami Ayalon",
    slug: "ami-ayalon",
    domain: "Security / former Shin Bet director",
    corePosition: "The security establishment case for ending the occupation — you cannot defeat an idea with force; security and political resolution are inseparable",
    recognitionTier: "depth",
  },
  {
    name: "Daniel Pipes",
    slug: "daniel-pipes",
    domain: "Political commentary / Middle East Forum",
    corePosition: "The Palestinian national movement must be defeated, not accommodated — Israel wins when its enemies give up; the victory model of conflict resolution",
    recognitionTier: "depth",
  },
  {
    name: "Marwan Muasher",
    slug: "marwan-muasher",
    domain: "Diplomacy / former Jordanian FM",
    corePosition: "The Arab state perspective — what's achievable given regional realities, the limits of normalization, and the Abraham Accords' strategic logic",
    recognitionTier: "depth",
  },
  {
    name: "Meron Benvenisti",
    slug: "meron-benvenisti",
    domain: "Geography / former Jerusalem deputy mayor",
    corePosition: "Mapped the physical infrastructure of occupation — settlements, roads, water — showing how territorial facts made two states physically impossible",
    recognitionTier: "surprise",
  },
  {
    name: "Eyal Weizman",
    slug: "eyal-weizman",
    domain: "Architecture / Forensic Architecture",
    corePosition: "The built environment as evidence of political violence — uses architectural analysis to document and prove what states deny",
    recognitionTier: "surprise",
  },
  {
    name: "Shlomo Sand",
    slug: "shlomo-sand",
    domain: 'History / "The Invention of the Jewish People"',
    corePosition: "Challenges the historical narrative of Jewish exile and return — the ethno-national claims underlying Zionism rest on constructed history",
    recognitionTier: "surprise",
  },
  {
    name: "Diana Buttu",
    slug: "diana-buttu",
    domain: "Law / former PLO legal advisor",
    corePosition: "International law as the framework — occupation, settlements, and collective punishment are illegal under clear legal standards; compliance, not negotiation, is the demand",
    recognitionTier: "surprise",
  },
  {
    name: "Avraham Burg",
    slug: "avraham-burg",
    domain: 'Former Knesset speaker / "The Holocaust Is Over"',
    corePosition: "Israeli establishment figure who broke with the consensus — Zionism must evolve beyond victimhood or destroy itself; internal dissent at the highest level",
    recognitionTier: "surprise",
  },
  {
    name: "Francesca Albanese",
    slug: "francesca-albanese",
    domain: "International law / UN Special Rapporteur",
    corePosition: "The institutional international law position on Palestine — occupation, apartheid framework, and the legal obligations of the international community",
    recognitionTier: "surprise",
  },
  {
    name: "Ruth Gavison",
    slug: "ruth-gavison",
    domain: "Legal philosophy / Israel",
    corePosition: "Defended Zionism as compatible with liberalism and human rights from within legal theory — the philosophical case that a Jewish state need not be exclusionary",
    recognitionTier: "surprise",
  },
  {
    name: "Khaled Hroub",
    slug: "khaled-hroub",
    domain: "Political science / Cambridge",
    corePosition: "The scholarly analysis of Hamas as political movement — Islamist politics, charter evolution, and the gap between Western perception and organizational reality",
    recognitionTier: "surprise",
  },
];
