import { PoolThinker } from "./types";

export const gentrificationPool: PoolThinker[] = [
  {
    name: "Jane Jacobs",
    slug: "jane-jacobs",
    domain: 'Urbanism / "The Death and Life of Great American Cities"',
    corePosition: "Cities thrive through organic density, mixed use, and street-level community — top-down planning destroys what makes neighborhoods work",
    recognitionTier: "anchor",
  },
  {
    name: "Edward Glaeser",
    slug: "edward-glaeser",
    domain: 'Economics / "Triumph of the City"',
    corePosition: "Housing scarcity drives displacement; the solution is building more, everywhere; NIMBYism and zoning restrictions are the real enemy of affordability",
    recognitionTier: "anchor",
  },
  {
    name: "Matthew Desmond",
    slug: "matthew-desmond",
    domain: 'Sociology / "Evicted"',
    corePosition: "Eviction is not a consequence of poverty but a cause of it — the housing system actively produces and reproduces inequality",
    recognitionTier: "anchor",
  },
  {
    name: "Richard Florida",
    slug: "richard-florida",
    domain: 'Urban studies / "The Creative Class"',
    corePosition: "Creative-class economics as both explanation and accelerant of gentrification — named the dynamic and was blamed for encouraging it",
    recognitionTier: "anchor",
  },
  {
    name: "David Harvey",
    slug: "david-harvey",
    domain: 'Geography / "The Right to the City"',
    corePosition: "The city is produced by collective labor — residents have a right to the urban space they create; displacement is theft of collectively produced value",
    recognitionTier: "anchor",
  },
  {
    name: "Henry George",
    slug: "henry-george",
    domain: 'Political economy / "Progress and Poverty"',
    corePosition: "Land value rises from community investment, not owner effort — land value taxation captures public value and prevents speculation",
    recognitionTier: "anchor",
  },
  {
    name: "Ta-Nehisi Coates",
    slug: "ta-nehisi-coates",
    domain: 'Journalism / "The Case for Reparations"',
    corePosition: "Housing segregation and displacement are the mechanism of racial wealth extraction — redlining, urban renewal, and gentrification are chapters of the same story",
    recognitionTier: "depth",
  },
  {
    name: "Neil Smith",
    slug: "neil-smith",
    domain: 'Geography / "The New Urban Frontier"',
    corePosition: 'Gentrification as "rent gap" exploitation — capital moves into disinvested neighborhoods when the gap between current rent and potential rent becomes profitable',
    recognitionTier: "depth",
  },
  {
    name: "Loretta Lees",
    slug: "loretta-lees",
    domain: "Geography / gentrification studies",
    corePosition: 'Distinguished "super-gentrification" and "planetary gentrification" — the process has gone global and intensified beyond early theories',
    recognitionTier: "depth",
  },
  {
    name: "Keeanga-Yamahtta Taylor",
    slug: "keeanga-yamahtta-taylor",
    domain: 'African American studies / "Race for Profit"',
    corePosition: "Federal housing policy has consistently used Black homeownership as a profit extraction mechanism — from redlining to subprime to gentrification",
    recognitionTier: "depth",
  },
  {
    name: "Samuel Stein",
    slug: "samuel-stein",
    domain: 'Urban planning / "Capital City"',
    corePosition: "Real estate capital controls urban planning — planners serve developers unless structurally prevented; the political economy of who shapes cities",
    recognitionTier: "depth",
  },
  {
    name: "Mindy Thompson Fullilove",
    slug: "mindy-thompson-fullilove",
    domain: 'Psychiatry / "Root Shock"',
    corePosition: "Displacement causes measurable psychological and physical harm equivalent to PTSD — community destruction is a public health crisis",
    recognitionTier: "depth",
  },
  {
    name: "Derek Hyra",
    slug: "derek-hyra",
    domain: 'Urban affairs / "Race, Class, and Politics in the Cappuccino City"',
    corePosition: "Political displacement precedes physical displacement — gentrifiers capture governance before residents are priced out",
    recognitionTier: "depth",
  },
  {
    name: "Jenny Schuetz",
    slug: "jenny-schuetz",
    domain: "Housing economics / Brookings",
    corePosition: "The empirical middle ground — some development reduces displacement, some accelerates it; policy details matter more than ideology",
    recognitionTier: "depth",
  },
  {
    name: "Peter Marcuse",
    slug: "peter-marcuse",
    domain: "Urban planning / gentrification and abandonment",
    corePosition: "Gentrification and abandonment are twin products of the same system — capital moves in and out of neighborhoods based on profit, not need",
    recognitionTier: "depth",
  },
  {
    name: "Mehrsa Baradaran",
    slug: "mehrsa-baradaran",
    domain: 'Law / "The Color of Money"',
    corePosition: "Black communities cannot build wealth through homeownership in a system designed to extract from them — the structural trap of housing-as-investment for the marginalized",
    recognitionTier: "depth",
  },
  {
    name: "Ruth Glass",
    slug: "ruth-glass",
    domain: 'Sociology (coined "gentrification")',
    corePosition: "Named the process in 1964 London — working-class neighborhoods invaded by the middle class until the original residents are displaced; the founding observation",
    recognitionTier: "depth",
  },
  {
    name: "William Julius Wilson",
    slug: "william-julius-wilson",
    domain: 'Sociology / "The Truly Disadvantaged"',
    corePosition: "Concentrated poverty in inner cities is structural, not cultural — when middle-class residents leave, institutions collapse; complicates simple anti-gentrification narratives",
    recognitionTier: "depth",
  },
  {
    name: "Raj Chetty",
    slug: "raj-chetty",
    domain: "Economics / Opportunity Insights",
    corePosition: "Neighborhood effects on children's outcomes are measurable and enormous — where you grow up determines your economic future; place matters causally",
    recognitionTier: "depth",
  },
  {
    name: "Sharon Zukin",
    slug: "sharon-zukin",
    domain: 'Sociology / "Naked City"',
    corePosition: '"Authenticity" is gentrification\'s engine and alibi — newcomers seek the character that their presence destroys',
    recognitionTier: "depth",
  },
  {
    name: "Rick Jacobus",
    slug: "rick-jacobus",
    domain: "Community development / community land trusts",
    corePosition: "Permanently affordable housing through shared-equity models — removes land from speculative markets while preserving homeownership pathways",
    recognitionTier: "depth",
  },
  {
    name: "Eve Ewing",
    slug: "eve-ewing",
    domain: 'Sociology / "Ghosts in the Schoolyard"',
    corePosition: "School closings are the mechanism of neighborhood erasure — institutions are community infrastructure; removing them is cultural demolition",
    recognitionTier: "depth",
  },
  {
    name: "Kathe Newman",
    slug: "kathe-newman",
    domain: "Urban planning / Rutgers",
    corePosition: 'Empirically demonstrated that "neighborhood improvement without displacement" is possible under specific policy conditions — the evidence for hopeful intervention',
    recognitionTier: "surprise",
  },
  {
    name: "Brandi Thompson Summers",
    slug: "brandi-thompson-summers",
    domain: 'Geography / "Black in Place"',
    corePosition: "Black placemaking persists under gentrification through cultural practice even when ownership is lost — resistance isn't only about staying",
    recognitionTier: "surprise",
  },
  {
    name: "Tom Slater",
    slug: "tom-slater",
    domain: "Geography / Edinburgh",
    corePosition: 'Critiques the "gentrification is complex" academic position as political cover for inaction — scholarly ambiguity serves power',
    recognitionTier: "surprise",
  },
  {
    name: "Tony Roshan Samara",
    slug: "tony-roshan-samara",
    domain: "Urban studies / Bay Area",
    corePosition: "Regional analysis shows gentrification displaces people from entire metro areas, not just neighborhoods — the scale of the problem exceeds neighborhood-level solutions",
    recognitionTier: "surprise",
  },
  {
    name: "Lance Freeman",
    slug: "lance-freeman",
    domain: "Urban planning / Columbia",
    corePosition: "Empirically found that low-income residents in gentrifying neighborhoods don't always move faster — complicates the displacement narrative with data",
    recognitionTier: "surprise",
  },
  {
    name: "Lorcan Sirr",
    slug: "lorcan-sirr",
    domain: "Housing policy / Ireland",
    corePosition: "The financialization of housing globally — institutional investors buying residential property transforms housing from shelter to asset class; the Dublin case study",
    recognitionTier: "surprise",
  },
];
