import { PoolThinker } from "./types";

export const gunRightsPool: PoolThinker[] = [
  {
    name: "Antonin Scalia",
    slug: "antonin-scalia",
    domain: "Constitutional law / DC v. Heller",
    corePosition: "Individual right interpretation — the Second Amendment protects personal firearm ownership independent of militia service; originalist textualism applied",
    recognitionTier: "anchor",
  },
  {
    name: "John Paul Stevens",
    slug: "john-paul-stevens",
    domain: "Constitutional law / Heller dissent",
    corePosition: "The Second Amendment protects collective militia rights, not individual gun ownership — Heller was decided incorrectly and should be overturned",
    recognitionTier: "anchor",
  },
  {
    name: "Wayne LaPierre",
    slug: "wayne-lapierre",
    domain: "NRA leadership",
    corePosition: '"The only thing that stops a bad guy with a gun is a good guy with a gun" — the organizational embodiment of absolutist gun rights politics in America',
    recognitionTier: "anchor",
  },
  {
    name: "David Hogg",
    slug: "david-hogg",
    domain: "Gun control activism / March for Our Lives",
    corePosition: "Parkland survivor who built a mass movement — generational change in gun politics driven by those who grew up doing active shooter drills",
    recognitionTier: "anchor",
  },
  {
    name: "Shannon Watts",
    slug: "shannon-watts",
    domain: "Gun safety activism / Moms Demand Action",
    corePosition: "Built the grassroots counterweight to the NRA — pragmatic, incremental gun safety as achievable politics",
    recognitionTier: "anchor",
  },
  {
    name: "John Lott",
    slug: "john-lott",
    domain: 'Economics / "More Guns, Less Crime"',
    corePosition: "Empirical case that concealed carry reduces crime — the most-cited and most-contested researcher on the pro-gun side",
    recognitionTier: "anchor",
  },
  {
    name: "Gabby Giffords",
    slug: "gabby-giffords",
    domain: "Gun violence prevention / former Congress",
    corePosition: "Shot in the head, survived, built a movement — the embodiment of gun violence as lived political reality",
    recognitionTier: "anchor",
  },
  {
    name: "Colion Noir",
    slug: "colion-noir",
    domain: "Gun rights media",
    corePosition: "Black gun ownership as civil rights continuity — the Second Amendment protected Black communities when the state wouldn't",
    recognitionTier: "depth",
  },
  {
    name: "Saul Cornell",
    slug: "saul-cornell",
    domain: 'History / "A Well-Regulated Militia"',
    corePosition: "Historically, the Second Amendment meant something between individual right and collective right — the civic republican interpretation",
    recognitionTier: "depth",
  },
  {
    name: "Adam Winkler",
    slug: "adam-winkler",
    domain: 'Law / "Gunfight"',
    corePosition: "Gun rights and gun regulation have always coexisted in American history — the absolutist positions on both sides are historically illiterate",
    recognitionTier: "depth",
  },
  {
    name: "Garen Wintemute",
    slug: "garen-wintemute",
    domain: "Emergency medicine / UC Davis",
    corePosition: "Treats gunshot victims and studies gun violence epidemiologically — the physician's perspective that firearms are a public health crisis requiring public health solutions",
    recognitionTier: "depth",
  },
  {
    name: "Carol Anderson",
    slug: "carol-anderson",
    domain: 'History / "The Second"',
    corePosition: "The Second Amendment was designed to protect slave patrols — the racial origin of gun rights in America; constitutional reverence without historical honesty is complicity",
    recognitionTier: "depth",
  },
  {
    name: "David Kopel",
    slug: "david-kopel",
    domain: "Law / Independence Institute",
    corePosition: "The scholarly case for broad gun rights — comparative analysis showing that armed democracies aren't less safe and disarmed populations aren't safer",
    recognitionTier: "depth",
  },
  {
    name: "Robert Spitzer",
    slug: "robert-spitzer",
    domain: 'Political science / "The Politics of Gun Control"',
    corePosition: "The gun debate is structurally asymmetric — intensity of preference gives gun owners disproportionate political power relative to their numbers",
    recognitionTier: "depth",
  },
  {
    name: "Philip Cook",
    slug: "philip-cook",
    domain: "Economics / Duke",
    corePosition: 'The "guns as risk factor" framework — firearms in the home increase suicide, homicide, and accident risk; the epidemiological case against prevalence',
    recognitionTier: "depth",
  },
  {
    name: "Stephen Halbrook",
    slug: "stephen-halbrook",
    domain: "Law / Second Amendment litigation",
    corePosition: "The litigation engine behind expanding gun rights — argued multiple Supreme Court cases; the legal architecture of the individual right",
    recognitionTier: "depth",
  },
  {
    name: "Firmin DeBrabander",
    slug: "firmin-debrabander",
    domain: 'Philosophy / "Do Guns Make Us Free?"',
    corePosition: "Guns don't secure freedom — they undermine democratic public life by introducing threat into civic space; armed society is not polite society",
    recognitionTier: "depth",
  },
  {
    name: "Michael Waldman",
    slug: "michael-waldman",
    domain: 'Law / "The Second Amendment: A Biography"',
    corePosition: "The individual right interpretation was a political project, not a historical discovery — the NRA rewrote constitutional meaning over 40 years",
    recognitionTier: "depth",
  },
  {
    name: "Maj Toure",
    slug: "maj-toure",
    domain: "Gun rights / Black Guns Matter",
    corePosition: "Armed self-reliance for marginalized communities — gun rights as anti-paternalism; don't outsource your safety to a state that doesn't protect you",
    recognitionTier: "depth",
  },
  {
    name: "Joseph Blocher",
    slug: "joseph-blocher",
    domain: "Law / Duke",
    corePosition: 'The "marketplace of violence" — Second Amendment doctrine needs limiting principles just like First Amendment doctrine has; rights require boundaries',
    recognitionTier: "depth",
  },
  {
    name: "Daniel Webster",
    slug: "daniel-webster",
    domain: "Public health / Johns Hopkins",
    corePosition: "Evidence-based policy — permit-to-purchase, extreme risk laws, and dealer regulations are the interventions with strongest empirical support",
    recognitionTier: "depth",
  },
  {
    name: "Nicholas Johnson",
    slug: "nicholas-johnson",
    domain: 'Law / "Negroes and the Gun"',
    corePosition: "The long history of Black armed self-defense in America — from Reconstruction through the civil rights movement; gun rights as survival",
    recognitionTier: "depth",
  },
  {
    name: "Jonathan Metzl",
    slug: "jonathan-metzl",
    domain: 'Psychiatry / "Dying of Whiteness"',
    corePosition: "White men vote against gun regulation even as they die from gun suicide at epidemic rates — racial identity overrides self-interest",
    recognitionTier: "depth",
  },
  {
    name: "Devin Hughes",
    slug: "devin-hughes",
    domain: "Gun violence research / GVPedia",
    corePosition: "Meta-analysis of gun research — when you control for study quality, the evidence overwhelmingly supports that more guns correlate with more death",
    recognitionTier: "depth",
  },
  {
    name: "Jennifer Carlson",
    slug: "jennifer-carlson",
    domain: 'Sociology / "Citizen-Protectors"',
    corePosition: "Ethnography of concealed carriers — gun ownership as masculine identity and citizenship performance, not just self-defense",
    recognitionTier: "surprise",
  },
  {
    name: "Patrick Charles",
    slug: "patrick-charles",
    domain: 'History / "Armed in America"',
    corePosition: "The full 400-year history of gun regulation in America — demonstrates that regulation was the norm, not the exception, until recently",
    recognitionTier: "surprise",
  },
  {
    name: "Angela Stroud",
    slug: "angela-stroud",
    domain: 'Sociology / "Good Guys with Guns"',
    corePosition: "Women concealed carriers navigate gendered expectations — the intersection of gun ownership, feminism, and vulnerability",
    recognitionTier: "surprise",
  },
  {
    name: "Rebecca Peters",
    slug: "rebecca-peters",
    domain: "Gun control / Australia",
    corePosition: "Architected Australia's post-Port Arthur gun buyback — the international case study of what comprehensive reform looks like and what it achieves",
    recognitionTier: "surprise",
  },
  {
    name: "Dennis Henigan",
    slug: "dennis-henigan",
    domain: "Law / Brady Campaign",
    corePosition: "The most sustained legal advocate for gun regulation — decades of litigation, legislation, and the argument that Heller doesn't prevent reasonable regulation",
    recognitionTier: "surprise",
  },
  {
    name: "David Yamane",
    slug: "david-yamane",
    domain: 'Sociology / "Gun Curious"',
    corePosition: "The sociology of gun culture from a scholar who became a gun owner during research — the gap between how outsiders imagine gun culture and its actual texture",
    recognitionTier: "surprise",
  },
];
