import { PoolThinker } from "./types";

export const homelessnessPool: PoolThinker[] = [
  {
    name: "Matthew Desmond",
    slug: "matthew-desmond",
    domain: 'Sociology / "Evicted" & "Poverty, by America"',
    corePosition: "Poverty is not a condition people fall into but something actively produced by those who benefit from it — eviction is the mechanism, not the result",
    recognitionTier: "anchor",
  },
  {
    name: "Sam Tsemberis",
    slug: "sam-tsemberis",
    domain: "Psychiatry / Housing First",
    corePosition: "Housing First works — give people housing unconditionally, then address other issues; the evidence is clear and resistance is ideological, not empirical",
    recognitionTier: "anchor",
  },
  {
    name: "Michael Shellenberger",
    slug: "michael-shellenberger",
    domain: 'Journalism / "San Fransicko"',
    corePosition: "Progressive cities enabled homelessness through permissiveness on drugs and crime; compassion without accountability produces more suffering, not less",
    recognitionTier: "anchor",
  },
  {
    name: "Gabor Maté",
    slug: "gabor-mate",
    domain: 'Addiction medicine / "In the Realm of Hungry Ghosts"',
    corePosition: "Addiction is a response to childhood trauma and disconnection — punishing addicted homeless people is punishing them for being wounded",
    recognitionTier: "anchor",
  },
  {
    name: "Marybeth Shinn",
    slug: "marybeth-shinn",
    domain: "Psychology / homelessness research",
    corePosition: "Decades of longitudinal research shows homelessness is primarily caused by housing affordability, not individual pathology — the data is unambiguous",
    recognitionTier: "anchor",
  },
  {
    name: "Philip Alston",
    slug: "philip-alston",
    domain: "Human rights / UN Special Rapporteur",
    corePosition: "The U.S. criminalizes poverty while maintaining the world's highest incarceration rate — homelessness is a human rights violation, not a policy puzzle",
    recognitionTier: "anchor",
  },
  {
    name: "Dennis Culhane",
    slug: "dennis-culhane",
    domain: "Social policy / Penn",
    corePosition: "Pioneered the data infrastructure for understanding homelessness — demonstrated that a small chronic population consumes most resources; targeted intervention works",
    recognitionTier: "depth",
  },
  {
    name: "Margot Kushel",
    slug: "margot-kushel",
    domain: "Medicine / UCSF Benioff Homelessness",
    corePosition: "The California PATH study — documented that the overwhelming majority of homeless Californians became homeless in California due to housing costs, not migration",
    recognitionTier: "depth",
  },
  {
    name: "Gregg Colburn",
    slug: "gregg-colburn",
    domain: 'Real estate / "Homelessness Is a Housing Problem"',
    corePosition: "Cross-city data proves homelessness rates correlate with housing costs, not mental illness or drug use rates — the supply explanation",
    recognitionTier: "depth",
  },
  {
    name: "Randall Kuhn",
    slug: "randall-kuhn",
    domain: "Public health / UCLA",
    corePosition: "Health consequences of homelessness are measurable and catastrophic — life expectancy on the street is 20-30 years shorter; housing is healthcare",
    recognitionTier: "depth",
  },
  {
    name: "Brendan O'Flaherty",
    slug: "brendan-oflaherty",
    domain: 'Economics / "Making Room"',
    corePosition: "Homelessness is an economic phenomenon requiring economic analysis — rational actors in irrational markets; the microeconomics of who falls out",
    recognitionTier: "depth",
  },
  {
    name: "Sara Rankin",
    slug: "sara-rankin",
    domain: "Law / criminalization of poverty",
    corePosition: "Anti-camping ordinances, hostile architecture, and sweeps don't reduce homelessness — they redistribute it and add criminal records that prevent housing",
    recognitionTier: "depth",
  },
  {
    name: "Ann Oliva",
    slug: "ann-oliva",
    domain: "Housing policy / former HUD",
    corePosition: "The federal policy architecture of homelessness — Continuum of Care, HMIS data systems, and coordinated entry as bureaucratic infrastructure",
    recognitionTier: "depth",
  },
  {
    name: "Keith Humphreys",
    slug: "keith-humphreys",
    domain: "Psychiatry / Stanford",
    corePosition: "Substance abuse treatment works and should be available before, during, and after housing — Housing First is necessary but not sufficient without treatment access",
    recognitionTier: "depth",
  },
  {
    name: "Jennifer Friedenbach",
    slug: "jennifer-friedenbach",
    domain: "Advocacy / Coalition on Homelessness SF",
    corePosition: "Direct advocacy from the street level — the gap between policy research and lived experience; what looks rational from a desk looks different from a tent",
    recognitionTier: "depth",
  },
  {
    name: "Thomas Main",
    slug: "thomas-main",
    domain: 'Political science / "Homelessness in New York City"',
    corePosition: "New York's right-to-shelter model produces different outcomes than West Coast approaches — legal frameworks shape what homelessness looks like",
    recognitionTier: "depth",
  },
  {
    name: "Deborah Padgett",
    slug: "deborah-padgett",
    domain: 'Social work / "Housing First"',
    corePosition: "The qualitative research behind Housing First — what stability means to people who haven't had it; the phenomenology of home",
    recognitionTier: "depth",
  },
  {
    name: "Alex Vitale",
    slug: "alex-vitale",
    domain: 'Sociology / "The End of Policing"',
    corePosition: "Police are the wrong response to homelessness, mental health crises, and addiction — the entire crisis response system needs redesign",
    recognitionTier: "depth",
  },
  {
    name: "Kevin Corinth",
    slug: "kevin-corinth",
    domain: "Economics / AEI",
    corePosition: "Conservative housing economist — homelessness is partly about housing costs AND partly about behavioral health; both-and, not either-or",
    recognitionTier: "depth",
  },
  {
    name: "Chris Herring",
    slug: "chris-herring",
    domain: 'Sociology / "Complaint"',
    corePosition: 'Encampment sweeps are driven by business complaints, not evidence — the political economy of who gets listened to when homeless people are "the problem"',
    recognitionTier: "depth",
  },
  {
    name: "Nan Roman",
    slug: "nan-roman",
    domain: "Policy / National Alliance to End Homelessness",
    corePosition: "The pragmatic center of homelessness policy — built the infrastructure of coordinated entry, data-driven intervention, and system redesign",
    recognitionTier: "depth",
  },
  {
    name: "Juha Kaakinen",
    slug: "juha-kaakinen",
    domain: "Housing policy / Y-Foundation Finland",
    corePosition: "Finland reduced homelessness by 35% through Housing First at national scale — the proof that a wealthy country can actually solve this if it chooses to",
    recognitionTier: "surprise",
  },
  {
    name: "Loïc Wacquant",
    slug: "loic-wacquant",
    domain: 'Sociology / "Punishing the Poor"',
    corePosition: "Neoliberalism requires punitive management of those it discards — mass incarceration and homelessness criminalization are the same project",
    recognitionTier: "surprise",
  },
  {
    name: "Leilani Farha",
    slug: "leilani-farha",
    domain: "Human rights / UN Housing Rapporteur",
    corePosition: "Housing is a human right under international law — the financialization of housing globally is the structural cause; the international frame",
    recognitionTier: "surprise",
  },
  {
    name: "Mitchell Duneier",
    slug: "mitchell-duneier",
    domain: 'Sociology / "Sidewalk"',
    corePosition: "Ethnography of street life in New York — unhoused people maintain complex social worlds, economic lives, and dignity systems invisible to passersby",
    recognitionTier: "surprise",
  },
  {
    name: "DJ Jaffe",
    slug: "dj-jaffe",
    domain: 'Mental illness policy / "Insane Consequences"',
    corePosition: "Severe mental illness drives chronic homelessness — deinstitutionalization without community treatment was the policy failure; involuntary treatment saves lives",
    recognitionTier: "surprise",
  },
];
