import { PoolThinker } from "./types";

export const immigrationPool: PoolThinker[] = [
  {
    name: "George Borjas",
    slug: "george-borjas",
    domain: "Economics / Harvard",
    corePosition: "Immigration reduces wages for native low-skill workers — the most cited economist on the restrictionist side; the supply-and-demand argument",
    recognitionTier: "anchor",
  },
  {
    name: "Bryan Caplan",
    slug: "bryan-caplan",
    domain: 'Economics / "Open Borders"',
    corePosition: "Open borders would double world GDP — the moral and economic case for near-complete freedom of movement; borders are the greatest injustice",
    recognitionTier: "anchor",
  },
  {
    name: "Samuel Huntington",
    slug: "samuel-huntington",
    domain: 'Political science / "Who Are We?"',
    corePosition: "Mass immigration from Latin America threatens American cultural identity — national cohesion requires cultural assimilation, not just legal status",
    recognitionTier: "anchor",
  },
  {
    name: "Hannah Arendt",
    slug: "hannah-arendt",
    domain: 'Political philosophy / "The Origins of Totalitarianism"',
    corePosition: "The refugee is the paradigmatic political figure of modernity — statelessness reveals the fiction that human rights exist without political membership",
    recognitionTier: "anchor",
  },
  {
    name: "Stephen Miller",
    slug: "stephen-miller",
    domain: "Policy / former White House advisor",
    corePosition: 'Immigration restriction as national security and cultural preservation — the policy architect of "America First" immigration enforcement',
    recognitionTier: "anchor",
  },
  {
    name: "Douglas Massey",
    slug: "douglas-massey",
    domain: "Sociology / Princeton",
    corePosition: "Decades of research showing that border enforcement doesn't reduce migration — it traps people inside who would otherwise circulate; the empirical demolition of enforcement logic",
    recognitionTier: "anchor",
  },
  {
    name: "David Frum",
    slug: "david-frum",
    domain: 'Journalism / "How Immigration Became So Controversial"',
    corePosition: "Liberal immigration policy erodes the social solidarity required for the welfare state — the center-right case for restriction with compassion",
    recognitionTier: "anchor",
  },
  {
    name: "Joseph Carens",
    slug: "joseph-carens",
    domain: 'Philosophy / "The Ethics of Immigration"',
    corePosition: "Borders are the modern equivalent of feudal privilege — birthplace determines life outcomes; justice requires open borders as the default",
    recognitionTier: "depth",
  },
  {
    name: "Michael Walzer",
    slug: "michael-walzer",
    domain: 'Philosophy / "Spheres of Justice"',
    corePosition: "Communities have the right to control membership — political self-determination includes deciding who joins; the communitarian case for borders",
    recognitionTier: "depth",
  },
  {
    name: "Ayelet Shachar",
    slug: "ayelet-shachar",
    domain: 'Law / "The Birthright Lottery"',
    corePosition: "Citizenship by birth is morally arbitrary — the most consequential distribution of life chances is also the least justified",
    recognitionTier: "depth",
  },
  {
    name: "Giovanni Peri",
    slug: "giovanni-peri",
    domain: "Economics / UC Davis",
    corePosition: "Immigration is complementary, not competitive — immigrants fill different roles than natives; the positive-sum economic case",
    recognitionTier: "depth",
  },
  {
    name: "Suketu Mehta",
    slug: "suketu-mehta",
    domain: 'Journalism / "This Land Is Our Land"',
    corePosition: "Colonialism created the conditions that drive migration — the Global North owes a debt to the people whose countries it extracted from",
    recognitionTier: "depth",
  },
  {
    name: "David Miller",
    slug: "david-miller",
    domain: 'Philosophy / "Strangers in Our Midst"',
    corePosition: "Nations have legitimate interests in controlling immigration — cultural preservation and democratic self-governance are not xenophobia",
    recognitionTier: "depth",
  },
  {
    name: "Mae Ngai",
    slug: "mae-ngai",
    domain: 'History / "Impossible Subjects"',
    corePosition: '"Illegal alien" is a legal category created in the 1920s — illegality is produced by law, not by people; the history of how immigration became criminal',
    recognitionTier: "depth",
  },
  {
    name: "Alex Nowrasteh",
    slug: "alex-nowrasteh",
    domain: "Economics / Cato Institute",
    corePosition: "Libertarian case for immigration — immigrants commit less crime, use fewer benefits, and create more economic value than natives; the data is clear",
    recognitionTier: "depth",
  },
  {
    name: "Sandro Mezzadra",
    slug: "sandro-mezzadra",
    domain: 'Political philosophy / "Border as Method"',
    corePosition: "Borders are not walls but processes — they filter, sort, and hierarchize movement; understanding borders means understanding global labor management",
    recognitionTier: "depth",
  },
  {
    name: "Leah Boustan",
    slug: "leah-boustan",
    domain: "Economics / Princeton",
    corePosition: "Historical data on immigrant assimilation — the children and grandchildren of immigrants converge with natives on every measurable outcome",
    recognitionTier: "depth",
  },
  {
    name: "Roberto Gonzales",
    slug: "roberto-gonzales",
    domain: 'Education / "Lives in Limbo"',
    corePosition: 'Growing up undocumented in America — the transition from "protected" childhood to "illegal" adulthood; the psychological reality of liminal status',
    recognitionTier: "depth",
  },
  {
    name: "Paul Collier",
    slug: "paul-collier",
    domain: 'Economics / "Exodus"',
    corePosition: "Moderate immigration benefits both sides; large-scale migration threatens social cohesion in receiving countries and brain-drains sending countries — the moderate restrictionist",
    recognitionTier: "depth",
  },
  {
    name: "Reece Jones",
    slug: "reece-jones",
    domain: 'Geography / "White Borders"',
    corePosition: "Border enforcement is violence — walls, detention, and deportation are instruments of racial control dressed in bureaucratic language",
    recognitionTier: "depth",
  },
  {
    name: "Viet Thanh Nguyen",
    slug: "viet-thanh-nguyen",
    domain: 'Literature / "The Sympathizer"',
    corePosition: "The refugee is not a problem to be solved but a person with agency — the literature of displacement as political testimony",
    recognitionTier: "depth",
  },
  {
    name: "Roger Daniels",
    slug: "roger-daniels",
    domain: "History / immigration history",
    corePosition: "The long history of American nativism — every wave of immigrants faced the same arguments; the cyclical nature of anti-immigrant politics",
    recognitionTier: "depth",
  },
  {
    name: "Bridget Anderson",
    slug: "bridget-anderson",
    domain: 'Migration studies / "Us and Them?"',
    corePosition: 'Immigration enforcement constructs the category of "good citizen" by defining who is excludable — borders produce national identity, not the other way around',
    recognitionTier: "surprise",
  },
  {
    name: "Hein de Haas",
    slug: "hein-de-haas",
    domain: 'Migration studies / "How Migration Really Works"',
    corePosition: "Most migration assumptions are wrong — enforcement doesn't deter, development increases migration, and circular migration was the historical norm",
    recognitionTier: "surprise",
  },
  {
    name: "Hiroshi Motomura",
    slug: "hiroshi-motomura",
    domain: 'Law / "Americans in Waiting"',
    corePosition: "U.S. immigration law has always contained a tension between selection (who we want) and affiliation (who is already here and connected) — both are legitimate",
    recognitionTier: "surprise",
  },
  {
    name: "Harsha Walia",
    slug: "harsha-walia",
    domain: 'Activism / "Border and Rule"',
    corePosition: "Borders are instruments of racial capitalism — they manage global labor pools for the benefit of capital; abolishing borders means abolishing the system that requires them",
    recognitionTier: "surprise",
  },
  {
    name: "Jaya Ramji-Nogales",
    slug: "jaya-ramji-nogales",
    domain: 'Law / "Refugee Roulette"',
    corePosition: "Asylum outcomes depend more on which judge you get than on your case — the procedural justice crisis in immigration courts",
    recognitionTier: "surprise",
  },
  {
    name: "Philippe Legrain",
    slug: "philippe-legrain",
    domain: 'Economics / "Immigrants: Your Country Needs Them"',
    corePosition: "The economic case for immigration is overwhelming across every study and every country — restriction is an economically irrational policy driven by cultural anxiety",
    recognitionTier: "surprise",
  },
  {
    name: "Tara Zahra",
    slug: "tara-zahra",
    domain: 'History / "The Great Departure"',
    corePosition: 'Before the 20th century, states tried to prevent people from LEAVING — immigration restriction is historically recent and the "natural order" argument is ahistorical',
    recognitionTier: "surprise",
  },
];
