import { PoolThinker } from "./types";

export const longevityPool: PoolThinker[] = [
  {
    name: "Aubrey de Grey",
    slug: "aubrey-de-grey",
    domain: "Biogerontology / SENS",
    corePosition: 'Aging is an engineering problem with identifiable damage types; "longevity escape velocity" is achievable within decades if we fund the research',
    recognitionTier: "anchor",
  },
  {
    name: "Ray Kurzweil",
    slug: "ray-kurzweil",
    domain: 'Futurism / "The Singularity Is Near"',
    corePosition: "Exponential technological progress will merge biology and computing — death is a solvable problem on a specific timeline",
    recognitionTier: "anchor",
  },
  {
    name: "Peter Attia",
    slug: "peter-attia",
    domain: 'Longevity medicine / "Outlive"',
    corePosition: "Lifespan without healthspan is meaningless — the clinical practice of extending healthy years through exercise, metabolic health, and early intervention",
    recognitionTier: "anchor",
  },
  {
    name: "David Sinclair",
    slug: "david-sinclair",
    domain: "Genetics / Harvard",
    corePosition: "Aging is a disease with a cause (epigenetic information loss) and a cure; reprogramming biology is not science fiction but active research",
    recognitionTier: "anchor",
  },
  {
    name: "Francis Fukuyama",
    slug: "francis-fukuyama",
    domain: 'Political philosophy / "Our Posthuman Future"',
    corePosition: "Biotechnology threatens the concept of human nature that grounds liberal democracy — enhancement without limits erodes the moral equality of persons",
    recognitionTier: "anchor",
  },
  {
    name: "Ezekiel Emanuel",
    slug: "ezekiel-emanuel",
    domain: 'Bioethics / health policy',
    corePosition: '"Why I Hope to Die at 75" — the pursuit of longevity past a certain point diminishes life rather than extending it; a good death has a natural time',
    recognitionTier: "anchor",
  },
  {
    name: "Nick Bostrom",
    slug: "nick-bostrom",
    domain: "Philosophy / transhumanism",
    corePosition: 'The "fable of the dragon" — death is history\'s greatest catastrophe and opposing it is the most important moral project; aging is the dragon we must slay',
    recognitionTier: "anchor",
  },
  {
    name: "Bryan Johnson",
    slug: "bryan-johnson",
    domain: 'Biohacking / "Don\'t Die"',
    corePosition: "The human body as an optimization system — total measurement, algorithmic decision-making, and radical self-experimentation as proof of concept",
    recognitionTier: "depth",
  },
  {
    name: "Cynthia Kenyon",
    slug: "cynthia-kenyon",
    domain: "Genetics / Calico",
    corePosition: "Discovered that single gene mutations can double lifespan in organisms — aging has genetic regulators that can be manipulated",
    recognitionTier: "depth",
  },
  {
    name: "Leonard Hayflick",
    slug: "leonard-hayflick",
    domain: "Cell biology",
    corePosition: "Discovered the Hayflick limit — cells have a fixed division capacity; aging is not a disease but a fundamental biological process",
    recognitionTier: "depth",
  },
  {
    name: "Laura Deming",
    slug: "laura-deming",
    domain: "Longevity VC / Longevity Fund",
    corePosition: "The investment thesis for longevity — which interventions have the most evidence, which companies are serious, and where capital should flow",
    recognitionTier: "depth",
  },
  {
    name: "Nir Barzilai",
    slug: "nir-barzilai",
    domain: "Geroscience / Albert Einstein College",
    corePosition: "Studies centenarians to identify protective genetics; TAME trial — testing metformin as the first FDA-approved anti-aging drug",
    recognitionTier: "depth",
  },
  {
    name: "Venki Ramakrishnan",
    slug: "venki-ramakrishnan",
    domain: 'Molecular biology / Nobel laureate',
    corePosition: '"Why We Die" — a working scientist\'s sober assessment of what longevity research can and cannot deliver; separating hype from evidence',
    recognitionTier: "depth",
  },
  {
    name: "S. Jay Olshansky",
    slug: "s-jay-olshansky",
    domain: 'Demography / "The Quest for Immortality"',
    corePosition: "Life expectancy gains are decelerating; the low-hanging fruit is gone; radical extension requires fundamentally different biology, not better medicine",
    recognitionTier: "depth",
  },
  {
    name: "João Pedro de Magalhães",
    slug: "joao-pedro-de-magalhaes",
    domain: "Biogerontology / genomics",
    corePosition: "Comparative biology of aging — why do some species barely age? The genetic toolkit for longevity already exists in nature",
    recognitionTier: "depth",
  },
  {
    name: "Caleb Finch",
    slug: "caleb-finch",
    domain: "Gerontology / USC",
    corePosition: "Inflammation and environment drive aging more than genetics in most people — the environmental determination of lifespan",
    recognitionTier: "depth",
  },
  {
    name: "Michael Rose",
    slug: "michael-rose",
    domain: "Evolutionary biology",
    corePosition: "Aging evolved because natural selection weakens after reproduction; evolution-based interventions are more promising than molecular repair",
    recognitionTier: "depth",
  },
  {
    name: "Bernard Williams",
    slug: "bernard-williams",
    domain: 'Philosophy / "The Makropulos Case"',
    corePosition: "Immortality would be unbearable — identity requires finitude; eternal life isn't extended meaning but extended tedium",
    recognitionTier: "depth",
  },
  {
    name: "Martha Nussbaum",
    slug: "martha-nussbaum",
    domain: "Philosophy / capabilities",
    corePosition: "Human flourishing requires vulnerability and mortality — the capabilities approach to what makes a life worth living depends on limits",
    recognitionTier: "depth",
  },
  {
    name: "Daniel Callahan",
    slug: "daniel-callahan",
    domain: "Bioethics / Hastings Center",
    corePosition: 'A "natural lifespan" exists and society has no obligation to extend it indefinitely — intergenerational justice requires accepting mortality',
    recognitionTier: "depth",
  },
  {
    name: "John Harris",
    slug: "john-harris",
    domain: 'Bioethics / "Enhancing Evolution"',
    corePosition: "If we can extend healthy life, we are morally obligated to do so — the case for enhancement as a positive duty",
    recognitionTier: "depth",
  },
  {
    name: "Shinya Yamanaka",
    slug: "shinya-yamanaka",
    domain: "Stem cell biology / Nobel laureate",
    corePosition: "Discovered cellular reprogramming factors — proved that aging can be reversed at the cellular level; the empirical foundation for rejuvenation",
    recognitionTier: "depth",
  },
  {
    name: "Elizabeth Blackburn",
    slug: "elizabeth-blackburn",
    domain: 'Molecular biology / telomeres',
    corePosition: 'Nobel Prize for telomerase discovery; "The Telomere Effect" — stress, lifestyle, and social conditions age cells at different rates',
    recognitionTier: "depth",
  },
  {
    name: "Eric Topol",
    slug: "eric-topol",
    domain: 'Digital medicine / "Deep Medicine"',
    corePosition: "AI will transform longevity through personalized prevention — the convergence of data, genomics, and clinical practice",
    recognitionTier: "depth",
  },
  {
    name: "Valter Longo",
    slug: "valter-longo",
    domain: "Biogerontology / fasting",
    corePosition: "Fasting-mimicking diets activate longevity pathways; dietary intervention is the most accessible and evidence-backed lifespan tool available now",
    recognitionTier: "depth",
  },
  {
    name: "Andrew Steele",
    slug: "andrew-steele",
    domain: 'Computational biology / "Ageless"',
    corePosition: "Aging is the leading cause of death and suffering — not treating it is the radical position; the case for longevity as mainstream medicine",
    recognitionTier: "depth",
  },
  {
    name: "Atul Gawande",
    slug: "atul-gawande",
    domain: 'Surgery / "Being Mortal"',
    corePosition: "Medicine's failure is not that people die but that they die badly — the quality of the ending matters more than its postponement",
    recognitionTier: "depth",
  },
  {
    name: "Jan Vijg",
    slug: "jan-vijg",
    domain: "Genetics / Albert Einstein College",
    corePosition: "Argues there is a hard ceiling on human lifespan (~115-120 years) imposed by mutation accumulation — radical extension may be biologically impossible",
    recognitionTier: "surprise",
  },
  {
    name: "Marios Kyriazis",
    slug: "marios-kyriazis",
    domain: "Gerontology / radical life extension",
    corePosition: "Extreme longevity requires not just biological repair but cognitive enhancement — the brain is the binding constraint, not the body",
    recognitionTier: "surprise",
  },
  {
    name: "Colin Farrelly",
    slug: "colin-farrelly",
    domain: "Political philosophy",
    corePosition: "Longevity science is the most important justice issue of the century — a \"duty to retard aging\" that overrides other health priorities",
    recognitionTier: "surprise",
  },
  {
    name: "Ilya Stambler",
    slug: "ilya-stambler",
    domain: "History of life extension",
    corePosition: "Documents 2,000 years of longevity pursuit — separating what's new from what's ancient in the current moment",
    recognitionTier: "surprise",
  },
  {
    name: "Vadim Gladyshev",
    slug: "vadim-gladyshev",
    domain: "Systems biology / Harvard",
    corePosition: "Developed biological age clocks; quantifying aging at the molecular level — the measurement infrastructure that makes intervention possible",
    recognitionTier: "surprise",
  },
  {
    name: "Eos Chater",
    slug: "eos-chater",
    domain: "Ethics of aging / intergenerational justice",
    corePosition: "Life extension without resource redistribution is intergenerational theft — older generations holding wealth and power indefinitely while younger ones wait",
    recognitionTier: "surprise",
  },
  {
    name: "Shin-ichiro Imai",
    slug: "shin-ichiro-imai",
    domain: "Biogerontology / NAD+ metabolism",
    corePosition: "The biochemistry of how cells lose function with age — NAD+ decline as a unifying mechanism; the Japanese contribution to molecular geroscience",
    recognitionTier: "surprise",
  },
];
