import { PoolThinker } from "./types";

export const meaningCrisisPool: PoolThinker[] = [
  {
    name: "Viktor Frankl",
    slug: "viktor-frankl",
    domain: 'Psychiatry / "Man\'s Search for Meaning"',
    corePosition: "Meaning is found through suffering, love, and purpose — even in extremity, the choice of attitude remains; logotherapy as existential practice",
    recognitionTier: "anchor",
  },
  {
    name: "Friedrich Nietzsche",
    slug: "friedrich-nietzsche",
    domain: "Philosophy",
    corePosition: '"God is dead" — not a celebration but a warning; without transcendent foundations, nihilism is the default unless we actively create values',
    recognitionTier: "anchor",
  },
  {
    name: "Jordan Peterson",
    slug: "jordan-peterson",
    domain: 'Psychology / "Maps of Meaning"',
    corePosition: "Mythological structures encode evolved wisdom about meaning; responsibility and voluntary suffering are the antidote to nihilism",
    recognitionTier: "anchor",
  },
  {
    name: "Simone de Beauvoir",
    slug: "simone-de-beauvoir",
    domain: "Philosophy / existentialism",
    corePosition: "Freedom is the ground of meaning, but freedom without commitment is empty — meaning is made through chosen projects and solidarity",
    recognitionTier: "anchor",
  },
  {
    name: "Albert Camus",
    slug: "albert-camus",
    domain: "Philosophy / absurdism",
    corePosition: "Life is absurd AND worth living — the honest response to meaninglessness is neither denial nor despair but revolt, creation, and solidarity",
    recognitionTier: "anchor",
  },
  {
    name: "Fyodor Dostoevsky",
    slug: "fyodor-dostoevsky",
    domain: "Literature / philosophy",
    corePosition: '"If God does not exist, everything is permitted" — explored the psychological consequences of belief\'s collapse before it happened culturally',
    recognitionTier: "anchor",
  },
  {
    name: "Søren Kierkegaard",
    slug: "soren-kierkegaard",
    domain: "Philosophy / theology",
    corePosition: 'The "leap of faith" — rational argument cannot get you to meaning; commitment precedes understanding; the aesthetic life leads to despair',
    recognitionTier: "anchor",
  },
  {
    name: "Thich Nhat Hanh",
    slug: "thich-nhat-hanh",
    domain: "Buddhism / mindfulness",
    corePosition: "Meaning is not found in the future but in present-moment awareness — interbeing; the illusion of separate self is the root of suffering",
    recognitionTier: "anchor",
  },
  {
    name: "Byung-Chul Han",
    slug: "byung-chul-han",
    domain: 'Philosophy / "The Burnout Society"',
    corePosition: "Neoliberal self-exploitation has replaced external oppression — we exhaust ourselves voluntarily; meaninglessness is the achievement society's product",
    recognitionTier: "depth",
  },
  {
    name: "John Vervaeke",
    slug: "john-vervaeke",
    domain: 'Cognitive science / "Awakening from the Meaning Crisis"',
    corePosition: "The meaning crisis is cognitive, not just cultural — attention, relevance, and participatory knowing have been systematically undermined by modernity",
    recognitionTier: "depth",
  },
  {
    name: "Charles Taylor",
    slug: "charles-taylor",
    domain: 'Philosophy / "A Secular Age"',
    corePosition: 'Secularization didn\'t just remove God — it transformed the entire "conditions of belief"; we live in a world where faith is one option among many, and that changes everything',
    recognitionTier: "depth",
  },
  {
    name: "Iain McGilchrist",
    slug: "iain-mcgilchrist",
    domain: 'Psychiatry / "The Master and His Emissary"',
    corePosition: "Left-hemisphere dominance in Western culture produces fragmentation, abstraction, and loss of meaning — the crisis is neurological as much as philosophical",
    recognitionTier: "depth",
  },
  {
    name: "Robert Bellah",
    slug: "robert-bellah",
    domain: 'Sociology / "Habits of the Heart"',
    corePosition: "American individualism has eroded the communal practices that generate meaning — expressive individualism is the cultural logic of loneliness",
    recognitionTier: "depth",
  },
  {
    name: "Zygmunt Bauman",
    slug: "zygmunt-bauman",
    domain: 'Sociology / "Liquid Modernity"',
    corePosition: "Institutions no longer provide stable frameworks for identity — everything is temporary, disposable, and fluid; meaning requires solidity that modernity dissolves",
    recognitionTier: "depth",
  },
  {
    name: "Alasdair MacIntyre",
    slug: "alasdair-macintyre",
    domain: 'Philosophy / "After Virtue"',
    corePosition: "The Enlightenment destroyed the moral framework it inherited without replacing it — we're living in the ruins of a tradition we can't rebuild and can't escape",
    recognitionTier: "depth",
  },
  {
    name: "Jonathan Haidt",
    slug: "jonathan-haidt",
    domain: 'Social psychology / "The Righteous Mind"',
    corePosition: "Moral foundations are innate and plural — meaning comes from belonging to moral communities; liberal individualism systematically undermines three of six foundations",
    recognitionTier: "depth",
  },
  {
    name: "Emile Durkheim",
    slug: "emile-durkheim",
    domain: "Sociology",
    corePosition: '"Anomie" — when social bonds weaken and norms dissolve, suicide and purposelessness rise; meaning is structurally produced by collective life',
    recognitionTier: "depth",
  },
  {
    name: "Hannah Arendt",
    slug: "hannah-arendt",
    domain: "Political philosophy",
    corePosition: "Meaning emerges through action in public — the private, contemplative life is not enough; political participation is constitutive of human flourishing",
    recognitionTier: "depth",
  },
  {
    name: "Martin Buber",
    slug: "martin-buber",
    domain: "Philosophy / theology",
    corePosition: '"I-Thou" — meaning lives in genuine encounter with the other; modern life reduces everything to "I-It" relations of use and manipulation',
    recognitionTier: "depth",
  },
  {
    name: "Iris Murdoch",
    slug: "iris-murdoch",
    domain: "Philosophy / fiction",
    corePosition: "Moral progress is attention — really seeing the other person; meaning comes not from will but from the patient, ego-dissolving work of perception",
    recognitionTier: "depth",
  },
  {
    name: "Robert Putnam",
    slug: "robert-putnam",
    domain: 'Political science / "Bowling Alone"',
    corePosition: "Social capital has collapsed — the empirical documentation of community dissolution; without civic participation, meaning atrophies",
    recognitionTier: "depth",
  },
  {
    name: "Gabor Maté",
    slug: "gabor-mate",
    domain: "Addiction medicine / trauma",
    corePosition: "Addiction is not about the substance but about pain — the meaning crisis manifests as compulsive escape from disconnection and unprocessed trauma",
    recognitionTier: "depth",
  },
  {
    name: "Rollo May",
    slug: "rollo-may",
    domain: "Existential psychology",
    corePosition: "Anxiety is not pathology but the inevitable companion of freedom — meaning requires confronting rather than medicating existential dread",
    recognitionTier: "depth",
  },
  {
    name: "James Carse",
    slug: "james-carse",
    domain: 'Philosophy / "Finite and Infinite Games"',
    corePosition: "Finite games are played to win; infinite games are played to continue playing — meaning lives in infinite games; institutions mistake the finite for the real",
    recognitionTier: "depth",
  },
  {
    name: "Marilynne Robinson",
    slug: "marilynne-robinson",
    domain: "Fiction / theology",
    corePosition: "Grace, attention, and ordinary life contain inexhaustible depth — meaning doesn't require grand narrative, only genuine perception of what's already present",
    recognitionTier: "depth",
  },
  {
    name: "Alain de Botton",
    slug: "alain-de-botton",
    domain: "Philosophy / School of Life",
    corePosition: "Philosophy and art can fill the structural role that religion once played — secular rituals, community, and consolation without faith",
    recognitionTier: "depth",
  },
  {
    name: "Abdal Hakim Murad",
    slug: "abdal-hakim-murad",
    domain: "Islamic theology / Cambridge",
    corePosition: "The Islamic tradition offers a living alternative to secular nihilism — meaning through submission, community, and sacred cosmology that modernity has not yet dissolved",
    recognitionTier: "depth",
  },
  {
    name: "Bonnitta Roy",
    slug: "bonnitta-roy",
    domain: "Process philosophy / metamodernism",
    corePosition: 'Meaning-making itself needs to be understood as a developmental process — the "source code" of how minds construct relevance and purpose',
    recognitionTier: "surprise",
  },
  {
    name: "Hartmut Rosa",
    slug: "hartmut-rosa",
    domain: 'Sociology / "Resonance"',
    corePosition: 'The crisis isn\'t meaninglessness but "alienation" — inability to be affected by the world; resonance (responsive relationship with world) is the alternative to acceleration',
    recognitionTier: "surprise",
  },
  {
    name: "Bayo Akomolafe",
    slug: "bayo-akomolafe",
    domain: "Philosophy / post-activism",
    corePosition: 'The Western meaning crisis is a specifically Western problem — indigenous and non-modern ontologies never separated meaning from world; the "crisis" is the tradition seeing its own limits',
    recognitionTier: "surprise",
  },
  {
    name: "Tomáš Halík",
    slug: "tomas-halik",
    domain: "Theology / Czech Republic",
    corePosition: 'Doubt is not the enemy of faith but its companion — "patient faith" that holds uncertainty without collapsing into either certainty or nihilism',
    recognitionTier: "surprise",
  },
  {
    name: "L.A. Paul",
    slug: "la-paul",
    domain: "Philosophy / transformative experience",
    corePosition: "Some meaningful choices cannot be evaluated in advance — becoming a parent, converting, starting over — because they transform the very self that would evaluate them",
    recognitionTier: "surprise",
  },
  {
    name: "Zak Stein",
    slug: "zak-stein",
    domain: "Education / developmental psychology",
    corePosition: "The meaning crisis is a crisis of human development — educational systems that fail to support psychological growth produce adults incapable of meaning-making",
    recognitionTier: "surprise",
  },
  {
    name: "Tu Weiming",
    slug: "tu-weiming",
    domain: "Confucian philosophy / Harvard",
    corePosition: "Confucian humanism offers meaning through cultivated relationships, ritual, and self-cultivation — neither theistic nor nihilistic; a \"third way\" between religion and secularism",
    recognitionTier: "surprise",
  },
];
