import { PoolThinker } from "./types";

export const nuclearDeterrencePool: PoolThinker[] = [
  {
    name: "J. Robert Oppenheimer",
    slug: "j-robert-oppenheimer",
    domain: "Physics / Manhattan Project",
    corePosition: '"Now I am become death" — the scientist who built the bomb and spent the rest of his life trying to contain what he created',
    recognitionTier: "anchor",
  },
  {
    name: "Henry Kissinger",
    slug: "henry-kissinger",
    domain: "Diplomacy / arms control",
    corePosition: "Architect of détente and SALT treaties — nuclear weapons require managed competition between great powers; abolition is fantasy",
    recognitionTier: "anchor",
  },
  {
    name: "Daniel Ellsberg",
    slug: "daniel-ellsberg",
    domain: 'Whistleblowing / "The Doomsday Machine"',
    corePosition: "The nuclear war plans are far more insane than the public knows — first-use doctrines, delegation authority, and automated escalation make accidental annihilation likely",
    recognitionTier: "anchor",
  },
  {
    name: "Herman Kahn",
    slug: "herman-kahn",
    domain: 'Strategy / "On Thermonuclear War"',
    corePosition: "Nuclear war is thinkable and survivable — strategic planning requires confronting the unthinkable; escalation dominance as deterrence theory",
    recognitionTier: "anchor",
  },
  {
    name: "Kenneth Waltz",
    slug: "kenneth-waltz",
    domain: 'Political science / "The Spread of Nuclear Weapons"',
    corePosition: "Nuclear proliferation promotes peace — more nuclear states means more deterrence; the counterintuitive case for the bomb",
    recognitionTier: "anchor",
  },
  {
    name: "Beatrice Fihn",
    slug: "beatrice-fihn",
    domain: "ICAN / Nobel Peace Prize",
    corePosition: "Led the campaign for the UN Treaty on the Prohibition of Nuclear Weapons — abolition is not idealism but the only rational response to an irrational weapon",
    recognitionTier: "anchor",
  },
  {
    name: "Thomas Schelling",
    slug: "thomas-schelling",
    domain: 'Economics / "The Strategy of Conflict"',
    corePosition: 'Deterrence is a game of credible commitment — the "threat that leaves something to chance"; nuclear strategy as bargaining theory',
    recognitionTier: "anchor",
  },
  {
    name: "William Perry",
    slug: "william-perry",
    domain: "Defense / former Secretary of Defense",
    corePosition: '"My Journey at the Nuclear Brink" — spent a career inside the system and concluded we\'ve been lucky, not safe; the insider\'s case for deep cuts',
    recognitionTier: "depth",
  },
  {
    name: "Scott Sagan",
    slug: "scott-sagan",
    domain: 'Political science / "The Limits of Safety"',
    corePosition: "Nuclear accidents and near-misses are far more common than acknowledged — organizational theory shows that complex systems produce inevitable failures",
    recognitionTier: "depth",
  },
  {
    name: "Nina Tannenwald",
    slug: "nina-tannenwald",
    domain: 'Political science / "The Nuclear Taboo"',
    corePosition: 'A norm against nuclear use has developed since 1945 — the "nuclear taboo" is real, fragile, and the most important constraint on use',
    recognitionTier: "depth",
  },
  {
    name: "Keir Lieber & Daryl Press",
    slug: "keir-lieber-daryl-press",
    domain: 'Political science / "The Myth of the Nuclear Revolution"',
    corePosition: "Nuclear superiority matters — first-strike capability is achievable and states pursue it; the revolution in accuracy changes everything about deterrence",
    recognitionTier: "depth",
  },
  {
    name: "Bruno Tertrais",
    slug: "bruno-tertrais",
    domain: "Strategy / French nuclear policy",
    corePosition: "European nuclear perspectives — France's independent deterrent represents a different philosophy: national sovereignty requires national weapons",
    recognitionTier: "depth",
  },
  {
    name: "James Acton",
    slug: "james-acton",
    domain: "Nuclear policy / Carnegie",
    corePosition: "Entanglement — conventional and nuclear forces are increasingly intertwined; a conventional war could escalate to nuclear through attacks on dual-use systems",
    recognitionTier: "depth",
  },
  {
    name: "Ward Wilson",
    slug: "ward-wilson",
    domain: 'History / "Five Myths About Nuclear Weapons"',
    corePosition: "Hiroshima didn't end WWII — Soviet entry did; nuclear weapons are less useful than assumed; the foundational narrative of deterrence is historically wrong",
    recognitionTier: "depth",
  },
  {
    name: "Andrew Futter",
    slug: "andrew-futter",
    domain: "International relations / nuclear cyber",
    corePosition: "Cyber threats to nuclear command and control — what happens when hackers can spoof launch warnings or disable safety systems",
    recognitionTier: "depth",
  },
  {
    name: "Nikolai Sokov",
    slug: "nikolai-sokov",
    domain: "Russian nuclear doctrine / arms control",
    corePosition: 'Russian nuclear thinking from inside — "escalate to de-escalate" doctrine; what Moscow actually believes about when and how to use nuclear weapons',
    recognitionTier: "depth",
  },
  {
    name: "Vipin Narang",
    slug: "vipin-narang",
    domain: "Political science / MIT",
    corePosition: "Regional nuclear postures — India, Pakistan, Israel, North Korea each developed different nuclear doctrines; one-size deterrence theory doesn't fit",
    recognitionTier: "depth",
  },
  {
    name: "Eric Schlosser",
    slug: "eric-schlosser",
    domain: 'Journalism / "Command and Control"',
    corePosition: "The history of nuclear weapons accidents — broken arrows, false alarms, and near-launches; the empirical record of how close we've come",
    recognitionTier: "depth",
  },
  {
    name: "Toby Ord",
    slug: "toby-ord",
    domain: 'Philosophy / "The Precipice"',
    corePosition: "Nuclear war remains among the top existential risks — assigns roughly 1% probability of nuclear catastrophe per century; existential risk framework applied",
    recognitionTier: "depth",
  },
  {
    name: "Rebecca Hersman",
    slug: "rebecca-hersman",
    domain: "Defense / CSIS",
    corePosition: "Nuclear decision-making under pressure — the time constraints, information failures, and cognitive biases that make crisis management terrifying",
    recognitionTier: "depth",
  },
  {
    name: "George Perkovich",
    slug: "george-perkovich",
    domain: "Nuclear policy / Carnegie",
    corePosition: "Nonproliferation architecture — the NPT bargain is eroding; what happens when the regime that prevented 30+ nuclear states collapses",
    recognitionTier: "depth",
  },
  {
    name: "Jeffrey Lewis",
    slug: "jeffrey-lewis",
    domain: 'Arms control / "The 2020 Commission"',
    corePosition: "Wrote fiction about nuclear war to convey what analysis can't — the gap between strategic abstraction and human experience of nuclear use",
    recognitionTier: "depth",
  },
  {
    name: "Benoît Pelopidas",
    slug: "benoit-pelopidas",
    domain: "Nuclear studies / Sciences Po",
    corePosition: "The role of luck in nuclear history — we systematically undercount near-misses; vulnerability, not control, is the honest assessment",
    recognitionTier: "surprise",
  },
  {
    name: "Zia Mian",
    slug: "zia-mian",
    domain: "Nuclear physics / Princeton",
    corePosition: "Pakistani-American physicist working on disarmament — South Asian nuclear dynamics and the specific risks of the India-Pakistan dyad",
    recognitionTier: "surprise",
  },
  {
    name: "Lynn Eden",
    slug: "lynn-eden",
    domain: 'Stanford / "Whole World on Fire"',
    corePosition: "U.S. nuclear war planning systematically ignores fire effects — damage estimates are undercounted by orders of magnitude; the institutional blindness",
    recognitionTier: "surprise",
  },
  {
    name: "Setsuko Thurlow",
    slug: "setsuko-thurlow",
    domain: "Hibakusha / ICAN",
    corePosition: "Hiroshima survivor and Nobel laureate — the only people who truly understand what nuclear weapons do are those who survived them; moral witness",
    recognitionTier: "surprise",
  },
  {
    name: "Pavel Podvig",
    slug: "pavel-podvig",
    domain: "Russian nuclear forces / researcher",
    corePosition: "The most detailed public tracking of Russian nuclear capabilities and doctrine — what Russia actually has, as opposed to what it claims",
    recognitionTier: "surprise",
  },
  {
    name: "Caitlin Talmadge",
    slug: "caitlin-talmadge",
    domain: "Political science / Georgetown",
    corePosition: "Conventional war scenarios that escalate to nuclear — specifically how a U.S.-China conflict could cross the nuclear threshold through attacks on Chinese nuclear forces",
    recognitionTier: "surprise",
  },
];
