import { PoolThinker } from "./types";

export const reparationsPool: PoolThinker[] = [
  {
    name: "Ta-Nehisi Coates",
    slug: "ta-nehisi-coates",
    domain: 'Journalism / "The Case for Reparations"',
    corePosition: "The 2014 Atlantic article that reignited the national debate — reparations are not about slavery alone but about the ongoing system of plunder from redlining to predatory lending",
    recognitionTier: "anchor",
  },
  {
    name: "William Darity Jr.",
    slug: "william-darity-jr",
    domain: 'Economics / "From Here to Equality"',
    corePosition: "The most rigorous economic framework for reparations — calculated the wealth gap, specified the form (direct payments to descendants), and designed implementation",
    recognitionTier: "anchor",
  },
  {
    name: "John McWhorter",
    slug: "john-mcwhorter",
    domain: "Linguistics / cultural commentary",
    corePosition: "Reparations are impractical and counterproductive — they encourage victimhood, face impossible implementation questions, and won't close racial gaps",
    recognitionTier: "anchor",
  },
  {
    name: "Coleman Hughes",
    slug: "coleman-hughes",
    domain: 'Philosophy / "The End of Race Politics"',
    corePosition: "Reparations based on race violate the principle of individual responsibility — the progressive case against racial restitution; class-based policy instead",
    recognitionTier: "anchor",
  },
  {
    name: "Angela Davis",
    slug: "angela-davis",
    domain: "Political philosophy / abolition",
    corePosition: "Reparations must be structural, not individual checks — abolishing the prison-industrial complex, transforming education, and redistributing land",
    recognitionTier: "anchor",
  },
  {
    name: "Nikole Hannah-Jones",
    slug: "nikole-hannah-jones",
    domain: "Journalism / 1619 Project",
    corePosition: "American wealth was built on enslaved labor — reparations are not charity but repayment of what was stolen; the historical claim as moral demand",
    recognitionTier: "anchor",
  },
  {
    name: "Desmond Tutu",
    slug: "desmond-tutu",
    domain: "Theology / Truth and Reconciliation Commission",
    corePosition: "South Africa's TRC as a model — truth-telling, forgiveness, and restorative justice as alternatives to both punishment and forgetting",
    recognitionTier: "anchor",
  },
  {
    name: "Bryan Stevenson",
    slug: "bryan-stevenson",
    domain: 'Law / "Just Mercy"',
    corePosition: "America has never seriously reckoned with slavery and racism — truth and acknowledgment must precede any material reparation; memory as justice",
    recognitionTier: "anchor",
  },
  {
    name: "Randall Robinson",
    slug: "randall-robinson",
    domain: 'Law / "The Debt"',
    corePosition: "The foundational book-length case for Black reparations — 246 years of slavery plus 100 years of Jim Crow created a debt that cannot be forgiven by time",
    recognitionTier: "depth",
  },
  {
    name: "Keeanga-Yamahtta Taylor",
    slug: "keeanga-yamahtta-taylor",
    domain: 'African American studies / "Race for Profit"',
    corePosition: "Federal housing policy was the mechanism of racial wealth extraction — from redlining to subprime; the state built the gap, the state must close it",
    recognitionTier: "depth",
  },
  {
    name: "Charles Ogletree",
    slug: "charles-ogletree",
    domain: "Law / Harvard",
    corePosition: "The legal strategy for reparations — identifying defendants, plaintiffs, and remedies; litigation as a path when legislation fails",
    recognitionTier: "depth",
  },
  {
    name: "Olúfẹ́mi Táíwò",
    slug: "olufemi-taiwo",
    domain: 'Philosophy / "Reconsidering Reparations"',
    corePosition: "Reparations as worldmaking — not backward-looking compensation but forward-looking construction of a just world; the constructive turn",
    recognitionTier: "depth",
  },
  {
    name: "Robin D.G. Kelley",
    slug: "robin-dg-kelley",
    domain: 'History / "Freedom Dreams"',
    corePosition: "Reparations must fund Black self-determination — not integration into existing structures but resources for building alternative institutions",
    recognitionTier: "depth",
  },
  {
    name: "Katherine Franke",
    slug: "katherine-franke",
    domain: 'Law / "Repair"',
    corePosition: "What happened after emancipation — the failure to redistribute land (40 acres) is the original reparations betrayal; Reconstruction as template and warning",
    recognitionTier: "depth",
  },
  {
    name: "Thomas Craemer",
    slug: "thomas-craemer",
    domain: "Political science / UConn",
    corePosition: "Estimated reparations at $14-17 trillion based on hours of slave labor at market wages — the economic calculation that makes the scale visible",
    recognitionTier: "depth",
  },
  {
    name: "Glen Loury",
    slug: "glen-loury",
    domain: "Economics / Brown",
    corePosition: "Racial inequality is real but reparations are the wrong instrument — community development, educational investment, and economic opportunity work; racial spoils don't",
    recognitionTier: "depth",
  },
  {
    name: "Daryl Michael Scott",
    slug: "daryl-michael-scott",
    domain: "History / Howard",
    corePosition: "The intellectual history of reparations movements — from post-Civil War through Callie House to the present; the long tradition that preceded Coates",
    recognitionTier: "depth",
  },
  {
    name: "Roy Brooks",
    slug: "roy-brooks",
    domain: 'Law / "Atonement and Forgiveness"',
    corePosition: 'The "atonement model" — reparations require genuine apology and acknowledgment of wrongdoing, not just payment; the moral dimension is primary',
    recognitionTier: "depth",
  },
  {
    name: "Ana Lucia Araujo",
    slug: "ana-lucia-araujo",
    domain: 'History / "Reparations for Slavery and the Slave Trade"',
    corePosition: "Global comparative framework — what reparations have looked like in different contexts: Germany to Israel, Japanese internment, Caribbean CARICOM demands",
    recognitionTier: "depth",
  },
  {
    name: "Robert Westley",
    slug: "robert-westley",
    domain: 'Law / "Many Billions Gone"',
    corePosition: "The legal architecture for group-based reparations — trust fund model, community investment, institutional building rather than individual checks",
    recognitionTier: "depth",
  },
  {
    name: "Nick Draper",
    slug: "nick-draper",
    domain: "History / UCL Legacies of Slavery",
    corePosition: "Documented that British slave-owners received £20 million in compensation at abolition (taxpayers finished paying this off in 2015) — the reparations that DID happen went to the wrong people",
    recognitionTier: "depth",
  },
  {
    name: "Thomas Sowell",
    slug: "thomas-sowell",
    domain: "Economics / political philosophy",
    corePosition: "Group-based reparations fail on every dimension — no clear beneficiaries, no clear payers, perverse incentives, and international evidence shows they entrench division",
    recognitionTier: "depth",
  },
  {
    name: "Adolph Reed Jr.",
    slug: "adolph-reed-jr",
    domain: "Political science / left critique",
    corePosition: "The left-wing case against race-based reparations — class solidarity over racial identity; reparations are a neoliberal distraction from universal economic programs",
    recognitionTier: "depth",
  },
  {
    name: "Elazar Barkan",
    slug: "elazar-barkan",
    domain: 'History / "The Guilt of Nations"',
    corePosition: "Comparative analysis of reparations worldwide — German payments, Japanese American redress, indigenous settlements; what works, what fails, and why",
    recognitionTier: "depth",
  },
  {
    name: "Hilary Beckles",
    slug: "hilary-beckles",
    domain: "History / CARICOM Reparations Commission",
    corePosition: "Caribbean reparations demand from European colonial powers — Britain, France, and the Netherlands owe debts to the societies they built on slave labor",
    recognitionTier: "surprise",
  },
  {
    name: "Michael Dawson",
    slug: "michael-dawson",
    domain: 'Political science / "Behind the Mule"',
    corePosition: "Black political unity on reparations is not monolithic — the range of positions within Black communities reflects genuine disagreements about strategy and form",
    recognitionTier: "surprise",
  },
  {
    name: "Saidiya Hartman",
    slug: "saidiya-hartman",
    domain: 'Literature / "Lose Your Mother"',
    corePosition: "The afterlife of slavery — the past is not past; tracing the lineage of dispossession through the present; the impossibility and necessity of repair",
    recognitionTier: "surprise",
  },
  {
    name: "Glen Sean Coulthard",
    slug: "glen-sean-coulthard",
    domain: 'Political science / "Red Skin, White Masks"',
    corePosition: "Indigenous peoples need land back, not recognition — Canadian reconciliation without material restitution is a new form of colonial management",
    recognitionTier: "surprise",
  },
  {
    name: "Pablo de Greiff",
    slug: "pablo-de-greiff",
    domain: "Philosophy / UN transitional justice",
    corePosition: "The international framework for reparations — what the UN rapporteur's principles say about who is owed what after mass atrocity",
    recognitionTier: "surprise",
  },
  {
    name: "Eric Yamamoto",
    slug: "eric-yamamoto",
    domain: 'Law / "Interracial Justice"',
    corePosition: "Japanese American redress as precedent and framework — how the 1988 Civil Liberties Act passed, what it means for other groups, and the interracial coalition model",
    recognitionTier: "surprise",
  },
  {
    name: "John Tateishi",
    slug: "john-tateishi",
    domain: "Activism / Japanese American Citizens League",
    corePosition: "Led the campaign that actually won reparations — the practical strategy, political coalition-building, and messaging that got the 1988 redress bill signed into law",
    recognitionTier: "surprise",
  },
];
