import { PoolThinker } from "./types";

export const spaceColonizationPool: PoolThinker[] = [
  {
    name: "Carl Sagan",
    slug: "carl-sagan",
    domain: 'Astronomy / "Pale Blue Dot"',
    corePosition: 'The cosmic perspective — space exploration reveals both our insignificance and our responsibility; "we are a way for the cosmos to know itself"',
    recognitionTier: "anchor",
  },
  {
    name: "Kim Stanley Robinson",
    slug: "kim-stanley-robinson",
    domain: "Science fiction / Mars trilogy",
    corePosition: "The most detailed fictional imagining of Mars colonization — political economy, ecology, and social organization of a new world; science fiction as governance thought experiment",
    recognitionTier: "anchor",
  },
  {
    name: "Daniel Deudney",
    slug: "daniel-deudney",
    domain: 'Political science / "Dark Skies"',
    corePosition: "Space expansion will increase existential risk, not reduce it — militarization, conflict, and the extension of human violence beyond Earth",
    recognitionTier: "anchor",
  },
  {
    name: "Gerard O'Neill",
    slug: "gerard-oneill",
    domain: 'Physics / "The High Frontier" (foundational)',
    corePosition: "Proposed orbital habitats in the 1970s — humans shouldn't live on planets at all; rotating cylinders with artificial gravity are the real future",
    recognitionTier: "anchor",
  },
  {
    name: "Robert Zubrin",
    slug: "robert-zubrin",
    domain: 'Aerospace engineering / "The Case for Mars"',
    corePosition: "Mars Direct — the engineering plan that made Mars colonization seem achievable with existing technology; the most-cited technical blueprint",
    recognitionTier: "anchor",
  },
  {
    name: "Lucianne Walkowicz",
    slug: "lucianne-walkowicz",
    domain: "Astronomy / space ethics",
    corePosition: "Space colonization without ethical frameworks reproduces colonialism — planetary protection and indigenous rights frameworks must apply beyond Earth",
    recognitionTier: "depth",
  },
  {
    name: "Chris Impey",
    slug: "chris-impey",
    domain: 'Astronomy / "Beyond"',
    corePosition: "The practical timeline for space settlement — what's achievable when, with what technology, and what the actual barriers are (radiation, psychology, cost)",
    recognitionTier: "depth",
  },
  {
    name: "Namrata Goswami",
    slug: "namrata-goswami",
    domain: 'Space policy / "Scramble for the Skies"',
    corePosition: "Great power competition in space — China, India, and the U.S. are already competing for lunar resources; the geopolitics of space",
    recognitionTier: "depth",
  },
  {
    name: "James Schwartz",
    slug: "james-schwartz",
    domain: 'Philosophy / "The Value of Science in Space Exploration"',
    corePosition: "Science, not colonization, should drive space exploration — the case for unmanned missions and against human settlement as priority",
    recognitionTier: "depth",
  },
  {
    name: "Frank White",
    slug: "frank-white",
    domain: 'Space philosophy / "The Overview Effect"',
    corePosition: "Astronauts who see Earth from space undergo cognitive transformation — the overview effect suggests space exploration changes consciousness itself",
    recognitionTier: "depth",
  },
  {
    name: "Lori Garver",
    slug: "lori-garver",
    domain: "NASA / space policy",
    corePosition: "Democratizing space access — the case that commercial spaceflight serves public interest better than government-only programs; pragmatic space policy",
    recognitionTier: "depth",
  },
  {
    name: "Octavia Butler",
    slug: "octavia-butler",
    domain: 'Science fiction / "Parable" series',
    corePosition: "Human nature will follow us to the stars — space doesn't redeem us; the hard question is whether we can change before we expand",
    recognitionTier: "depth",
  },
  {
    name: "Kelly and Zach Weinersmith",
    slug: "kelly-zach-weinersmith",
    domain: 'Science / "A City on Mars"',
    corePosition: "Debunks the near-term viability of space settlement — the gap between rhetoric and physical reality is enormous; the technical debunking",
    recognitionTier: "depth",
  },
  {
    name: "Charles Cockell",
    slug: "charles-cockell",
    domain: 'Astrobiology / "Extra-Terrestrial Liberty"',
    corePosition: "Freedom in space requires intentional constitutional design — extraterrestrial environments create totalitarian temptations; liberty doesn't happen by default in sealed habitats",
    recognitionTier: "depth",
  },
  {
    name: "Mary Robinette Kowal",
    slug: "mary-robinette-kowal",
    domain: 'Science fiction / "The Calculating Stars"',
    corePosition: "Space as continuation of Earth politics — who gets to go, whose labor makes it possible, and what we carry with us",
    recognitionTier: "depth",
  },
  {
    name: "Pete Worden",
    slug: "pete-worden",
    domain: "Breakthrough Starshot / former NASA Ames",
    corePosition: "Interstellar travel — not just Mars but reaching other star systems; laser-propelled spacecraft to Alpha Centauri within a generation",
    recognitionTier: "depth",
  },
  {
    name: "Tony Milligan",
    slug: "tony-milligan",
    domain: "Philosophy / space ethics",
    corePosition: "The ethical frameworks for space settlement — property, indigenous rights, environmental protection — need to be developed before, not after, we arrive",
    recognitionTier: "surprise",
  },
  {
    name: "Savannah Mandel",
    slug: "savannah-mandel",
    domain: 'Anthropology / "Ground Control"',
    corePosition: "Ethnography of the space industry — who works in commercial space, what motivates them, and whose dreams of the future are being built",
    recognitionTier: "surprise",
  },
  {
    name: "Alice Gorman",
    slug: "alice-gorman",
    domain: 'Space archaeology / "Dr. Space Junk"',
    corePosition: "Space debris and heritage — orbit is already being treated as a commons tragedy; the governance lesson from what we've already done to near-Earth space",
    recognitionTier: "surprise",
  },
  {
    name: "Erika Nesvold",
    slug: "erika-nesvold",
    domain: "Astrophysics / Off-Earth ethics",
    corePosition: "Designed ethics frameworks for space settlement — labor, governance, reproduction, and justice in extraterrestrial communities",
    recognitionTier: "surprise",
  },
  {
    name: "Deji Bryce Olukotun",
    slug: "deji-bryce-olukotun",
    domain: "Fiction / Afrofuturist space narratives",
    corePosition: "Space colonization through African diaspora lens — who gets to imagine the future? Whose narratives of exploration are centered?",
    recognitionTier: "surprise",
  },
  {
    name: "Adam Morton",
    slug: "adam-morton",
    domain: "Philosophy / planetary ethics",
    corePosition: "Terraforming raises unique ethical questions — do we have the right to transform another world? What would consent look like?",
    recognitionTier: "surprise",
  },
];
