import { PoolThinker } from "./types";

export const surveillancePrivacyPool: PoolThinker[] = [
  {
    name: "Edward Snowden",
    slug: "edward-snowden",
    domain: 'Whistleblowing / "Permanent Record"',
    corePosition: "Mass surveillance is unconstitutional and dangerous — revealed NSA programs at enormous personal cost; the defining figure of the privacy debate",
    recognitionTier: "anchor",
  },
  {
    name: "Shoshana Zuboff",
    slug: "shoshana-zuboff",
    domain: 'Business / "The Age of Surveillance Capitalism"',
    corePosition: 'Big Tech\'s business model is extracting and trading in human behavioral data — "surveillance capitalism" as a new economic logic that eliminates privacy',
    recognitionTier: "anchor",
  },
  {
    name: "Michel Foucault",
    slug: "michel-foucault",
    domain: 'Philosophy / "Discipline and Punish"',
    corePosition: "The Panopticon — surveillance produces self-discipline; power works through visibility; you don't need to watch everyone, just make them believe they're watched",
    recognitionTier: "anchor",
  },
  {
    name: "Bruce Schneier",
    slug: "bruce-schneier",
    domain: 'Security / "Data and Goliath"',
    corePosition: "Security and liberty are not trade-offs — mass surveillance doesn't work for security and destroys freedom; specific, targeted surveillance with oversight works",
    recognitionTier: "anchor",
  },
  {
    name: "Glenn Greenwald",
    slug: "glenn-greenwald",
    domain: 'Journalism / "No Place to Hide"',
    corePosition: "Published Snowden's revelations — government secrecy enables abuse; transparency and adversarial journalism are democracy's immune system",
    recognitionTier: "anchor",
  },
  {
    name: "George Orwell",
    slug: "george-orwell",
    domain: 'Literature / "1984" (foundational)',
    corePosition: "Big Brother — the totalitarian surveillance state as warning; the vocabulary for discussing state surveillance power",
    recognitionTier: "anchor",
  },
  {
    name: "Cory Doctorow",
    slug: "cory-doctorow",
    domain: "Tech policy / fiction",
    corePosition: '"Enshittification" and the case for interoperability — platforms degrade toward surveillance; structural technical remedies over regulation',
    recognitionTier: "anchor",
  },
  {
    name: "Helen Nissenbaum",
    slug: "helen-nissenbaum",
    domain: 'Philosophy / "Privacy in Context"',
    corePosition: "Contextual integrity — information flows should match social norms; privacy violations occur when data moves between contexts inappropriately",
    recognitionTier: "depth",
  },
  {
    name: "David Lyon",
    slug: "david-lyon",
    domain: 'Sociology / "Surveillance Studies"',
    corePosition: 'Founded the academic field of surveillance studies — "surveillance culture" means we\'ve internalized watching and being watched as normal',
    recognitionTier: "depth",
  },
  {
    name: "Simone Browne",
    slug: "simone-browne",
    domain: 'Sociology / "Dark Matters"',
    corePosition: "Surveillance is racialized — from slave passes to facial recognition, monitoring technologies have always targeted Black bodies first",
    recognitionTier: "depth",
  },
  {
    name: "Daniel Solove",
    slug: "daniel-solove",
    domain: 'Law / "Understanding Privacy"',
    corePosition: "Privacy is not one thing — it's a family of related concerns (information collection, processing, dissemination, invasion); taxonomic clarity enables better law",
    recognitionTier: "depth",
  },
  {
    name: "Woodrow Hartzog",
    slug: "woodrow-hartzog",
    domain: 'Law / "Privacy\'s Blueprint"',
    corePosition: "Design determines privacy — legal rights mean nothing if the technology is built to undermine them; privacy-by-design as regulatory mandate",
    recognitionTier: "depth",
  },
  {
    name: "Meredith Whittaker",
    slug: "meredith-whittaker",
    domain: "AI / Signal president",
    corePosition: "End-to-end encryption is a human right — the infrastructure of private communication must exist independent of any company's business model",
    recognitionTier: "depth",
  },
  {
    name: "Viktor Mayer-Schönberger",
    slug: "viktor-mayer-schonberger",
    domain: 'Information law / "Delete"',
    corePosition: 'The right to be forgotten — digital memory is dangerous; humans evolved to forget and digital permanence breaks something essential about social life',
    recognitionTier: "depth",
  },
  {
    name: "Kashmir Hill",
    slug: "kashmir-hill",
    domain: 'Journalism / "Your Face Belongs to Us"',
    corePosition: "Documented Clearview AI's scraping of billions of faces — the journalism that made mass facial recognition a public issue",
    recognitionTier: "depth",
  },
  {
    name: "Frank Pasquale",
    slug: "frank-pasquale",
    domain: 'Law / "The Black Box Society"',
    corePosition: "Algorithms that affect lives must be auditable — the accountability gap in automated decision-making; transparency as minimum requirement",
    recognitionTier: "depth",
  },
  {
    name: "Maciej Cegłowski",
    slug: "maciej-ceglowski",
    domain: "Tech / The Website Obesity Crisis",
    corePosition: "Data is toxic waste, not the new oil — every piece of data collected is a liability; the argument for data minimization as default",
    recognitionTier: "depth",
  },
  {
    name: "Virginia Eubanks",
    slug: "virginia-eubanks",
    domain: 'Political science / "Automating Inequality"',
    corePosition: "Surveillance systems punish the already-marginalized — automated eligibility, predictive policing, and digital tracking concentrate harm on the poor",
    recognitionTier: "depth",
  },
  {
    name: "Max Schrems",
    slug: "max-schrems",
    domain: "Privacy activism / noyb",
    corePosition: "The Austrian activist who invalidated two U.S.-EU data transfer agreements — individual legal action forcing structural privacy change",
    recognitionTier: "depth",
  },
  {
    name: "Clare Garvie",
    slug: "clare-garvie",
    domain: "Law / facial recognition",
    corePosition: "The Georgetown research documenting police facial recognition — which departments use it, on whom, with what accuracy, and with what oversight (almost none)",
    recognitionTier: "depth",
  },
  {
    name: "Torin Monahan",
    slug: "torin-monahan",
    domain: "Communication / surveillance studies",
    corePosition: "Surveillance is productive, not just repressive — it creates categories, populations, and identities; understanding it requires seeing what it builds, not just what it restricts",
    recognitionTier: "surprise",
  },
  {
    name: "Os Keyes",
    slug: "os-keyes",
    domain: "Information science / trans surveillance",
    corePosition: "Facial recognition and gender classification systems harm trans people specifically — the intersection of surveillance technology and gender nonconformity",
    recognitionTier: "surprise",
  },
  {
    name: "Amba Kak",
    slug: "amba-kak",
    domain: "AI Now Institute / Global South surveillance",
    corePosition: "Surveillance technology exported from democracies to authoritarians — the international trade in tools of repression",
    recognitionTier: "surprise",
  },
  {
    name: "Julie Cohen",
    slug: "julie-cohen",
    domain: 'Law / "Between Truth and Power"',
    corePosition: "The informational body — law must recognize that data about people constitutes a form of power over them; the biopolitics of information",
    recognitionTier: "surprise",
  },
  {
    name: "Wolfie Christl",
    slug: "wolfie-christl",
    domain: "Researcher / corporate surveillance",
    corePosition: "Maps the actual data flows — who collects what, sells it to whom, and how the data broker ecosystem works in practice; the empirical infrastructure",
    recognitionTier: "surprise",
  },
];
