import { PoolThinker } from "./types";

export const taiwanPool: PoolThinker[] = [
  {
    name: "Graham Allison",
    slug: "graham-allison",
    domain: 'Political science / "Destined for War"',
    corePosition: "The Thucydides Trap — rising powers and established powers tend toward war; U.S.-China conflict over Taiwan is the most dangerous instance",
    recognitionTier: "anchor",
  },
  {
    name: "John Mearsheimer",
    slug: "john-mearsheimer",
    domain: "Political science / realism",
    corePosition: "Taiwan cannot be defended without nuclear-level risk — the U.S. should not commit to a war it might lose over an island it doesn't need",
    recognitionTier: "anchor",
  },
  {
    name: "Chris Miller",
    slug: "chris-miller",
    domain: 'History / "Chip War"',
    corePosition: "Taiwan's semiconductor monopoly (TSMC) makes it the most strategically important territory on Earth — whoever controls the chips controls the future",
    recognitionTier: "anchor",
  },
  {
    name: "Henry Kissinger",
    slug: "henry-kissinger",
    domain: "Diplomacy / One China architect",
    corePosition: "Designed the strategic ambiguity framework in 1972 — constructive ambiguity as diplomatic technology; clarity is not always an asset",
    recognitionTier: "anchor",
  },
  {
    name: "Elbridge Colby",
    slug: "elbridge-colby",
    domain: 'Defense strategy / "The Strategy of Denial"',
    corePosition: "Taiwan is the decisive theater — the U.S. must prioritize Pacific deterrence over all other commitments; a denial strategy can work without escalation to nuclear war",
    recognitionTier: "anchor",
  },
  {
    name: "Audrey Tang",
    slug: "audrey-tang",
    domain: "Civic technology / Taiwan's digital minister",
    corePosition: "Taiwan as democratic technology laboratory — digital democracy, open government, and civic hacking as both domestic governance and soft power",
    recognitionTier: "anchor",
  },
  {
    name: "Bonnie Glaser",
    slug: "bonnie-glaser",
    domain: "China studies / CSIS",
    corePosition: "The empirical center of cross-strait analysis — what China's military can actually do, what deterrence requires, what signals mean",
    recognitionTier: "depth",
  },
  {
    name: "Oriana Skylar Mastro",
    slug: "oriana-skylar-mastro",
    domain: "Political science / Stanford",
    corePosition: "China is preparing for a Taiwan operation — not because war is inevitable, but because Xi has decided the status quo is no longer acceptable",
    recognitionTier: "depth",
  },
  {
    name: "Michael Beckley",
    slug: "michael-beckley",
    domain: 'Political science / "Danger Zone"',
    corePosition: "The window of maximum danger is now — China's power is peaking, not rising indefinitely; declining powers take risks rising powers don't",
    recognitionTier: "depth",
  },
  {
    name: "Shelley Rigger",
    slug: "shelley-rigger",
    domain: 'Political science / "The Tiger Leading the Dragon"',
    corePosition: "Taiwanese identity has transformed — the population increasingly identifies as Taiwanese, not Chinese; unification is politically impossible regardless of military balance",
    recognitionTier: "depth",
  },
  {
    name: "Kevin Rudd",
    slug: "kevin-rudd",
    domain: 'Diplomacy / "The Avoidable War"',
    corePosition: "U.S.-China managed competition — neither containment nor accommodation; stabilize the relationship enough to avoid war while competing vigorously",
    recognitionTier: "depth",
  },
  {
    name: "Morris Chang",
    slug: "morris-chang",
    domain: "TSMC founder",
    corePosition: "Built the semiconductor monopoly — understood decades ago that chip manufacturing would be geopolitically decisive; Taiwan's \"silicon shield\"",
    recognitionTier: "depth",
  },
  {
    name: "Lyle Goldstein",
    slug: "lyle-goldstein",
    domain: "Naval strategy / China maritime",
    corePosition: "Engagement and restraint — the U.S. military buildup around Taiwan is provocative, not stabilizing; escalation spirals are the real risk",
    recognitionTier: "depth",
  },
  {
    name: "Jessica Chen Weiss",
    slug: "jessica-chen-weiss",
    domain: "Political science / Cornell",
    corePosition: "Chinese nationalism constrains leadership options — public opinion in China makes backing down on Taiwan politically impossible; audience costs matter",
    recognitionTier: "depth",
  },
  {
    name: "Kharis Templeman",
    slug: "kharis-templeman",
    domain: "Taiwan studies / Hoover",
    corePosition: "Taiwan's domestic politics and party system — how internal dynamics (DPP vs. KMT) shape cross-strait relations from the Taipei side",
    recognitionTier: "depth",
  },
  {
    name: "Ryan Hass",
    slug: "ryan-hass",
    domain: "Brookings / former NSC",
    corePosition: "The case for maintaining strategic ambiguity — clarity in either direction (defend or abandon) makes war more likely, not less",
    recognitionTier: "depth",
  },
  {
    name: "Jude Blanchette",
    slug: "jude-blanchette",
    domain: "China studies / CSIS",
    corePosition: "Xi's decision-making and CCP internal politics — understanding what drives Beijing requires understanding the domestic political constraints on Chinese leaders",
    recognitionTier: "depth",
  },
  {
    name: "Matt Pottinger",
    slug: "matt-pottinger",
    domain: 'Former NSC / "The Boiling Moat"',
    corePosition: "Taiwan must invest massively in asymmetric defense — mines, mobile missiles, distributed forces; make invasion too costly to attempt",
    recognitionTier: "depth",
  },
  {
    name: "Yan Xuetong",
    slug: "yan-xuetong",
    domain: "International relations / Tsinghua",
    corePosition: "China's leading IR theorist — moral realism; China's rise requires a different international order, not accommodation within America's",
    recognitionTier: "depth",
  },
  {
    name: "Wu Xinbo",
    slug: "wu-xinbo",
    domain: "International relations / Fudan",
    corePosition: "The Chinese academic perspective on Taiwan — U.S. interference is the obstacle to peaceful resolution; without American arms, Taiwan would negotiate",
    recognitionTier: "depth",
  },
  {
    name: "Ian Easton",
    slug: "ian-easton",
    domain: 'Defense / "The Chinese Invasion Threat"',
    corePosition: "Detailed military analysis of what a Taiwan invasion would actually look like — terrain, logistics, and why amphibious assault is extremely difficult",
    recognitionTier: "surprise",
  },
  {
    name: "Lev Nachman",
    slug: "lev-nachman",
    domain: "Political science / Taiwan youth",
    corePosition: "Taiwanese youth identity and political engagement — the generation that grew up post-democratization and has no connection to Chinese identity",
    recognitionTier: "surprise",
  },
  {
    name: "Tanner Greer",
    slug: "tanner-greer",
    domain: "Strategy / The Scholar's Stage",
    corePosition: "Historical parallels for the Taiwan situation — what Cold War deterrence, Korean War decisions, and pre-WWI diplomacy tell us about escalation",
    recognitionTier: "surprise",
  },
  {
    name: "Syaru Shirley Lin",
    slug: "syaru-shirley-lin",
    domain: 'Political economy / "Taiwan\'s China Dilemma"',
    corePosition: "Taiwan's economic dependence on China creates vulnerability that military deterrence alone cannot address — the economic dimension of cross-strait security",
    recognitionTier: "surprise",
  },
  {
    name: "Brendan Taylor",
    slug: "brendan-taylor",
    domain: 'Strategic studies / "Dangerous Decade"',
    corePosition: "Maps the specific escalation pathways — not whether conflict is likely in the abstract, but which scenarios lead to miscalculation",
    recognitionTier: "surprise",
  },
  {
    name: "Evan Medeiros",
    slug: "evan-medeiros",
    domain: "China policy / Georgetown",
    corePosition: "The practitioner's view of U.S.-China relations — what diplomacy can and cannot achieve; the gap between strategy documents and actual management",
    recognitionTier: "surprise",
  },
];
