import { PoolThinker } from "./types";

export const transRightsPool: PoolThinker[] = [
  {
    name: "Judith Butler",
    slug: "judith-butler",
    domain: 'Philosophy / "Gender Trouble"',
    corePosition: "Gender is performative, not natural — the foundational theoretical framework for understanding sex/gender as socially constructed",
    recognitionTier: "anchor",
  },
  {
    name: "J.K. Rowling",
    slug: "jk-rowling",
    domain: "Literature / gender-critical feminism",
    corePosition: "Sex is biological and immutable; self-ID threatens women's sex-based rights and spaces — the most visible voice of gender-critical feminism",
    recognitionTier: "anchor",
  },
  {
    name: "Laverne Cox",
    slug: "laverne-cox",
    domain: "Acting / trans advocacy",
    corePosition: "Trans visibility and dignity — the most recognizable trans public figure; representation as political act",
    recognitionTier: "anchor",
  },
  {
    name: "Abigail Shrier",
    slug: "abigail-shrier",
    domain: 'Journalism / "Irreversible Damage"',
    corePosition: "Rapid-onset gender dysphoria in adolescent girls is a social contagion — medical transition of minors is harm disguised as affirmation",
    recognitionTier: "anchor",
  },
  {
    name: "Andrea Long Chu",
    slug: "andrea-long-chu",
    domain: 'Criticism / "Females"',
    corePosition: "Transition is about desire, not identity — the case for bodily autonomy without requiring medical gatekeeping or political justification",
    recognitionTier: "anchor",
  },
  {
    name: "Helen Joyce",
    slug: "helen-joyce",
    domain: 'Journalism / "Trans"',
    corePosition: "Gender self-identification undermines material reality — sex matters for law, medicine, and policy; redefining it has cascading consequences",
    recognitionTier: "anchor",
  },
  {
    name: "Janet Mock",
    slug: "janet-mock",
    domain: 'Memoir / "Redefining Realness"',
    corePosition: "Trans womanhood as lived truth — intersections of race, class, and gender; the personal as political testimony",
    recognitionTier: "anchor",
  },
  {
    name: "Sandy Stone",
    slug: "sandy-stone",
    domain: 'Media studies / "The Empire Strikes Back"',
    corePosition: "The foundational trans studies text — trans people must not be required to pass or conform to cisgender narratives; multiplicity over assimilation",
    recognitionTier: "depth",
  },
  {
    name: "Kathleen Stock",
    slug: "kathleen-stock",
    domain: 'Philosophy / "Material Girls"',
    corePosition: "Sex is a biological category distinct from gender identity — philosophical argument for maintaining the distinction without denying trans people's dignity",
    recognitionTier: "depth",
  },
  {
    name: "Jack Halberstam",
    slug: "jack-halberstam",
    domain: 'Gender studies / "Trans*"',
    corePosition: "Trans as radical openness — not a fixed identity but a challenge to all categorical thinking about gender; queer negativity",
    recognitionTier: "depth",
  },
  {
    name: "Julia Serano",
    slug: "julia-serano",
    domain: 'Biology / "Whipping Girl"',
    corePosition: "Transmisogyny — trans women face a specific intersection of transphobia and misogyny; sexism is the root, not gender nonconformity per se",
    recognitionTier: "depth",
  },
  {
    name: "Ray Blanchard",
    slug: "ray-blanchard",
    domain: "Sexology / autogynephilia theory",
    corePosition: "Two types of male-to-female transsexualism — homosexual and autogynephilic; the most contested and polarizing theory in trans clinical science",
    recognitionTier: "depth",
  },
  {
    name: "Hilary Cass",
    slug: "hilary-cass",
    domain: "Pediatrics / Cass Review",
    corePosition: "Led the UK review of youth gender services — concluded evidence for puberty blockers is weak; recommended caution and holistic care over early medical intervention",
    recognitionTier: "depth",
  },
  {
    name: "Florence Ashley",
    slug: "florence-ashley",
    domain: "Law and bioethics / trans healthcare",
    corePosition: "Trans-affirming care is evidence-based and ethical — the Cass Review and similar efforts reflect moral panic, not scientific rigor",
    recognitionTier: "depth",
  },
  {
    name: "Susan Stryker",
    slug: "susan-stryker",
    domain: 'History / "Transgender History"',
    corePosition: 'The historical record of trans existence across cultures and centuries — trans identity is not new; the "trend" narrative is historically ignorant',
    recognitionTier: "depth",
  },
  {
    name: "Lisa Littman",
    slug: "lisa-littman",
    domain: "Medicine / ROGD study",
    corePosition: 'Coined "rapid-onset gender dysphoria" — the clinical observation that clusters of adolescents present simultaneously; contested methodology, influential framing',
    recognitionTier: "depth",
  },
  {
    name: "Paisley Currah",
    slug: "paisley-currah",
    domain: 'Political science / "Sex Is as Sex Does"',
    corePosition: "Legal sex is not biology but a classification system that states use for governance — the regulatory function of sex categories",
    recognitionTier: "depth",
  },
  {
    name: "Deirdre McCloskey",
    slug: "deirdre-mccloskey",
    domain: "Economics / memoir",
    corePosition: 'Transitioned at 53 as a prominent economist — "Crossing" documents the personal and intellectual transformation; the late-transition perspective',
    recognitionTier: "depth",
  },
  {
    name: "Doriane Coleman",
    slug: "doriane-coleman",
    domain: "Law / sports policy",
    corePosition: "The case for sex-based categories in sport — testosterone exposure during male puberty creates performance advantages that persist; fairness requires boundaries",
    recognitionTier: "depth",
  },
  {
    name: "Talia Mae Bettcher",
    slug: "talia-mae-bettcher",
    domain: "Philosophy / trans feminism",
    corePosition: '"First-person authority" — trans people have epistemic authority over their own gender; others\' skepticism is a form of violence, not reasonable inquiry',
    recognitionTier: "depth",
  },
  {
    name: "Jesse Singal",
    slug: "jesse-singal",
    domain: "Journalism / detransition",
    corePosition: "Detransition and regret deserve serious attention — the medical system is failing some patients by affirming too quickly; journalistic investigation",
    recognitionTier: "depth",
  },
  {
    name: "Thomas Page McBee",
    slug: "thomas-page-mcbee",
    domain: 'Memoir / "Amateur"',
    corePosition: "The phenomenology of becoming male — what masculinity looks like from someone who chose it; gender as experienced rather than theorized",
    recognitionTier: "depth",
  },
  {
    name: "Eric Vilain",
    slug: "eric-vilain",
    domain: "Genetics / disorders of sex development",
    corePosition: 'Biological sex is more complex than binary — intersex conditions demonstrate that "male" and "female" are endpoints on a spectrum, not discrete categories',
    recognitionTier: "depth",
  },
  {
    name: "Toby Beauchamp",
    slug: "toby-beauchamp",
    domain: 'Gender studies / "Going Stealth"',
    corePosition: "Trans surveillance and state visibility — the way governments track and classify bodies is always a form of control",
    recognitionTier: "surprise",
  },
  {
    name: "Finn Mackay",
    slug: "finn-mackay",
    domain: 'Feminism / "Female Masculinities"',
    corePosition: "Not all gender nonconformity is trans — butch lesbian identity and trans masculinity exist in the same landscape without being the same thing",
    recognitionTier: "surprise",
  },
  {
    name: "Grace Lavery",
    slug: "grace-lavery",
    domain: 'Literature / "Please Miss"',
    corePosition: "Trans femininity as aesthetic and intellectual practice — camp, excess, and refusal of respectability; against the medicalization of gender",
    recognitionTier: "surprise",
  },
  {
    name: "Emi Koyama",
    slug: "emi-koyama",
    domain: 'Intersex/trans activism / "Transfeminist Manifesto"',
    corePosition: "The intersections of trans and feminist politics — neither is complete without the other; the manifesto that bridged two movements",
    recognitionTier: "surprise",
  },
  {
    name: "Serena Nanda",
    slug: "serena-nanda",
    domain: 'Anthropology / "Gender Diversity"',
    corePosition: "Cross-cultural survey of gender systems — hijra, Two-Spirit, fa'afafine — demonstrates that binary gender is a specific Western arrangement, not a human universal",
    recognitionTier: "surprise",
  },
  {
    name: "Walt Heyer",
    slug: "walt-heyer",
    domain: "Detransition advocacy",
    corePosition: "Lived experience of regret — transitioned and detransitioned; argues the medical system failed him and is failing others through insufficient screening",
    recognitionTier: "surprise",
  },
  {
    name: "Robert Garofalo",
    slug: "robert-garofalo",
    domain: "Adolescent medicine / Lurie Children's",
    corePosition: "The clinical case for gender-affirming care in adolescents — longitudinal outcomes data showing mental health improvement with appropriate medical support",
    recognitionTier: "surprise",
  },
];
