import { PoolThinker } from "./types";

export const truthMediaPool: PoolThinker[] = [
  {
    name: "Noam Chomsky",
    slug: "noam-chomsky",
    domain: 'Linguistics / "Manufacturing Consent"',
    corePosition: "Mass media serves elite interests by filtering information through propaganda — the political economy of news production, not individual bias, determines what gets covered",
    recognitionTier: "anchor",
  },
  {
    name: "Hannah Arendt",
    slug: "hannah-arendt",
    domain: 'Philosophy / "The Origins of Totalitarianism"',
    corePosition: "Totalitarianism requires the destruction of truth — lying as a political instrument; the relation between factual truth and political reality",
    recognitionTier: "anchor",
  },
  {
    name: "Marshall McLuhan",
    slug: "marshall-mcluhan",
    domain: "Media theory / The Medium is the Message",
    corePosition: "The medium shapes content and consciousness more than the message — television made politics visual; the internet makes everything immediate; medium is the message",
    recognitionTier: "anchor",
  },
  {
    name: "Neil Postman",
    slug: "neil-postman",
    domain: 'Media criticism / "Amusing Ourselves to Death"',
    corePosition: "Television transformed public discourse into entertainment — Huxley was right, not Orwell; we're drowning in irrelevance, not censorship",
    recognitionTier: "anchor",
  },
  {
    name: "Renée DiResta",
    slug: "renee-diresta",
    domain: "Computational propaganda / Stanford Internet Observatory",
    corePosition: "Disinformation is an adversarial operation, not accidental misinformation — the architecture of influence campaigns, coordinated inauthentic behavior, and how platforms are weaponized",
    recognitionTier: "anchor",
  },
  {
    name: "Julian Assange",
    slug: "julian-assange",
    domain: "Journalism / WikiLeaks",
    corePosition: "Radical transparency as democratic necessity — government secrecy enables war crimes and corruption; publishing classified documents serves the public interest regardless of political consequence",
    recognitionTier: "anchor",
  },
  {
    name: "George Orwell",
    slug: "george-orwell",
    domain: 'Literature / "1984" and "Politics and the English Language"',
    corePosition: "Political language is designed to make lies sound truthful — doublespeak, Newspeak, and the corruption of meaning as a tool of power",
    recognitionTier: "anchor",
  },
  {
    name: "Zeynep Tufekci",
    slug: "zeynep-tufekci",
    domain: "Sociology / tech critique",
    corePosition: "Algorithmic amplification of outrage is the structural problem — not fake news per se, but the incentives that make engagement-maximizing content override truth-maximizing content",
    recognitionTier: "depth",
  },
  {
    name: "Jay Rosen",
    slug: "jay-rosen",
    domain: "Journalism studies / NYU",
    corePosition: "The press as a political actor, not a neutral observer — the view from nowhere is a choice with consequences; journalism needs a theory of its own purpose",
    recognitionTier: "depth",
  },
  {
    name: "Yochai Benkler",
    slug: "yochai-benkler",
    domain: 'Law / "Network Propaganda"',
    corePosition: "Right-wing media is structurally different — not a symmetric polarization problem but an asymmetric one where Fox, Breitbart, and talk radio form a closed epistemic ecosystem",
    recognitionTier: "depth",
  },
  {
    name: "Whitney Phillips",
    slug: "whitney-phillips",
    domain: "Media studies / trolling and disinformation",
    corePosition: "Mainstream media amplifies fringe content — the symbiotic relationship between trolls and journalists; covering disinformation can spread it; attention is the currency being gamed",
    recognitionTier: "depth",
  },
  {
    name: "danah boyd",
    slug: "danah-boyd",
    domain: "Media studies / Data & Society",
    corePosition: "Teaching people to distrust media is itself a vector for manipulation — media literacy can backfire; the infrastructure of information sharing matters more than individual critical thinking",
    recognitionTier: "depth",
  },
  {
    name: "Walter Lippmann",
    slug: "walter-lippmann",
    domain: 'Journalism / "Public Opinion" (foundational)',
    corePosition: "The world outside and the pictures in our heads — the original argument that the public needs expert intermediaries to interpret a complex world; the founding case for professional journalism",
    recognitionTier: "depth",
  },
  {
    name: "Michel Foucault",
    slug: "michel-foucault",
    domain: 'Philosophy / "The Order of Discourse"',
    corePosition: "Knowledge and power are inseparable — who gets to speak truth, under what conditions, to whom; truth is produced by regimes of power, not discovered outside them",
    recognitionTier: "depth",
  },
  {
    name: "Joan Donovan",
    slug: "joan-donovan",
    domain: "Media manipulation / Harvard Shorenstein Center",
    corePosition: "Infrastructure of disinformation — who builds and maintains the systems that spread falsehoods; platform accountability and the political economy of information",
    recognitionTier: "depth",
  },
  {
    name: "Jürgen Habermas",
    slug: "jurgen-habermas",
    domain: 'Philosophy / "The Structural Transformation of the Public Sphere"',
    corePosition: "The public sphere requires communicative rationality — spaces of public deliberation based on argument rather than power or money; the ideal speech situation as democratic norm",
    recognitionTier: "depth",
  },
  {
    name: "Tim Wu",
    slug: "tim-wu",
    domain: 'Law / "The Attention Merchants"',
    corePosition: "Attention has been commercialized and the cost is democracy — advertising-based media has always been in tension with the public interest; the attention economy's democratic consequences",
    recognitionTier: "depth",
  },
  {
    name: "Siva Vaidhyanathan",
    slug: "siva-vaidhyanathan",
    domain: 'Media studies / "Anti-Social Media"',
    corePosition: "Facebook is not a town square — it's a surveillance and manipulation machine; the case against treating platforms as infrastructure deserving First Amendment protection",
    recognitionTier: "depth",
  },
  {
    name: "Emily Bell",
    slug: "emily-bell",
    domain: "Journalism / Columbia Tow Center",
    corePosition: "Platform dependency has broken journalism — when distribution is controlled by Facebook and Google, editorial judgment shifts to algorithmic judgment; the structural crisis of news",
    recognitionTier: "depth",
  },
  {
    name: "Jonathan Rauch",
    slug: "jonathan-rauch",
    domain: 'Political science / "The Constitution of Knowledge"',
    corePosition: "Liberal epistemology has an immune system — peer review, error correction, falsifiability; populist attacks on expertise are attacks on the system of knowledge production itself",
    recognitionTier: "depth",
  },
  {
    name: "Cass Sunstein",
    slug: "cass-sunstein",
    domain: 'Law / "#Republic"',
    corePosition: "Filter bubbles and echo chambers threaten deliberative democracy — the case for serendipitous encounters with different views; the public forum doctrine applied to the internet",
    recognitionTier: "depth",
  },
  {
    name: "Peter Pomerantsev",
    slug: "peter-pomerantsev",
    domain: 'Journalism / "This Is Not Propaganda"',
    corePosition: "Post-truth as authoritarian strategy — Russia's information war isn't about making people believe lies but making people believe nothing; weaponized relativism",
    recognitionTier: "depth",
  },
  {
    name: "Maria Ressa",
    slug: "maria-ressa",
    domain: "Journalism / Rappler (Nobel Peace Prize)",
    corePosition: "Social media enabled Duterte's authoritarian information campaign — first-person account of how platforms were weaponized against journalists and democratic institutions in the Philippines",
    recognitionTier: "depth",
  },
  {
    name: "Claire Wardle",
    slug: "claire-wardle",
    domain: "Mis/disinformation studies / First Draft",
    corePosition: "Information disorder taxonomy — misinformation, disinformation, malinformation are distinct phenomena requiring different interventions; the field's foundational classification framework",
    recognitionTier: "depth",
  },
  {
    name: "Ben Thompson",
    slug: "ben-thompson",
    domain: "Tech analysis / Stratechery",
    corePosition: "Aggregation theory explains platform power — who controls discovery controls media; the business model analysis that explains why Facebook and Google captured journalism's economics",
    recognitionTier: "depth",
  },
  {
    name: "Michael Lynch",
    slug: "michael-lynch",
    domain: 'Philosophy / "The Internet of Us"',
    corePosition: "Google-knowing vs. understanding — outsourcing cognition to search engines changes what knowledge means; epistemic autonomy in the age of information abundance",
    recognitionTier: "surprise",
  },
  {
    name: "C. Thi Nguyen",
    slug: "c-thi-nguyen",
    domain: "Philosophy / echo chambers",
    corePosition: "Echo chambers and epistemic bubbles are different — bubbles are accidental (missing information); chambers are deliberate (active inoculation against outside views); the distinction matters for solutions",
    recognitionTier: "surprise",
  },
  {
    name: "Ethan Zuckerman",
    slug: "ethan-zuckerman",
    domain: 'Media / "Mistrust"',
    corePosition: "Institutional distrust is rational in some cases — the problem is undifferentiated cynicism that can't distinguish between corrupt institutions and fixable ones",
    recognitionTier: "surprise",
  },
  {
    name: "Sophia Rosenfeld",
    slug: "sophia-rosenfeld",
    domain: 'History / "Democracy and Truth"',
    corePosition: "Truth has always been contested in democracies — the current crisis is not unique; what's new is the scale, speed, and commercial incentives of the contestation",
    recognitionTier: "surprise",
  },
  {
    name: "Yael Eisenstat",
    slug: "yael-eisenstat",
    domain: "Former Facebook / election integrity",
    corePosition: "Inside account of how Facebook rejected meaningful disinformation countermeasures — the business model always overrides integrity; insider testimony on platform self-governance failure",
    recognitionTier: "surprise",
  },
  {
    name: "Mike Caulfield",
    slug: "mike-caulfield",
    domain: "Education / SIFT methodology",
    corePosition: "Lateral reading beats critical thinking for verifying online information — check what others say about a source before evaluating the source itself; the web literacy approach that actually works",
    recognitionTier: "surprise",
  },
];
