import { PoolThinker } from "./types";

export const usForeignPolicyPool: PoolThinker[] = [
  {
    name: "Henry Kissinger",
    slug: "henry-kissinger",
    domain: "Diplomacy / realpolitik",
    corePosition: "Power and interest, not values, must drive foreign policy — the architect of détente, the opening to China, and strategic triangulation; realpolitik as statecraft",
    recognitionTier: "anchor",
  },
  {
    name: "Noam Chomsky",
    slug: "noam-chomsky",
    domain: 'Linguistics / "Hegemony or Survival"',
    corePosition: "U.S. foreign policy systematically serves elite interests at the expense of democracy and human rights — the most consistent left critic of American imperial power",
    recognitionTier: "anchor",
  },
  {
    name: "John Mearsheimer",
    slug: "john-mearsheimer",
    domain: "Political science / offensive realism",
    corePosition: "Liberal hegemony has been a catastrophe — democracy promotion, NATO expansion, and the rules-based order have provoked great powers and created instability; offshore balancing instead",
    recognitionTier: "anchor",
  },
  {
    name: "Samantha Power",
    slug: "samantha-power",
    domain: 'Diplomacy / "A Problem from Hell"',
    corePosition: "America has a moral responsibility to prevent genocide — the case for humanitarian intervention and the Responsibility to Protect; idealism as foreign policy",
    recognitionTier: "anchor",
  },
  {
    name: "Andrew Bacevich",
    slug: "andrew-bacevich",
    domain: 'Military history / "The Limits of Power"',
    corePosition: "American militarism is self-defeating — the permanent war economy, overextended commitments, and the gap between what the military can do and what politicians promise",
    recognitionTier: "anchor",
  },
  {
    name: "Samuel Huntington",
    slug: "samuel-huntington",
    domain: 'Political science / "The Clash of Civilizations"',
    corePosition: "Post-Cold War conflict will be civilizational, not ideological — Western universalism is a provocation; cultural and religious identity will drive 21st-century geopolitics",
    recognitionTier: "anchor",
  },
  {
    name: "Francis Fukuyama",
    slug: "francis-fukuyama",
    domain: 'Political science / "The End of History"',
    corePosition: "Liberal democracy is the endpoint of ideological evolution — the neoconservative faith in democratic transformation of the Middle East; later recanted the Iraq application",
    recognitionTier: "anchor",
  },
  {
    name: "Stephen Walt",
    slug: "stephen-walt",
    domain: "Political science / Harvard Kennedy School",
    corePosition: "The Israel lobby has distorted U.S. Middle East policy — realist critique of how domestic interest groups override national interest in foreign policy",
    recognitionTier: "depth",
  },
  {
    name: "Anne-Marie Slaughter",
    slug: "anne-marie-slaughter",
    domain: 'International law / "A New World Order"',
    corePosition: "Networked governance over state sovereignty — foreign policy in a world of transnational problems requires horizontal government networks, not just state-to-state diplomacy",
    recognitionTier: "depth",
  },
  {
    name: "Chas Freeman",
    slug: "chas-freeman",
    domain: "Diplomacy / China policy",
    corePosition: "Engagement with adversaries requires genuine diplomacy — the practitioner's critique of Washington groupthink on China; the case for strategic empathy with rivals",
    recognitionTier: "depth",
  },
  {
    name: "Rosa Brooks",
    slug: "rosa-brooks",
    domain: 'Law / "How Everything Became War"',
    corePosition: "The blurring of war and peace has dangerous consequences — endless low-level conflict, drone warfare, and special operations without declaration create permanent legal and moral ambiguity",
    recognitionTier: "depth",
  },
  {
    name: "Robert Kagan",
    slug: "robert-kagan",
    domain: 'Political science / "The World America Made"',
    corePosition: "American power created the liberal order — without U.S. engagement, the international system returns to great-power competition and authoritarianism; the neoconservative case for hegemony",
    recognitionTier: "depth",
  },
  {
    name: "Rashid Khalidi",
    slug: "rashid-khalidi",
    domain: 'History / "Brokers of Deceit"',
    corePosition: "U.S. Middle East policy has always served Israeli interests over Palestinian rights — the broker of deceit; historical documentation of American bad faith in the peace process",
    recognitionTier: "depth",
  },
  {
    name: "Barry Posen",
    slug: "barry-posen",
    domain: 'Political science / "Restraint"',
    corePosition: "Grand strategy of restraint — the U.S. should do less, not more; overcommitment creates blowback, wastes resources, and enables free-riding allies to avoid hard choices",
    recognitionTier: "depth",
  },
  {
    name: "Michael Walzer",
    slug: "michael-walzer",
    domain: 'Political philosophy / "Just and Unjust Wars"',
    corePosition: "The moral framework for evaluating military intervention — just war theory applied to contemporary conflicts; neither pacifist nor hawkish, but principled about when force is justified",
    recognitionTier: "depth",
  },
  {
    name: "Emma Ashford",
    slug: "emma-ashford",
    domain: "Political science / Stimson Center",
    corePosition: "Liberal hegemony has failed on its own terms — not just realist critique but the empirical record: democracy promotion hasn't worked, interventions have backfired",
    recognitionTier: "depth",
  },
  {
    name: "Pankaj Mishra",
    slug: "pankaj-mishra",
    domain: 'History / "Age of Anger"',
    corePosition: "Western universalism is experienced as imperialism by the Global South — the rage against liberal modernity; what looks like democratic backsliding from Washington looks like self-determination from elsewhere",
    recognitionTier: "depth",
  },
  {
    name: "Daniel Immerwahr",
    slug: "daniel-immerwahr",
    domain: 'History / "How to Hide an Empire"',
    corePosition: "America has always been an empire — the territories, bases, and client states that constitute American power; the gap between self-understanding and historical reality",
    recognitionTier: "depth",
  },
  {
    name: "Kenneth Waltz",
    slug: "kenneth-waltz",
    domain: 'Political science / "Theory of International Politics"',
    corePosition: "Structural realism — the anarchic international system drives state behavior regardless of domestic politics; nuclear deterrence is stable; the system-level analysis that defines IR theory",
    recognitionTier: "depth",
  },
  {
    name: "Kori Schake",
    slug: "kori-schake",
    domain: "Defense policy / American Enterprise Institute",
    corePosition: "America's allies need the U.S. but the U.S. also needs its allies — the conservative internationalist case for alliance maintenance; pushback against both isolationism and unilateralism",
    recognitionTier: "depth",
  },
  {
    name: "Graham Allison",
    slug: "graham-allison",
    domain: 'Political science / "Destined for War"',
    corePosition: "The Thucydides Trap — the historical pattern of conflict when rising powers challenge established ones; whether U.S.-China can escape what Rome and Athens, Britain and Germany could not",
    recognitionTier: "depth",
  },
  {
    name: "Condoleezza Rice",
    slug: "condoleezza-rice",
    domain: "Diplomacy / Stanford Hoover Institution",
    corePosition: "Transformational diplomacy and democracy promotion — the Bush-era doctrine that America's security requires spreading democracy; the practitioner's defense of the Iraq decision",
    recognitionTier: "depth",
  },
  {
    name: "Adom Getachew",
    slug: "adom-getachew",
    domain: 'Political theory / "Worldmaking after Empire"',
    corePosition: "Anti-colonial movements built an alternative world order — sovereignty, self-determination, and the New International Economic Order as a competing vision that U.S. foreign policy suppressed",
    recognitionTier: "surprise",
  },
  {
    name: "Monica Duffy Toft",
    slug: "monica-duffy-toft",
    domain: "Political science / Tufts",
    corePosition: "Civil war termination and intervention — when outside intervention helps or hinders peace; the empirical record of what actually ends civil wars (often not negotiated settlements)",
    recognitionTier: "surprise",
  },
  {
    name: "Van Jackson",
    slug: "van-jackson",
    domain: "Political science / progressive realism",
    corePosition: "Progressive foreign policy is coherent — the left case for restraint, anti-militarism, and foreign policy for the working class; the emerging progressive realist synthesis",
    recognitionTier: "surprise",
  },
  {
    name: "Sarang Shidore",
    slug: "sarang-shidore",
    domain: "Geopolitics / Global South strategy",
    corePosition: "The Global South refuses to choose sides — India, Brazil, South Africa, and others are building strategic autonomy; the multipolar world Washington keeps denying is already here",
    recognitionTier: "surprise",
  },
  {
    name: "Neta Crawford",
    slug: "neta-crawford",
    domain: "Political science / Costs of War Project",
    corePosition: "The actual cost of post-9/11 wars — $8 trillion spent, nearly a million dead, counterterrorism goals largely unmet; the empirical accounting that indicts the War on Terror",
    recognitionTier: "surprise",
  },
  {
    name: "Patrick Porter",
    slug: "patrick-porter",
    domain: 'Strategic studies / "The False Promise of Liberal Order"',
    corePosition: "The liberal international order is a myth — it was always more partial, coercive, and contested than its advocates admit; honest reckoning with American power requires abandoning the myth",
    recognitionTier: "surprise",
  },
];
